### ISSUE TITLE
High Score Saving

### ISSUE THREAD

**Issue by cjszoo** [performous/performous#103]
I hope this isn't a dup..
Ive seen this issue for some time now, currently running nieknooijens windows build from 7/17/14.
I have somewhere around 300 songs, when you get to a certain point/number of high scores throughout the songs, certain songs (sometimes random) stop allowing you to save a high score. If i purge out the .dat file, i can save again but it comes back after playing for a little bit. It seems like once you hit a certain number of entries in the dat file, it starts acting up.
Is there anyway to make it use a score file in the directory with the txt/mp3 files? I cant remember the file extension or name of that but Ive seen it in some utltrastar files.

As always, you guys are great!

**Comment by twollgam** [comment]
@Baklap4 Is this still an issue? I think there is a database file in xml format now. And storing the scores in song folders could have problems with file permissions. If the songs are in system wide directories, users do not have write permissions. Songs could be on readonly media like DVD ...
