### ISSUE TITLE
ss_extract in Ubuntu 14.04

### ISSUE THREAD

**Issue by iqqmuT** [performous/performous#110]
ss_extract uses ffmpeg in ripping, however ffmpeg package is not available in Ubuntu 14.04.
I installed ffmpeg from a PPA but converting a video ended to the error:
```File for preset 'hq' not found```

Would it be possible to change ss_extract to use avconv?

EDIT:
Sorry, didn't note that this was already fixed in https://github.com/performous/performous/commit/b560e7ce675462057da0d710b0943e7c9f4465e1

**Comment by TobiX** [comment]
This should be okay again since 15.04, closing.
