### ISSUE TITLE
Make performous compatible with libswresample

### ISSUE THREAD

**Issue by akien-mga** [performous/performous#115]
I'm having trouble packaging Performous 1.0 for Mageia because we package ffmpeg's libswresample instead of libav's libavresample. The old fight between the two forks keeps harming the community...

If it's not too hard to manage, it would be great if you could make performous support libswresample as drop in replacement of libavresample. For now I've packaged a pre-1.0 snapshot where the libavresample dependency had not been introduced yet: https://svnweb.mageia.org/packages/cauldron/performous/current/SPECS/performous.spec?view=markup

**Comment by nieknooijens** [comment]
just some news on this bug, it seems that the next ubuntu will ship ffmpeg:
http://www.webupd8.org/2014/11/ffmpeg-returns-to-official-ubuntu.html
but again: as long as libavresample works either with libAV or ffmpeg I don't see the need for change.
