### ISSUE TITLE
Doesn't start in Windows 8.1

### ISSUE THREAD

**Issue by treefrog00** [performous/performous#118]
Is there an error log somewhere?

**Comment by rank-prism** [comment]
had the same issue, and the patch above worked like a charm. thanks.

**Comment by twiecki** [comment]
I'm running into this issue. I tried cross-compiling but it didn't work. Any chance on a new release with a windows binary that includes this fix?

**Comment by jamesjrg** [comment]
You can apply the patch without having to recompile because the shader code is only compiled when you actually start performous

**Comment by twiecki** [comment]
oh cool!

**Comment by twiecki** [comment]
I just applied the patch but the problem persists. Any way I can get the console output?

**Comment by nieknooijens** [comment]
here's one from latest master:
https://www.dropbox.com/s/pzhg3z2w2eb4s21/performous-build.zip?dl=0
here's one from latest webserver:
https://www.dropbox.com/s/2b9budw2qx5j4ga/performous-webserver.zip?dl=0

hope these work!

**Comment by twiecki** [comment]
@nieknooijens They do, many thanks!
