### ISSUE TITLE
Extreme lags with video

### ISSUE THREAD

**Issue by 3of8** [performous/performous#123]
I noticed one problem today that I never had before: every song with a video (without exception) lags so much that the game becomes completely unplayable. This occurs both with the version packaged in Ubuntu 14.10 and with the latest git version.

Workaround: remove the video, then everything works fine.

htop shows that there is plenty of free memory and the CPU is barely affected at all, so it cannot be a CPU load/swapping issue. I also moved a song (and the video) to my system SSD, so it can't be due to slow USB/external hard disc performance either. Is there anything in Performous's video buffering that could cause this issue?

**Comment by nieknooijens** [comment]
I tested it with the latest intel graphics stack and it works as expected (full speed). if you have an optimus card you shouldn't install it since it breaks nvidia hardware accelleration.
