### ISSUE TITLE
Unable to load Performous 1.0 on Windows 7 laptop

### ISSUE THREAD

**Issue by Yvannas** [performous/performous#125]
Hi there, I am unable to load Performous at all on my laptop. A white box flashes up and then disappears - nothing further happens.
I am running Win7 32bit on a laptop with a 2.30ghz Phenom processor, 4gb of ram and Radeon mobility graphics that are switchable between HD 6550 and AMD M880G HD 4250.
Please let me know if there is anything other info I can get that would be helpful - I will probably need instructions for most things but am pretty technically competent - I work in IT, just a different area. :-)

**Comment by nieknooijens** [comment]
I encountered this several times with some Nvidia cards where the manufacturer had installed the official driver, but only the directX part and not the OpenGL part. Please try updating your drivers from both intel and AMD and then try to run it on both the Intel and the AMD.
you can get the latest drivers here:
https://downloadcenter.intel.com/
http://support.amd.com/en-us/download

again this is probably due to your manufacturer that didn't include the required OpenGL libraries.

**Comment by Yvannas** [comment]
thanks for that - was already updating drivers :-) - only AMD though. Both of the gpu's are AMD. 
I will be sure to check for OpenGL and let you know how I get on.

**Comment by nieknooijens** [comment]
yeah numbers are a bit confusing, I have the HD4600 but that's from intel...

**Comment by TobiX** [comment]
Can you check %APPDATA%\performous\cache\infolog.txt for error messages?

**Comment by speich** [comment]
I have the same problem. Also I don't seem to have infolog.txt

**Comment by TobiX** [comment]
@speich You might want to create those directories then. There is currently a bug where we don't create those directories at all... I'' upload a prerelease later.

**Comment by speich** [comment]
Where should this directory be, in  %APPDATA%\local or  %APPDATA%\roaming ?

**Comment by nieknooijens** [comment]
Try both! Worst case scenario is an unused text file of 1kb
Op 5 apr. 2015 18:48 schreef "Simon Speich" <notifications@github.com>:

**Comment by TobiX** [comment]
Please try this test build: http://buildbox.23.gs/test/Performous-1.0-65-g6fa2124.exe

**Comment by speich** [comment]
Thank you. This build fixes the issue. I was able to install and run Performious now.

**Comment by TobiX** [comment]
@Yvannas Can you verify with the test build?

**Comment by TJC** [comment]
I'm on a Windows 8.1 laptop, Intel Core i3 CPU, with an nVidia GPU.
I get an an insta-crash as soon as I run Performous.exe.. Sounds a lot like issue reported above.

**Comment by TJC** [comment]
Testing with the g6fa2124 build, it seems to load fine.

**Comment by TobiX** [comment]
I consider this fixed, then. We should roll a 1.1 release later this week...

**Comment by page2pagepro** [comment]
System:
Dell Optiplex 960 SFF
HD5450 Video
SSD
Widows 7 x64

Using version below, file located in APPDATA does not exist:
%APPDATA%\performous\cache\infolog.txt

  File: Performous-1.0.exe
CRC-32: 945a5a6f
   MD4: 209ffda4f792ceb4a0538fc4e6f6e42a
   MD5: e114977d2f9b79e7953f5ca8afd0be49
 SHA-1: 1bdfe2070f14444b5a12ed578bcb8492aad3e3ee

Using Test build, I get results in TXT File:

  File: Performous-1.0-65-g6fa2124.exe
CRC-32: eab67441
   MD4: 2632817f0d35362b7dead8e408b96c65
   MD5: 6d7b21b224a476b6863aa3cba46df08c
 SHA-1: 4e2753866efc142e10bec5cf7fdf5709ad95a3b5



TXT Results:
logger/notice: Logging all notices, warnings and errors. Log file: C:\Users\USDX\AppData\Roaming\performous\cache\infolog.txt
core/notice: Performous 1.0 starting...
  Build date:           Oct 31 2014
  Internationalization: Enabled
  MIDI Hardware I/O:    Enabled
  Webcam support:       Disabled
core/notice: Starting the audio subsystem (errors printed on console may be ignored).
audio/error: Audio device 'out=2': Device doesn't have enough output channels
opengl/error: Shader color: Geometry shader was successfully compiled to run on hardware.

opengl/error: Shader surface: Geometry shader was successfully compiled to run on hardware.

opengl/error: Shader texture: Geometry shader was successfully compiled to run on hardware.

opengl/error: Shader 3dobject: Geometry shader was successfully compiled to run on hardware.

opengl/error: Shader dancenote: Geometry shader was successfully compiled to run on hardware.

opengl/error: Shader color: Vertex shader was successfully compiled to run on hardware.

opengl/error: Shader color: Fragment shader was successfully compiled to run on hardware.

opengl/error: Shader color: Vertex shader(s) linked, fragment shader(s) linked, geometry shader(s) linked.

opengl/error: Shader surface: Vertex shader was successfully compiled to run on hardware.

opengl/error: Shader surface: Fragment shader was successfully compiled to run on hardware.

opengl/error: Shader surface: Vertex shader(s) linked, fragment shader(s) linked, geometry shader(s) linked.

opengl/error: Shader texture: Vertex shader was successfully compiled to run on hardware.

opengl/error: Shader texture: Fragment shader was successfully compiled to run on hardware.

opengl/error: Shader texture: Vertex shader(s) linked, fragment shader(s) linked, geometry shader(s) linked.

opengl/error: Shader 3dobject: Vertex shader was successfully compiled to run on hardware.

opengl/error: Shader 3dobject: Fragment shader was successfully compiled to run on hardware.

opengl/error: Shader 3dobject: Vertex shader(s) linked, fragment shader(s) linked, geometry shader(s) linked.

opengl/error: Shader dancenote: Vertex shader was successfully compiled to run on hardware.

opengl/error: Shader dancenote: Fragment shader was successfully compiled to run on hardware.

opengl/error: Shader dancenote: Vertex shader(s) failed to link, fragment shader(s) failed to link, geometry shader(s) failed to link.
WARNING: warning(#276) Symbol 'vLightDir[0], vLightDir[1], vLightDir[2]' usage doesn't match between two stages
ERROR: error(#380) Too many inputs are used in geometry shader. 
WARNING: warning(#276) Symbol 'vLightDir[0], vLightDir[1], vLightDir[2]' usage doesn't match between two stages
ERROR: error(#380) Too many inputs are used in geometry shader. 
WARNING: warning(#276) Symbol 'vLightDir[0], vLightDir[1], vLightDir[2]' usage doesn't match between two stages
ERROR: error(#380) Too many inputs are used in geometry shader. 






I noticed I'd been using M$ native drivers for ATI:
1/26/2011
8.821.0.0




Followed advice and update Video driver:
  File: amd-catalyst-15.7.1-with-dotnet45-win7-64bit.exe
CRC-32: 2490a0ed
   MD4: ed8f010395b0412e2aacc2e2795d6ee7
   MD5: 758f4172a4c618b58193ad1a9bd632d2
 SHA-1: cd0fab7befa1f69f8dd0f15380e39f2430515e14



Now up to:
7/28/2015
15.200.1062.1003



PROBLEM SOLVED!
