### ISSUE TITLE
Crossfade in song browser is too long?

### ISSUE THREAD

**Issue by TobiX** [performous/performous#128]
Somebody reported to me that he thinks the crossfade in the song browser is too long and I have to agree.

The current value seems to be 2 seconds (set in line 202 of game/screen_songs.cc), should we reduce it to 1 second?

**Comment by nieknooijens** [comment]
It never bothered me but we could also just make it a config option.
I think we should re-categorize some of the config variables to keep it simple.

**Comment by tapio** [comment]
I find it too long too now that you mention it. I tried 1 sec and 0.5 sec and either is fine with me. However, I would not make this configurable as this is so small thing that it would only clutter the settings menu and it does not seem hard to reach a consensus on a good value.

**Comment by Tronic** [comment]
For the record, a long crossfade was originally used to hide some delays with song loading, especially with seeking to preview position which can take a while. There have been plenty of improvements made to the audio code since then. Perhaps such delays are less apparent with the current codebase.

**Comment by nieknooijens** [comment]
they are only apparent if I run other processes besides performous that heavily scan my Hard drive (for example a compiler or stepmania which is loading songs) but that's just silly to do!
