### ISSUE TITLE
TXT song parser should read track names for duets

### ISSUE THREAD

**Issue by TobiX** [performous/performous#141]
When using a duet song from Singstar (notes.xml), there is a nice "Artist" attribute which gets used to fill the selection screen. The TXT parser always uses "Vocals" and "Duet singer". There seem to be 2 competing "standards" how the singer name is encoded in UltraStar TXT files:

    #DUETSINGERP1:ArtistA
    #DUETSINGERP2:ArtistB

and

    #P1:ArtistA
    #P2:ArtistB

Performous should understand both formats.

**Comment by nieknooijens** [comment]
I have an event this weekend, but i'll try tot find soms time this weekend tot dive into it
