### ISSUE TITLE
Problem with Rockband Kit (Guitare and Drums)

### ISSUE THREAD

**Issue by Mrrisikoguru** [performous/performous#146]
Hi, I hope I'm right, because I don't know where I can ask to.

When I plug in only one of the devices, Performous do what they have to do =)
If I plug in the guitare and the drums then they change the both devices. It means: the drum behaves like the guitare and the guitare like the drums.
How can I fix it or what information do you need to help me?

I use the Performous 1.0 on windows 7 32bit.

Btw.: How I can open or where I can find the command line?

**Comment by nieknooijens** [comment]
I guess this has something to do with SDL2 handling the joysticks differently than SDL1.
The command line is "cmd.exe" on windows: http://windows.microsoft.com/en-us/windows-vista/open-a-command-prompt-window

**Comment by Mrrisikoguru** [comment]
Ok, but if I start performous in the commandline i don't get some feedback/output on the command line. Where or how I have to type in the commands like "--audio" and so on?

As a workaround I try to change the mappings in the controllers.xml but then nothing works. Is the idea complete wrong or do I something wrong?

At the moment there can play only 1 person (and 1 at the keyboard).

**Comment by nieknooijens** [comment]
isn' t that on the wiki?
https://github.com/performous/performous/wiki/Command-line-arguments

**Comment by Mrrisikoguru** [comment]
Ok, I have to run it on a terminal but I thought it means the command line (cmd in windows).
Also I said that if I run performous in the cmd nothing happens. What I have to do?

**Comment by TobiX** [comment]
We write a log file at %APPDATA%\performous\cache\infolog.txt, please check that for errors.

**Comment by Mrrisikoguru** [comment]
Sry, performous runs if I start it in the cmd but if I type
```
performous.exe --audiohelp
```
or so, then nothing happens.

PS: On the end of the log file I have many 
```
image/error: Reading PNG failed
```
Whats wrong with these files? Ingame I have some songs without a cover. I think thats the reason... I have only png with 400x400 or 500x500 pixel. Here an example that triggers an error:
![album](https://cloud.githubusercontent.com/assets/12664290/7985380/a16271dc-0ad0-11e5-8f9d-e4f133d509f5.png)

**Comment by ooshlablu** [comment]
I haven't run into this issue with any of my testing over the past year with many different Guitar Hero/Rock Band instruments. Most things have been mapped AFAICT, anything else can be easily added.

**Comment by Baklap4** [comment]
Closing this issue as it's probably be fixed by one of the already closed prs and this wasn't linked.
