### ISSUE TITLE
performous fails to build from source with GCC-5

### ISSUE THREAD

**Issue by apoleon** [performous/performous#150]
Hello,

apparently Performous fails to build from source with the latest version of the GNU C++ compiler. 

https://bugs.debian.org/778059

The Debian bug report contains more information including a full build log. I'm currently unable to verify this issue because the new gcc-5 toolchain is only available in Debian experimental and there seems to be another (possibly unrelated) issue with Boost. 

I will keep this bug report updated as soon as I can reproduce this issue myself.

**Comment by TobiX** [comment]
````
/«BUILDDIR»/performous-0.7.0+git20140715/game/songparser.hh:36:79: error: cannot convert 'std::basic_istream<char>' to 'bool' in return
  bool getline(std::string& line) { ++m_linenum; return std::getline(m_ss, line);}
````

That looks like something already failing in libc++/clang, which I recently fixed... Can you try with current master?

**Comment by apoleon** [comment]
I can't test master at the moment because the new GCC 5 toolchain is still in Debian experimental and there are some dependency problems with Boost. But as soon as GCC 5 is the new default in unstable, probably in two or three weeks, I will check again. Thanks.

**Comment by apoleon** [comment]
Hi,

I've tested master a few minutes ago and the issue is gone. You can close this bug report now. Thanks.
