### ISSUE TITLE
Performous crash when play duet songs

### ISSUE THREAD

**Issue by legluondunet** [performous/performous#151]
Hello,

performous crash when I choose a duet song. This is the terminal output:

$ ./performous
./performous  ~/Karaoke/
logger/notice: Logging all notices, warnings and errors. Log file: performous/infolog.txt
core/notice: Performous 1.0-85-g3d5f013 starting...
  Build date:           Jul 14 2015
  Internationalization: Enabled
  MIDI Hardware I/O:    Enabled
  Webcam support:       Enabled
core/notice: Starting the audio subsystem (errors printed on console may be ignored).
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:947:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:947:(find_matching_chmap) Found no matching channel map
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
audio/error: Audio device 'dev="Wireless Mic #122012370: USB Audio" mics=blue,red': No such device.
ffmpeg/warning: Negative audio timestamp -1.08844e-07 seconds, frame ignored.
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
[h264 @ 0x7fdfb8001320] missing picture in access unit
Erreur de segmentation (core dumped)

Thank you for your help.
My config:
Ubuntu 14.10
Graphic card: Intel® Ivybridge Mobile

**Comment by nieknooijens** [comment]
![schermafdruk van 2015-07-22 09 42 23](https://cloud.githubusercontent.com/assets/2794331/8820465/00018354-3056-11e5-8c01-7b0fcecbe1d4.png)

working perfectly here on both ubuntu 14.04 14.10 and 15.04
can you run GDB for us?

run performous using "gdb performous" then type "run".
when it crashes/freezes, go back to the terminal and type "bt" (backtrace) this will show us what the program's last instructions were.

**Comment by legluondunet** [comment]
If I run performous with GDB, it crashes before to show the interface...
Try this:
config all the microphone to none, enter to validate, launch a duet song, your performous crashes?

**Comment by nieknooijens** [comment]
yep that crashed it!  if you set two microphones to the default sound card (even if there is no mic attached) does that solve it?

**Comment by legluondunet** [comment]
effectively no more crash with your workaround.

**Comment by Lord-Kamina** [comment]
Haven't tried it recently but I've always used two (usb) mics on my
default/integrated sound card, without issue.

On Tuesday, July 28, 2015, legluondunet <notifications@github.com> wrote:

> effectively no more crash with your workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/151#issuecomment-125626300>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png]  Interno de
Medicina  Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by Baklap4** [comment]
This issue is solved by this commit: https://github.com/performous/performous/commit/3a5755ae690385f384e828161b715005853996e9
And can be closed.
