### ISSUE TITLE
Unable to add songs in Mac OS X Yosemite 10.10.3

### ISSUE THREAD

**Issue by jhmclane** [performous/performous#157]
I've placed folders named Songs in the following locations inside the performous.app package (inside Applications folder):

share/games/performous/songs/Joshua Morin - On the run
share/games/songs/Joshua Morin - On the run
share/songs/Joshua Morin - On the run

Example is one of the song folders downloaded from the Performous website.

However, after launching the application I still get a "no songs found" message when going into the Sing menu from the Performous home screen.

Would be very helpful to have either updated instructions _or_ one sample song included in the application package, to give an example of a path that works.

**Comment by Lord-Kamina** [comment]
Make sure they have the proper encoding; a lot of the songs downloaded from
the web will be un ISO-8859-1 or CP1252, when they should be UTF-8 instead.

On Thu, Aug 27, 2015 at 7:28 PM, jhmclane <notifications@github.com> wrote:

> I've placed folders named Songs in the following locations inside the
> performous.app package (inside Applications folder):
>
> share/games/performous/songs/Joshua Morin - On the run
> share/games/songs/Joshua Morin - On the run
> share/songs/Joshua Morin - On the run
>
> Example is one of the song folders downloaded from the Performous website.
>
> However, after launching the application I still get a "no songs found"
> message when going into the Sing menu from the Performous home screen.
>
> Would be very helpful to have either updated instructions *or* one sample
> song included in the application package, to give an example of a path that
> works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/157>.
>



-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by jhmclane** [comment]
Thanks for the encoding comment. Since I'm using the recommended songs from the Performous website I assume they're in the right format.

**Comment by Lord-Kamina** [comment]
Actually... Scratch that. Considering I packaged the Mac app... I don't
think I added those folders amongst the default path for songs (although
they could have been there from before, not sure)

I suggest you take the bull by the horns and check the config file in
~/.config, there you can check the defaults for sure or change them if it
suits you.

On Friday, August 28, 2015, jhmclane <notifications@github.com> wrote:

> Thanks for the encoding comment. Since I'm using the recommended songs
> from the Performous website I assume they're in the right format.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/157#issuecomment-135848855>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by keenanmoss** [comment]
Hi! I downloaded the program a few days ago. It works well but I can't add the songs folder. I'm using the same folder that I had on my windows XP, should I change something???

**Comment by Lord-Kamina** [comment]
The configuration file is, I believe, inside .performous/ in your home
folder. Try looking at the paths in there (or modify them as appropriate)

**Comment by Baklap4** [comment]
Statusupdate?

**Comment by nieknooijens** [comment]
I think #227 will fix this.
