### ISSUE TITLE
new notegraph layout

### ISSUE THREAD

**Issue by frankhedecke** [performous/performous#159]
Hey there,

I experimented with the notegraph. 

When three people sing their notes are colliding. So it's difficult for performers to follow them while singing.

I wrote a [version](https://github.com/frankhedecke/performous/tree/offset_view) with separate graphs for each performer. _The Code is merely hacked and not final_

What do you think about the idea of this layout? 

![offset_view](https://cloud.githubusercontent.com/assets/7064194/9718593/9156df10-557d-11e5-8e52-54424500827e.png)

**Comment by Baklap4** [comment]
Very awesome! But what if you play with 8 peoplr at once? Up to 3 will be viewable but i think the screen will get pretty crowded with 8 singing graphs...

**Comment by nieknooijens** [comment]
yeah, I do like the transparency-effect though! perhaps you could narrow the lines so you can actually see your individual colour even when using 8 players.

**Comment by TobiX** [comment]
You should probably remove the note names from the singing lines also ;)

**Comment by Lord-Kamina** [comment]
I like the note names. In fact it's one of the things I've always likee
better about performous over Ultrastar. Now... Re: separate graphs, USDX
does it that way but you need a second monitor to play with more than 3
players at once, as a result.

On Monday, September 7, 2015, Tobias Gruetzmacher <notifications@github.com>
wrote:

> You should probably remove the note names from the singing lines also ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/159#issuecomment-138350400>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by TobiX** [comment]
Maybe different modes should be configurable? I for one like the current presentation ;)

**Comment by frankhedecke** [comment]
### note scale
The note names currently match only the red bars. Maybe a note scale for each player is the solution.
The blue and green bars have just an offset to the y-value of the red bar.

### other things I will fix
The highlighting of the notebar while singing the correct bote, also just works with the red bar.

**Comment by frankhedecke** [comment]
### up to 8 players
For 8 players I suggest 4 notebar streams and by twos charing one stream.
- 1 .. 3 players: 1 .. 3 streams
- 4 players : 2 streams
- 5 .. 6 players : 3 streams
- 7 .. 8 players : 4 streams

### proper code
I made new SVGs for the 3 players. The graphics are hardcoded. In the future I try to use the color of the player for the bars.

**Comment by Lord-Kamina** [comment]
Customization is always good.

Also... The idea of varying the number of streams depending on the number
of players definitely sounds interesting.

On Monday, September 7, 2015, Tobias Gruetzmacher <notifications@github.com>
wrote:

> Maybe different modes should be configurable? I for one like the current
> presentation ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/159#issuecomment-138365376>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by nieknooijens** [comment]
what about duet-songs?

**Comment by frankhedecke** [comment]
imho duet-songs seems difficult. I'll think later about them.

**Comment by yoda-jm** [comment]
I'm not a big fan of this approach. I think it is more difficult to read where I stand while singing, and not having the proper note name is confusing.
Would it be possible to simply draw multiple times the notegraph:
- 2 singers: North - South
- 3 singers: North - Middle - South
- 4 singers: NW - NE - SW - SE
- 5 singers: NW - N - NE - SW - SE
- ...

**Comment by nieknooijens** [comment]
@yoda-jm then you'll need a 4K screen to fit it all!
currently the lowest resolution performous supports is 640x480 since most projectors nowadays start at 800x600 (with some exceptions, there are led-beamers that only output 320x240) so I don't mind if our minimum becomes 800x600 but you shouldn't force a minimum of 1920x1080!

**Comment by frankhedecke** [comment]
a small update. My [https://github.com/frankhedecke/performous/tree/offset_view](branch) now support all 8 standard microphone colors.

**Comment by frankhedecke** [comment]
... the note's color now matches the color of the player. The notes are now less transparent.

![offset_view_2](https://cloud.githubusercontent.com/assets/7064194/9876326/840ab834-5bb5-11e5-8f5c-81ac02e3c256.png)

**Comment by nieknooijens** [comment]
still, I like the flat abstract design and having them less transparent makes it easier to see.

**Comment by skyli91** [comment]
I like the colorful and flat design of the notes. It looks great :) but the incorrect note names are strange.
I'd like a design like duet mode is now, when 4 or more players are singing, the screen would split the same way as in duet mode, with two notelines image. But these colors would be nice to appear on the notes :) maybe the colors could be that color who is leading and has the most points :)

**Comment by Baklap4** [comment]
@frankhedecke is this development still going or? If so can you please report any updates regarding the matter? For now i'm considering this as `Inactive` and will therefore close the issue. However feel free to reopen this / create a pull request if you want to share something with the world.
