### ISSUE TITLE
Spotify support?

### ISSUE THREAD

**Issue by kipinae** [performous/performous#165]
Since most of my music now comes directly from Spotify instead of files or digital media, I was wondering if it was possible at all to support Spotify as a music source (at least for Unlimited/Premium users who get no ads)?

**Comment by Lord-Kamina** [comment]
I highly doubt it. Performous works with text files that define where, how long and which notes a song has. Besides the fact one would need to have this for all songs, it's also possible and common for these files to not be compatible with different versions of a song.

**Comment by nieknooijens** [comment]
spotify also has this nasty DRM stuff, I shoudn't support them.
https://www.defectivebydesign.org/spotify

**Comment by TobiX** [comment]
There are two things that make this impossible:
- We need metadata that isn't on spotify (lyrics, notes, etc.)
- Spotify uses DRM and DRM and open source are mutually exclusive.
