### ISSUE TITLE
Harmonix Guitar Controller for Nintendo Wii not found from controllers.xml.

### ISSUE THREAD

**Issue by arielenter** [performous/performous#170]
Just reporting what I got on performous today:

"Licensed by Nintendo of America  Harmonix Guitar Controller for Nintendo Wii (joystick 0)" not found from controllers.xml. Please report a bug if this is a game controller."

I'm using master. Thanks :)

**Comment by arielenter** [comment]
I added the following to controller.xml every thing seems to be working great:

		<controller type="guitar" name="GUITAR_ROCKBAND_WII">
			<description>RockBand Wii guitar</description>
			<device regex="Harmonix Guitar Controller for Nintendo Wii" />
			<mapping>
				<button hw="0" map="blue" />
				<button hw="1" map="green" />
				<button hw="2" map="red" />
				<button hw="3" map="yellow" />
				<button hw="4" map="orange" />
				<button hw="5" map="godmode" />
				<button hw="8" map="cancel" />
				<button hw="9" map="start" />
				<button hw="6" map="godmode" />
				<button hw="12" />
				<axis hw="2" map="whammy" />
				<axis hw="3" />
				<axis hw="4" negative="left" positive="right" />
				<axis hw="5" negative="pick_up" positive="pick_down" />
				<hat hw="0" up="pick_up" down="pick_down" left="left" right="right" />
			</mapping>
		</controller>

**Comment by nieknooijens** [comment]
for us to include controller mappings, we have to own one ;-) please send us a pull request and we will happily include this mapping into master.
