### ISSUE TITLE
Mac OSX 10.10.5 Font broken (Pango error)

### ISSUE THREAD

**Issue by m-o-p** [performous/performous#172]
I downloaded and installed the given MacOXS 10.6 (and never) dmg and get the following error and result as shown in thread #87 

(process:706): Pango-CRITICAL **: No modules found:
No builtin or dynamically loaded modules were found.
PangoFc will not work correctly.
This probably means there was an error in the creation of:
  '/opt/local/etc/pango/pango.modules'
You should create this file by running:
  pango-querymodules > '/opt/local/etc/pango/pango.modules'

(process:706): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='latin'
ffmpeg/info:  avutil:54.7.100(ff) avcodec:56.1.100(ff) avformat:56.4.101(ff) avresample:2.1.0(lav) swscale:3.0.100(ff)

**Comment by Lord-Kamina** [comment]
I am sorry but 10.6 is not currently supported. The 1.0 build I think works
with 10.8 onwards. For the new release (whenever that is) I think I've
managed to get it to work on 10.7 but I really doubt 10.6 will work well
since I've been building using the libc++ library.

On Friday, 25 December 2015, Marc-Oliver Pahl <notifications@github.com>
wrote:

> I downloaded and installed the given MacOXS 106 (and never) dmg and get
> the following error and result as shown in thread #87
> <https://github.com/performous/performous/issues/87>
>
> (process:706): Pango-CRITICAL **: No modules found:
> No builtin or dynamically loaded modules were found
> PangoFc will not work correctly
> This probably means there was an error in the creation of:
> '/opt/local/etc/pango/pangomodules'
> You should create this file by running:
> pango-querymodules > '/opt/local/etc/pango/pangomodules'
>
> (process:706): Pango-WARNING **: failed to choose a font, expect ugly
> output engine-type='PangoRenderCoreText', script='latin'
> ffmpeg/info: avutil:547100(ff) avcodec:561100(ff) avformat:564101(ff)
> avresample:210(lav) swscale:30100(ff)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/172>.
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by Lord-Kamina** [comment]
Wait. I'm asleep. Ignore that.
Try this build?
https://www.dropbox.com/s/anhd05bbrdvqdnp/Performous.dmg?dl=0

On Friday, 25 December 2015, Gregorio Litenstein <g.litenstein@gmail.com>
wrote:

> I am sorry but 10.6 is not currently supported. The 1.0 build I think
> works with 10.8 onwards. For the new release (whenever that is) I think
> I've managed to get it to work on 10.7 but I really doubt 10.6 will work
> well since I've been building using the libc++ library.
>
> On Friday, 25 December 2015, Marc-Oliver Pahl <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I downloaded and installed the given MacOXS 106 (and never) dmg and get
>> the following error and result as shown in thread #87
>> <https://github.com/performous/performous/issues/87>
>>
>> (process:706): Pango-CRITICAL **: No modules found:
>> No builtin or dynamically loaded modules were found
>> PangoFc will not work correctly
>> This probably means there was an error in the creation of:
>> '/opt/local/etc/pango/pangomodules'
>> You should create this file by running:
>> pango-querymodules > '/opt/local/etc/pango/pangomodules'
>>
>> (process:706): Pango-WARNING **: failed to choose a font, expect ugly
>> output engine-type='PangoRenderCoreText', script='latin'
>> ffmpeg/info: avutil:547100(ff) avcodec:561100(ff) avformat:564101(ff)
>> avresample:210(lav) swscale:30100(ff)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/performous/performous/issues/172>.
>>
>
>
> --
>
> --
>   Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de Medicina Facultad
> de Medicina Clí­nica Alemana - Universidad del Desarrollo
>
>    - Fono: +56 9 96343643
>    - E-Mail: g.litenstein@gmail.com
>    <javascript:_e(%7B%7D,'cvml','g.litenstein@gmail.com');>
>
>
>
>
>

-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by m-o-p** [comment]
After a first quick test: seems to work now - THANKS A LOT!

![screen shot 2015-12-26 at 00 29 47](https://cloud.githubusercontent.com/assets/7588878/12004618/663db204-ab68-11e5-8157-76ff6db7f6fc.png)

Only the Open GL warnings remain in debug mode.

**Comment by Lord-Kamina** [comment]
No problem. BTW That build says 1.0 but it's actually more like a 1.1 beta
since it was made a couple days ago from the latest trunk.

On Friday, 25 December 2015, Marc-Oliver Pahl <notifications@github.com>
wrote:

> After a first quick test: seems to work now - THANKS A LOT!
>
> [image: screen shot 2015-12-26 at 00 29 47]
> <https://cloud.githubusercontent.com/assets/7588878/12004618/663db204-ab68-11e5-8157-76ff6db7f6fc.png>
>
> Only the Open GL warnings remain in debug mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/172#issuecomment-167266874>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by nieknooijens** [comment]
Since it's fixed I think we can close this issue.
