### ISSUE TITLE
Gamepad support

### ISSUE THREAD

**Issue by kochd** [performous/performous#173]
Any chance to see gamepad support for the menu comming ?
Currently its keyboard only.

Edit: 
Okay. Wiki says actually there should be support for xboxdrv. I am using xpad as it the default and implemented into the linux kernel. Looks like xpad is not supported. 
Thanks

**Comment by nieknooijens** [comment]
There is controller mapping for various guitar hero and DDR pads in controllers.xml, not sure if you can control the full menu with it, I'll check that tomorrow.

**Comment by nieknooijens** [comment]
ok just checked it, and it does work but your controller has to be mapped in the controllers.xml and I found a few places where it's left broken. I can create mapping for the gamepads I have here but that probably won't help you. should I update the wiki explaining how to create new mappings?

**Comment by kochd** [comment]
We are probably talking about different things here.
You are talking about instrument like controllers to be used as instruments. I am talking about the xbox gamepad ( https://upload.wikimedia.org/wikipedia/commons/e/ed/Xbox-360-S-Controller.png ) to be used as an alternative to the keyboard for navigating through the performous menu.

**Comment by nieknooijens** [comment]
yes it is, but instruments can be used to navigate the menu. I tested it with an mayflash V2 DDR pad and a Logitech F310 (basically an xbox controller) the DDR pad worked fine, the logitech worked, but only DPAD left/right and start were mapped, even worse the DPAD left behaved like up! so it's probably mapped to some other DDR pad with the same discriptor. anyway you can map your controller into the controllers.xml like a dance pad and it will work.

**Comment by nieknooijens** [comment]
Closed due to no response from the original bug reporter.
Please add your controller mapping to the controllers.xml if you'd like to see this fixed for you.
