### ISSUE TITLE
[Webserver] searching + sorting the database + going back to search = bug

### ISSUE THREAD

**Issue by skyli91** [performous/performous#185]
Hi!
I've just noticed this bug.
searching > going to the view database tab > sort and refresh the database > go back to search > add songs to the playlist > check the playlist 
What happens is not the selected songs are getting added, but others.

**Comment by nieknooijens** [comment]
hi there, this probably has to do with the fact that autocomplete and the search button both use the same database object.
this means that doing a full query dumps the results in database, and then inputting more than 3 chars into the search bar overwrites this database object. if you then select something in the background search results (not the autocomplete) for example the second song from there, it will actually add the second song in the autocomplete results. this is indeed a bug and I'll look into it this weekend.
