### ISSUE TITLE
FPS limit

### ISSUE THREAD

**Issue by skyli91** [performous/performous#186]
When playing, the framerate goes up to 1200-1500fps (and my gpu is whining because of this), would it be possible to have a setting for fps limit? 60-72-75-120-144 fps maybe?

**Comment by nieknooijens** [comment]
usually VSYNC solves this and it should be enabled by default, at least I don't get more than 60FPS unless I boot performous in benchmark mode.
you could also "up the load" by increasing the SVG render size in the options.

**Comment by skyli91** [comment]
Oops i noticed that i just have to disable the show fps (benchmark mode?). Thanks for the help!
