### ISSUE TITLE
Multilingual support for webserver

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#188]
As for now the webserver look is written in one plain html file ([index.html](https://github.com/performous/performous/blob/master/data/themes/default/index.html)). It might be fancy to make it instead of english also multilingual?

So people can add their own language like with the core game.

A possible solution to this is to create a language api and add the language choice to index.html.  The API will return a json list with key-value pairs where the key is the name of the translated thing and value the translated value.

This way we can add the API to webserver.cc and maybe use the already used translation files?

**Comment by Baklap4** [comment]
I'm at the moment stuck on how one would get all the msgid's and msgstr's from one localization file. I know one could get the translation of one word by typing: _("some id here") or gettext("some id here") But i need all of the id's and strings from the localization file.

**Comment by nieknooijens** [comment]
wat could be done is an index.html for each language, but that gives duplicate code.
other way would be the android way, making a strings.xml or strings.json and swap that one out.
we should look into jquery's localisation stuff.

**Comment by Baklap4** [comment]
An index for every language is lame and gives indeed duplicate code. At this very moment i'm trying to work with the po files.  Yet getting some undefined reference error while linking the executable -.-" If i fixed this we will be able to write the things for the webserver to PO files. And it should all work :)

**Comment by Baklap4** [comment]
Closed since #280 has been merged to master
