### ISSUE TITLE
Keys without the [Left Ctrl] have to be pressed while singing

### ISSUE THREAD

**Issue by skyli91** [performous/performous#190]
Reasons:
- Pressing LCTR+K or LCTRL+. is very hard with one hand. Also these: =,(,)
- I don't think anyone would accidentally press a key while singing but if so, then only the latency settings should need the CTRL modifier (and maybe could work with the right ctrl too). 

I think ctrl shouldn't be needed for S, K, C, H, V, W, A <- because these are easy to undo :) And if someone is used to ctrl + these keys, it could work too.

**Comment by nieknooijens** [comment]
@TobiX what do you think about this?

**Comment by Baklap4** [comment]
I dont know if right control is used atm? If not why not bind it to all the control commands? Same with right shift and right alt and combinations of those?

**Comment by Baklap4** [comment]
Closing this in favor of #522 

@skyli91  feel free to give more input on that issue :)!
