### ISSUE TITLE
Error launching Performous 1.1 on Windows 7

### ISSUE THREAD

**Issue by montrevel** [performous/performous#196]
Hello,

I installed Performous 1.1 on Windows 7.

I have an error when I try to launch it : 
![error_performous](https://cloud.githubusercontent.com/assets/20172548/16391155/26a49728-3ca6-11e6-8485-d5aa02ee739d.jpg)

Do you know what the problem is and how I can fix it ?

Thank you !

**Comment by Baklap4** [comment]
Could you post your config.xml?

**Comment by montrevel** [comment]
I find the problem for this error, Performous 1.0 wasn't totally uninstalled.

Now Performous 1.1 launch, but I have this message : 
![error_performous2](https://cloud.githubusercontent.com/assets/20172548/16417788/831af852-3d47-11e6-94a2-ded828892a21.jpg)

How should I do to fix that ?
My Windows 7 sound system is very standard and Performous 0.5 was working fine.

For information, I have no config.xml now, I don't no if it is normal. My infolog.txt if it helps : 
[infolog.txt](https://github.com/performous/performous/files/337155/infolog.txt)


Thank you !

**Comment by nieknooijens** [comment]
go to settings->audio devices and configure it as such:
![schermafdruk van 2016-06-28 17-19-05](https://cloud.githubusercontent.com/assets/2794331/16421193/73b29f5c-3d54-11e6-9b33-371b9b2da59a.png)

**Comment by montrevel** [comment]
Thank you very much it's OK now ! :-)
