### ISSUE TITLE
Playlist enhancements

### ISSUE THREAD

**Issue by skyli91** [performous/performous#198]
- option to move a song to the top of the playlist
- pressing a number while in the playlist viewer should move that song to the that position on the playlist (eg. pressing 3 would move that song to the third place)
- when a playlist is active in the song browsing screen, make it possible to play a song immediately out of turn (not having to open playlist, scroll to the end and play - it's slow) - maybe one more down arrow on the song browser would have play song, under the "show the songlist menu" option.
- drag and drop (web)

**Comment by Baklap4** [comment]
I'd like to add drag and drop to this list as well.

**Comment by skyli91** [comment]
I thought about the ingame playlist but drag n drop to the web would be nice too

**Comment by Baklap4** [comment]
Enhancement comitted as in: https://github.com/performous/performous/pull/215/commits/f702b3a6328476e71168fcde496088998934fc62 pull request is active in #215 

This features:
* Moving a song to the top of the playlist (through the webserver) (by setting position to 1)
* Moving a song to desired place in the playlist
# Does not feature:
* drag&drop someday i'll implement it but for now it's already a lot faster changing position of songs ;)

**Comment by Baklap4** [comment]
@skyli91 I've made drag and drop available in a pull request (with new frontend see: https://github.com/performous/performous/pull/251/commits/7e5f77fe31224bc475afd5ff91b2f0650b75897c) When this is in master i'll close this.
