### ISSUE TITLE
Microphone colors rendering order

### ISSUE THREAD

**Issue by skyli91** [performous/performous#199]
I think when singing, the pitchwave of the player with the most points should be on the top.
Now the order is strange yellow>purple>green>red>blue>lightblue it seems hard coded.

If you are playing with 6-7 players, not everyone can see their colors, just those that are on the top so it should be those who has the most points :)

![image](https://cloud.githubusercontent.com/assets/7442913/16544986/17adecdc-411b-11e6-9294-8e3a4ea5fa55.png)

**Comment by Baklap4** [comment]
@skyli91 can you give #653 a try? I've tested it a bit ago and it seems to be resolved with that PR
