### ISSUE TITLE
[webserver] Database list add song functionality

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#203]
While doing events i don't use books to show them my songs I use the database provided by the webserver.
When people want to look for a song (scroll through the long list of songs) they often expect that pressing a song would add the song. 
This is not implemented so it does nothing then just selecting text.
# Feature request
- add `OnClick()` listener to each different song (on the first tab when the button "refresh database" is clicked)
- `OnClick()` listener would add the clicked song to the playlist.

**Comment by nieknooijens** [comment]
I tried that at first but when loading a table of 5000+ songs my tablet is
already struggling! Load 5000 buttons and the result is a huge lag in the
interface

Op 24 jul. 2016 21:00 schreef "Arjan Spieard" <notifications@github.com>:

**Comment by Baklap4** [comment]
@nieknooijens This would be solved by introducing pagination with maybe an index on the first letter like usdb does with 'browsing for songs'
![image](https://cloud.githubusercontent.com/assets/3918517/17095131/47fbed50-5253-11e6-8dea-3d4262385522.png)

**Comment by Baklap4** [comment]
closed since #280 has been merged into master introducing a feature to click on a song which adds it to the playlist
