### ISSUE TITLE
[webserver] Set position of song in playlist.

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#204]
Sometimes the one hosting karaoke wants to troll around and rick roll everyone for example.
Currently one has to:
- add a song to the playlist
- Click the desired song
- Click Move up/down button
- Repeat step 2 and 3 to the desired place.
# Feature Request

When clicking a song one can choose another menu "Set position"
Then enter a valid position

A valid position is the range of 0 to the amount of songs currently in the playlist
# Feature Request 2

Move song to top or bottom.

**Comment by nieknooijens** [comment]
There's already a "play this song first" option. Isn't that basically the
same as "move to top"?

Op 24 jul. 2016 21:09 schreef "Arjan Spieard" <notifications@github.com>:

**Comment by Baklap4** [comment]
The play this song first option is only available in the songbrowser / playlist show

This is good, but not the best place to do at.
It'd be nice to do this within the browser. This way one does not have to interupt the game while it's being modified from the "outside"
The set position thing can be done by creating a drag/drop list of the current playlist
