### ISSUE TITLE
The web and wiki are not working

### ISSUE THREAD

**Issue by Krakonos** [performous/performous#206]
The wiki does not seem to have a DNS record, the performous.org points to a pages.github.com, forces https and this doesn't work at least in firefox 47, as the ssl cert is for completely different domain.

I know this isn't exactly a program issue, but don't know any other way to report it.

**Comment by Baklap4** [comment]
We are aware of this problem. As this is about the website i'll close this issue. As the same issue is made at our web repo: https://github.com/performous/web/issues/4
