### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by DSigmund** [performous/performous#208]
Google notifies about SSL-Errors...

**Comment by Baklap4** [comment]
This issue is already tracked within the web project: https://github.com/performous/web/issues/4

**Comment by DSigmund** [comment]
Sorry, my mistake

**Comment by Baklap4** [comment]
@DSigmund currently it's live on my server. Since performous.org is hosted by someone and he is currently not quite active i thought why not host it myself. It's available here: https://performous.asgardsings.nl

**Comment by yoda-jm** [comment]
Hello,

The site is hosted on github pages, the problem is that we need to revoke the old certificate.

**Comment by nieknooijens** [comment]
can't you setup a cron-job that fires every month which renews the certificate? (letsencrypt for example)

**Comment by Baklap4** [comment]
Right now it's hosted on github pages which by default doesn't support custom domains as https. We could use something like cloudflare as a proxy to github pages so the certificate won't be broken, or just revoke the certificate for performous.org and i'll just set it up on my server with letsencrypt as i have right now on my domain previously mentioned
