### ISSUE TITLE
[webserver] Add Language + Edition to search list

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#209]
Add Language and Edition to the search list in the browser.

This will result in a list containing:
`Artist - Title | Language - Edition`
So as an example result:

`Frozen - Let It Go | Dutch - Disney`

This way it's easier to determine the language of the song if it's available in multiple languages.
If you want to see the language currently you have to add the song to the playlist and click on an item in the list to see its details. This should stay and be extended with #204 

![image](https://cloud.githubusercontent.com/assets/3918517/21871544/1bf42be6-d863-11e6-82c9-8977d2eb11c8.png)

**Comment by nieknooijens** [comment]
would be nice, but can be cumbersome on small (phone) screens. is there a way to detect the size of the screen?

**Comment by Baklap4** [comment]
@nieknooijens Since we're already using jquery why not use `$(window).width()` and `$(window).height()` to detect width and height. If a screen is small (in width) than do not show it or show the string till it fits the screen and suffix with `...` if the string it bigger than screenwidth like this: `Band - Song | Dutc...`
While onhover you can show a tooltip perhaps which will fit on the screen? a jquery plugin can be used: https://github.com/FrDH/jQuery.dotdotdot
