### ISSUE TITLE
[Webserver] Fix Searching

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#210]
Currently searching works but when one uses special characters like in this searchstring: `(karaoke)` it won't filter correctly.

I can however escape the characters and it does work correctly then. So if i'm searching on: `\(karaoke\)` it shows me all results which contains the seachstring.

**Comment by nieknooijens** [comment]
is this in the webserver, song-chooser (local) or both?

**Comment by Baklap4** [comment]
Apparently it's also not working within the songbrowser (within the game)

Add txtfile with within the title `(karaoke)`
And add a few textfiles more without `(karaoke)` in the title
Try searching for `(karaoke)`
Result: Every file will be found
Expected result: Only the one with `(karaoke)` in the title should return

**Comment by nieknooijens** [comment]
![schermafdruk van 2017-01-22 10-55-12](https://cloud.githubusercontent.com/assets/2794331/22181696/6f37cda4-e091-11e6-8236-9806d69e3766.png)
![schermafdruk van 2017-01-22 10-55-41](https://cloud.githubusercontent.com/assets/2794331/22181694/6f35d206-e091-11e6-9d88-e439a0788cf8.png)
![schermafdruk van 2017-01-22 10-55-52](https://cloud.githubusercontent.com/assets/2794331/22181695/6f365500-e091-11e6-8fe7-7e2cbeb6c191.png)

filter seems to work just fine here.

**Comment by Baklap4** [comment]
Hmmm very weird i thought it was maybe one of the libraries but i'm still up to date. Maybe it's part of localization? What locales do you have installed?

**Comment by Baklap4** [comment]
Closing this since it's only at my laptop this way.

# Workaround
Escape special characters with a `\`
