### ISSUE TITLE
Title is not good visible while in singing mode.

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#216]
Some letters of the title in singing mode aren't good to read:
![image](https://cloud.githubusercontent.com/assets/3918517/22173906/5423e528-dfd0-11e6-8c4f-d52c8c6a4d89.png)

In my screenshot it should say: `John Legend - All of me`
This is the same in fullscreen mode.

**Comment by nieknooijens** [comment]
![schermafdruk van 2017-01-22 10-52-54](https://cloud.githubusercontent.com/assets/2794331/22181668/faef692a-e090-11e6-8e79-0b0244a1c056.png)
weird... works perfectly here.

**Comment by Baklap4** [comment]
This seems to be part of the text quality setting. I had it on 1.5
Now i have it at 3.0 and all shows well. Does this help in reproducing?

**Comment by nieknooijens** [comment]
yeah, you can also scale up the text in the file /data/themes/default/sing-songinfo.svg
it uses that files as base for the text scale and position.
