### ISSUE TITLE
Github cleanup

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#217]
# Branches cleanup
Are these branches still worked on?
If so please update them to current master and get the feature done.

# **If there's no reaction within a month I'll remove them.**

# List of Branches + owners

- [songmerge](https://github.com/performous/performous/tree/songmerge) @nieknooijens | **CLEANED**
- [webserver](https://github.com/performous/performous/tree/webserver) **CLEANED**
- [danceoverhaul](https://github.com/performous/performous/tree/danceoverhaul) @nieknooijens | **CLEANED**
- [qrCodeSupport](https://github.com/performous/performous/tree/qrCodeSupport) @baklap4
- [stereo3d-interlaced](https://github.com/performous/performous/tree/stereo3d-interlaced) Lasse Karkkainen / deleted user. What does this do?
- [stdthread](https://github.com/performous/performous/tree/stdthread) @Tronic 
- [dance3d](https://github.com/performous/performous/tree/dance3d) @Tronic (Obsolete with danceoverhaul?)
- [torrent](https://github.com/performous/performous/tree/torrent) @Tronic @yoda-jm 
- [egl](https://github.com/performous/performous/tree/egl) @tapio we're already using libepoxy?
- [legacy](https://github.com/performous/performous/tree/legacy) @Tronic @yoda-jm Why would we want this? and if we want to support older versions and apply hotfixes.. why aren't there any other legacy branches?

**Comment by nieknooijens** [comment]
songmerge was an idea of mine, but it looks like some weird pointer stuff is happening, I think it's best if I re-do this feature by starting from scratch. so I deleted the repo

**Comment by nieknooijens** [comment]
how about old issues? (2 years or older)

**Comment by Baklap4** [comment]
Add a comment in the issue to see if it's still relevant and ppl still want to have it updated.

**Comment by nieknooijens** [comment]
or just close them. if you close the issue the guy who opened it gets an e-mail. if he/she still thinks it's relevant he/she could just click "reopen".

**Comment by TobiX** [comment]
I don't see any reason why one should remove old branches. Most of them document experiments or started ideas.

For example: The egl branch might still contain some shader changes needed for proper egl support...

**Comment by Baklap4** [comment]
> I don't see any reason why one should remove old branches. Most of them document experiments or started ideas.
> For example: The egl branch might still contain some shader changes needed for proper egl support...

If these branches do contain something handy one should add these features. Not wait 4 years. Within 4 year a lot of technology have changed and therefore something you've programmed back then might not be as efficient as it could be written right now.

**Comment by TobiX** [comment]
Since you clearly know what is better for this project, consider this my resignation, goodbye.

**Comment by Lord-Kamina** [comment]
I do agree with Tobias, plus it's not like the branches being there is
detrimental in any way to the repository. Also, IMO it'd be really sad to
see him go :(

**Comment by Baklap4** [comment]
I've just proposed an idea; it was never my intention to get rid of people :( 

No it's not harmful in any way to the repository, but since there has been 0 activity to the stale branches why would you keep them?

I understand some of them might have awesome stuff in it and good new things. But then why not merge them back to master? If i see code which haven't been touched for 4 years and is not within the release version.. then i think there's no point in keeping them. 

Reason 1) merging master back into the branch may be difficult since a lot is changed during these 4 years. 
Reason 2) updating the libraries to the current ones and calls to them can be a pain in the ass aswell.
Reason 3) You'll get the same thing which happened to the webserver branch: https://github.com/performous/performous/pull/145#issuecomment-157365492
Reason 4) If you wanted the code to be in Performous-master you'd have already.

**Comment by yoda-jm** [comment]
I'm strongly against removing old branches, please *do not proceed*

**Comment by Baklap4** [comment]
> I'm strongly against removing old branches, please do not proceed
@yoda-jm please explain why?

**Comment by yoda-jm** [comment]
Some reasons for not proceeding:
- it doesn't bother (or please give what bother, maybe removing the branches is not what we want to do),
- we do not want to rewrite history (removing something from git is modifying past state),
- we do not want to remove past work (even unfinished/unused), tries contains information, even when it doesn't work,
- someone might want to look at the idea, maybe in 10 years, maybe using totally different code (but still what was done and when might be interesting).
