### ISSUE TITLE
I'm leaving

### ISSUE THREAD

**Issue by TobiX** [performous/performous#218]
As already mentioned in #217, I'm formally leaving the Performous project. I might contribute in the future from the outside, but I want to make clear that I won't be available for releases/builds or other organizational stuff. There are some reasons why I'm doing this:

- I was only ever interested in the singing part of Performous, not anything else
- The reason why I started using Performous vanished
- In recent months I wasn't doing much for the project anyways
- I have some ideas how a project should be managed, which I shouldn't impose on a project I'm not contributing much at all...

It would be nice if you could remove me from the Semaphore project (there seems to be some restriction, which make this hard: https://semaphoreci.com/docs/organizations/transferring-organization-ownership.html) - Maybe just switch to Travis-CI (which wasn't possible when we started using CI, since their Ubuntu was way to old).

I wish you all the best!

(PS: I might have overreacted in #217, that ticket is not the single reason I'm doing this, but it was "the straw that broke the camel's back")

**Comment by nieknooijens** [comment]
I' m sorry to hear that you' re leaving, but I think it' s better this way than to just disappear into nothing like Tapio and Tronic did. I do want to mention that @Baklap4  and I intend to keep the project alive and keep maintaining and improving the project.

**Comment by basisbit** [comment]
hello everyone, @TobiX and me met at the Gullaschprogrammiernacht maker/hacker event in Karlsruhe this year and we talked about how to make open source singstar-like karaoke even more fun. One thing was that we would like to add some neat features to performous which I added to USDX already lately. In the long term, it would be nice if we could replace the USDX codebase (which takes just too much work to maintain) and establish performous as the main singstar-alike karaoke game.
I hope to be able to work together with @TobiX + the other developers of performous and have fun at coding!

**Comment by nieknooijens** [comment]
@basisbit that's great news, unfortunately this project isn't in the best state atm. @Baklap4 and me are currently maintaining this repo, but since we're not "repo owner" (that's @tapio  and @Tronic ) we can't add members to the contributors group so ATM contributing is only possible with forks and pull-requests.

**Comment by basisbit** [comment]
when was the last time @tapio or @Tronic were reachable? Pull requests are fine for me for now, as I am "new" to this project anyways 😃

**Comment by TobiX** [comment]
Damn, I shouldn't have removed myself as project administrator 🤦‍ - Yeah, I can't promise too much, but I'll try to contribute here and there...

**Comment by basisbit** [comment]
trying once again... are @tapio or @Tronic still reachable or when was the last time that they are reachable?
Once no project admin can be reached any more, a github project is considered "dead", so this should be fixed quickly somehow.

**Comment by Baklap4** [comment]
Reopened since the action: Making @nieknooijens admin has not been accomplished yet.
@yoda-jm @tapio @Tronic Can any of you make @nieknooijens admin?

When done please close this issue :)

**Comment by nieknooijens** [comment]
yeah I sent in a request to join the admin group like 2 years ago. I think it's still pending.
Whether you accept or reject it, is up to you, just pick either one of them.
I would like to thank @tapio  for helping me out during the early days when I joined here, I possibly learned more about c++ and git by working on this project and getting valuable feedback than I could've ever learn in college. This helped me graduate last Februari! :smiley: I'm currently working full time at a small electronics company, while in the weekends I place performous at various events. So I think I'll be maintaining this project in the foreseeable future.

**Comment by tapio** [comment]
@nieknooijens now has elevated access. Thank you for the continued time and effort you've put in the project!

**Comment by Baklap4** [comment]
I just wrote @yoda-jm an email concerning this. He can ignore it now :joy:

Thanks @tapio
