### ISSUE TITLE
Black bars in playlist view if title is too long

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#222]
While adding songs to the playlist i've noticed sometimes there are black bars concealing the titles in the screen.
This is pretty annoying so maybe we should check the length of the text and based upon that set the textsize or something? can't add a picture right now.

**Comment by nieknooijens** [comment]
the weird thing is that I don't encounter this on my PC using both the Nvidia GT840M, and intel HD4000

**Comment by Lord-Kamina** [comment]
Is
Is this in master?

**Comment by Baklap4** [comment]
This is still within current master on both of my nvidia gt840m and intel HD4600

**Comment by Lord-Kamina** [comment]
And was it also a thing on 1.1? Wondering whether it's an old bug or
introduced by my resolution branch.

**Comment by Baklap4** [comment]
@Lord-Kamina let me check

**Comment by Baklap4** [comment]
On Tag 1.1 running on NVIDIA GT840m And intel hd4600 in songbrowser it works alright:
![image](https://user-images.githubusercontent.com/3918517/31637502-4b7a2b6c-b2cf-11e7-8dea-dea43f4a744a.png)
However on the playlist screen there's this black bars:
![image](https://user-images.githubusercontent.com/3918517/31637516-5c9cd8c2-b2cf-11e7-82f0-e46232210071.png)

OpenGl spews out an error:
```
opengl/error: Invalid value in Surface::load postcondition
opengl/error: Invalid value in Surface::load postcondition
opengl/error: Invalid value in Surface::load postcondition
opengl/error: Invalid value in Surface::load postcondition
opengl/error: Invalid value in Surface::load postcondition
```
This error occurs everytime the black bars are selected

**Comment by Baklap4** [comment]
@Lord-Kamina an intresting thing is i'm seeing `menu.dimensions.stretch(wcounter, 1);` in menu's regarding configuration where all of the text is shown properly and scaled correctly. However i cant seem to find it in `screen_playlist.cc`  When for example saying `songlist_menu.dimensions.stretch(0.342308, 1);` in the draw of `screen_playlist.cc` it doesn't affect anything...

**Comment by Baklap4** [comment]
I think i've found the issue...

as posted on Discord:

> It's a thing in the text quality settings
> or atleast related to it. Currently set to 3.0 it shows me black boxes
> at everything above 2.5 it shows me black boxes
> svg setting is set to 2.0 but can be set to whatever your pc can handle
> So i'm currently wondering how that setting is used and why i can't go beyond 2.5 text quality (while 6 is the max)

> i have no clue about the calculations in SvgTxtTheme::draw(std::vector<TZoomText>& _text) in file opengl_text.cc But my bet is the rectangle where the text is drawn is bigger than it should be while using a text factor bigger than 2.5 therefore it's rendering a black box can someone verify this? @Lord Kamina

@Lord-Kamina @nieknooijens can any of you reproduce this with higher text settings?

**Comment by Baklap4** [comment]
Closing as none can reproduce this.
