### ISSUE TITLE
OSX Crash when first setting up webserver

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#225]
I was trying out the webserver build and Performous crashed on quitting, after enabling webserver.

[performous_2017-02-17-010629_Anasas.txt](https://github.com/performous/performous/files/782270/performous_2017-02-17-010629_Anasas.txt)

It only happened the first time and the webserver appears to be operating as expected, but figured you might want to know.

**Comment by Baklap4** [comment]
@Lord-Kamina is it still crashing ?

**Comment by MagicChocoRolls** [comment]
Hi there,

Two weeks ago I had a singing session with friends where we wanted to try out the webserver. I used a build I created myself.
I had some random crashes of performous itself (without even using the webserver, but having it configured) and a lot more using the webserver. It was not deterministic when performous crashes. After about 5 crashes we went back to a version without webserver support. That worked like a charm.
Unfortunately I had no time collecting debug information, but I can try it out again to provide some more info.
For me, the webserver is not usable as is :-(

**Comment by Baklap4** [comment]
Hmmm sorry to hear @MagicChocoRolls :( We'd love some debug info regarding the crashes :+1:

**Comment by Lord-Kamina** [comment]
If you have access to the mac you used, the crash logs from macOS itself
should be present still in your console (they usually get saved to disk as
individual .crash files under User Reports). It would help a bit if you
could post those, and of course the performous log when you can try it out
again.

**Comment by MagicChocoRolls** [comment]
> If you have access to the mac you used, the crash logs from macOS itself
should be present still in your console (they usually get saved to disk as
individual .crash files under User Reports). It would help a bit if you
could post those, and of course the performous log when you can try it out
again.

Niiiiiice :) Didn't know about that.

I will give you all three crash logs from that day.

[crashlogs.zip](https://github.com/performous/performous/files/1111283/crashlogs.zip)

**Comment by Baklap4** [comment]
@Lord-Kamina is this still relevant with the updated way to check ip address? as per https://github.com/performous/performous/commit/39929f644a152d94c3baffb02c65b82d016f9607

**Comment by Lord-Kamina** [comment]
I don't know, I think the crash was not actually caused by the IP detection
(as that exception was caught by the "cannot determine ip" message)

It might actually have been a manifestation of the webserver exit crash.
I'll try to reproduce it later.

**Comment by Baklap4** [comment]
@Lord-Kamina can you try this on current master?

**Comment by Baklap4** [comment]
Closed because of fix #241
