### ISSUE TITLE
update jquery and jquery mobile to the latest versions

### ISSUE THREAD

**Issue by nieknooijens** [performous/performous#230]
since the webserver can be used offline now we should update jquery and jquery mobile.
Some javascript calls from the old jquery are being deprecated as we speak, so see it as necessary maintenance.

**Comment by Baklap4** [comment]
@nieknooijens do we really have to use jquery-mobile? since jquery-mobile supports up to jquery 2.1.1 while jquery itself is already at 3.2.1
Bootstrap for example is capable of using jquery 3.2.1

I'll be looking forward to make it work with bootstrap

**Comment by nieknooijens** [comment]
sure go ahead! (in a seperate branch of course)
since the mime-type stuff is fixed now nothing is stopping you from adding whatever you like into the webserver :wink:
