### ISSUE TITLE
[Webserver] Optimize mobile/tablet layout

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#231]
@nieknooijens and i are currently having troubles with the webserver layout. Since we do have over 5000 songs the webfrontend will consume a whole lot more memory and therefore running quite slow and sometimes even crashing the browser on a mobile/tablet device.

We should optimize this. I'm not quite sure but i guess it has something to do with the rendering of html. This can be solved by creating a more basic table (without styling) on mobile devices or find a way to optimize the current css.

Here are some "rules" set by Google to help write better more performant css/js code: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

**Comment by nieknooijens** [comment]
maybe updating jquery will make it speedier?

**Comment by Baklap4** [comment]
Updating jquery will make it a bit speedier, however its still a lot of data and will still be rendered pretty slow i think but lets see what #230 bring in for performance on this end.
