### ISSUE TITLE
Keypressed Loop

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#232]
While sorting out songs i came acros this 'bug'

# Act
Within the song browser i'm holding the Right arrow. Then i press ctrl + R 

# Thought it'd do
Reload the whole song library.

# It does the following
- Reloads the song library and keeps on browsing songs to the right, which heavenly speeds up the animation.

# To stop the loop
- Press the same arrow key and quickly press the oposite arrow key.

**Comment by Tronic** [comment]
I cannot reproduce this. If holding right arrow, Cmd+R does nothing. If I briefly release and then reload, it simply stops the browsing. Is this still broken for you?

**Comment by Baklap4** [comment]
This is still happening in current master

**Comment by Lord-Kamina** [comment]
Will see if I can reproduce over the weekend

**Comment by Baklap4** [comment]
Might be just on linux and windows i encountered it on both systems

**Comment by Baklap4** [comment]
I can still reproduce this behavior in both ubuntu 2104 and windows 10 at latest master.

Another way to consistenly reproduce this bug:
While in the songbrowser hold down the right arrow key
Random press (LEFT)CTRL and let go of **both** keys at the same time.


You can stop this loop by pressing the right arrow key again followed by a left arrow key.

**Comment by Lord-Kamina** [comment]
> I can still reproduce this behavior in both ubuntu 2104 and windows 10 at latest master.
> 
> Another way to consistenly reproduce this bug:
> While in the songbrowser hold down the right arrow key
> Random press (LEFT)CTRL and let go of **both** keys at the same time.
> 
> You can stop this loop by pressing the right arrow key again followed by a left arrow key.

I can reproduce it via this method (although using **Cmd** instead of **Ctrl**), but not the way you initially reported it.

**Comment by Baklap4** [comment]
The common factor is the `Ctrl` or `Cmd` (on mac)

**Comment by ooshlablu** [comment]
I can reproduce this on Ubuntu 18.04 & 20.04 and MacOS. I also noticed that if you hit escape to try to get out of it, it follows you to the main menu, which results in the cursor hanging on "Quit". Pressing enter there does let you exit the game.

**Comment by Baklap4** [comment]
> I also noticed that if you hit escape to try to get out of it, it follows you to the main menu, which results in the cursor hanging on "Quit". Pressing enter there does let you exit the game.

Correct noticed that aswell
