### ISSUE TITLE
set up CI with two way Github integration

### ISSUE THREAD

**Issue by basisbit** [performous/performous#238]
The currently used continuous integration solution does not show in github if a build succeeded or failed. Many CI solutions provide such feature (two-way github integration) and thus easily show for example that a new pull request breaks building performous (and/or tests), thus giving the creator of the pull request the possibility to quickly fix these problems.
example:
![image](https://user-images.githubusercontent.com/10870269/27225162-4aa897c8-5299-11e7-926d-824b987218bd.png)

More details about supported continuous integrations sytems with such deep github integration can be found at https://github.com/marketplace/category/continuous-integration

Is there any possibility to get this working using our current CI setup?

**Comment by nieknooijens** [comment]
we used to have that, but semaphore apparently broke down? :confused:

**Comment by Baklap4** [comment]
We had it when we still used travis if i'm correct. Within semaphore i don't see any option for this... @TobiX do you know more about this?

**Comment by TobiX** [comment]
We never used Travis. The integration probably broke when I removed my OAuth tokens. Since I currently don't have admin access, I can't fix that.

**Comment by Baklap4** [comment]
Hmm alright, so @nieknooijens can just add his oauth token, and then all would work again ?

**Comment by Baklap4** [comment]
@nieknooijens Can you add oath tokens to semaphore to provide this feature? If it's possible do it in such a way it doesn't rely on a user based token. Since that may cause this problem again if one leaves...

**Comment by nieknooijens** [comment]
![screenshot from 2017-09-01 08-50-00](https://user-images.githubusercontent.com/2794331/29958622-e6257e96-8ef3-11e7-995d-dffe757d06c2.png)
should be fixed now

**Comment by Baklap4** [comment]
@nieknooijens Hmmm alright so this is sadly linked to your account instead of the github repo. I bet there wasn't any other way to do it. If it comes in mind to leave the project please arrange this to be moved over to another (new) admin thankyou! Let's wait for someone to make a commit and see if it works. If it does we can close it ;)

**Comment by nieknooijens** [comment]
it was first linked to tobix's account, the only way to change it was to select "change repository" and select it using my OATH token.

**Comment by Baklap4** [comment]
yeah sadly (but that's not you to blame) since it's a repo specific imho but i guess github thinks otherwise. On gitlab one can create tokens/keys/secrets for a repo not linked to a specific user to make things like this work.

**Comment by Baklap4** [comment]
Closing this as seen in #283 it works again!
