### ISSUE TITLE
Webserver clean exit

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#241]
While at linux and make use of the terminal to start performous i might sometimes press `CTRL` + `C`.
This normally exits the game/application you're currently using from the terminal.

While doing this with Performous one gets the following printed to the console:
```
^CTerminating, please wait... (or kill the process)
Terminated.
webserver/error: Bad file descriptor
```
This does stop Performous, however it won't release the port where Performous' webserver did run on. This prevents an imediatly restart of Performous without having to wait for a minute or so.

Let's find/add a way to properly shutdown the webserver.

# Possibly related to #234 
- Fix for segfault on exit commited here: https://github.com/earlye/performous/commit/a83e82656664b46d48b987b31e40e99162db3d40

**Comment by nieknooijens** [comment]
well wasn't there a thread::join()? in the destructor of the webserver object?
then why doesn't it work correctly?

**Comment by earlye** [comment]
"well wasn't there a thread::join()? in the destructor of the webserver object?
then why doesn't it work correctly?"

The `m_server` and `m_serverThread` variables could be _null_, so calling `m_server->stop()` or `m_serverThread->join()` would segfault.
