### ISSUE TITLE
Remember song sort order or set a default order in the configuration

### ISSUE THREAD

**Issue by Stefan1200-de** [performous/performous#242]
### Actual behaviour

After starting Performous, the song selection is always in random order.

### Expected behaviour

Performous remembers the last selected sort order (title, artist, etc.) or allows the user to set a default sort order in the configuration.

### Details

Provide some additional information:
- performous version: 1.1
- operating system + version: Windows 10 & Linux Mint 18.1

**Comment by nieknooijens** [comment]
so basically we should store the sort order in the config, that shouldn't be too hard to fix

**Comment by Baklap4** [comment]
This will be picked up together with #246

**Comment by nieknooijens** [comment]
fixed in 389e8234
