### ISSUE TITLE
Performance while playing a duet is very bad

### ISSUE THREAD

**Issue by Stefan1200-de** [performous/performous#244]
### Actual behaviour

No matter which duett song I start, the performance / fps drops down and the speech frequency detection is weird. In most cases it is very hard to impossible to have the right pitch, because Performous shows my pitch at the top of the bar or at the bottom. Totally weird. I don't have this problems with normal songs, especially if I sing alone. This issue occur on two different systems:
Windows 10 + Intel i7 7700k + 16 GByte RAM
Linux Mint 18.1 + Intel Pentium N3700 + 8 GByte RAM
Both use Performous 1.1

Playing duett songs are currently impossible for me.

**Comment by basisbit** [comment]
can not confirm this on Intel Core i3-6100u running Windows 10 or Debian Jessie.

**Comment by Lord-Kamina** [comment]
I've played duets on a Pentium (don't know exact model) on 1.1, with no issues... D:

**Comment by Baklap4** [comment]
Can not confirm this aswell Intel Core i7-4700HQ @ 2.4 Ghz, 6 GB Ram, Ubuntu Xenial And Windows 10, Normal HDD. Using latest master and Performous 1.1.

**Comment by Baklap4** [comment]
@Stefan1200-de was there something going on in the background? And did you try to restart your pc? And have up to date drivers?

**Comment by Lord-Kamina** [comment]
Also, what are you using for sound input, and what values are your latencies and such set to?

**Comment by Stefan1200-de** [comment]
Drivers are up to date. I had this issues even after restarting the PC. I was just testing the software Vocaluxe, which don't have this issues with the same songs.

I use USB microphones (Monacor DM-500USB), which have a CMedia chip build in. Single player songs works without problems with Performous.

**Comment by Baklap4** [comment]
@Stefan1200-de can you show us some log files?

**Comment by Stefan1200-de** [comment]
@Baklap4 of course, where I can find them?

**Comment by Baklap4** [comment]
I can't quite remember the log save file location, should be somewhere on the system. Try running performous from the commandline by typing: `performous --log debug`

The infolog can be found here at linux: `~/.cache/performous` if i'm correct

**Comment by Stefan1200-de** [comment]
@Baklap4 Does the Windows version save the debug log too? Because my Linux machine has only an Intel Pentium Processor N3700, which is much slower as my Windows machine. I don't know if the N3700 should be fast enough for a duet song.

**Comment by nieknooijens** [comment]
@Stefan1200-de can you also try lowering the SVG render quality in the graphics options?

**Comment by Stefan1200-de** [comment]
@nieknooijens I set text and svg quality to 0.5, it seems that the performance issues are gone (or at least I can't see them anymore with my eyes). But I can't believe that my Windows 10 PC, which can handle all current games on Ultra settings, can't handle Performous with SVG Quality 1.5 and Text Quality 6.0. With text quality below 2.0 the small letters are hard to read (below 1.5 already impossible).

But the problem with the note matching while playing a duet song is still the same. This time I tried another duet song, which I never played with Performous before and compared it with Vocaluxe. In Vocaluxe I was able to match 3 times more notes as with Performous (both on easy mode). I know that this are two different programs, but that is a big difference. Especially while single player songs with Performous (which I do alone) are quite similar with Vocaluxe.

**Comment by Baklap4** [comment]
@Stefan1200-de you can open up a terminal (cmd.exe) in windows in the install dir of performous (C:/program files x86/performous) and run Performous.exe --log debug
It does save files on windows aswell

**Comment by Stefan1200-de** [comment]
@Baklap4 I did, but where is the file? I checked the Performous directory and %userprofile% (including %appdata% and the documents directory). I can't find any log file which seems to be related to Performous.

**Comment by Baklap4** [comment]
@Stefan1200-de the console shows the location as one of the first lines. You can also copy the lines spewed to the console :)

**Comment by Stefan1200-de** [comment]
@Baklap4 Unfortunately Performous shows nothing on the console on Windows, not even if I try Performous.exe --audiohelp or Performous.exe --help

**Comment by Lord-Kamina** [comment]
Just ran 1.1 on a win8.1 box; infolog.txt is in %appdata%\performous\cache.

**Comment by Stefan1200-de** [comment]
@Lord-Kamina Thanks, I found it.

Here is the debug log, my GFX settings: SVG 1.5x, Text 3.0x
With this settings the performance is okay and I can read all text messages.

[infolog.txt](https://github.com/performous/performous/files/1106368/infolog.txt)

**Comment by Baklap4** [comment]
I just got through your log, apart from having a lot of audio interfaces, i don't see anything unusual. Did the slowyness occur during loading of the songs? I Highly doubt it unless your hdd has some serious problems with read/write actions. I also saw we're reading quite a lot from the cache, but if your hdd is not the problem than that shouldn't be a problem....

**Comment by Stefan1200-de** [comment]
Well, I think the slowyness was because of text quality 6.0. After lowering the value to 3.0 it is much better (still not perfect, but playable). A lower value than 3.0 is not a good idea, because I can't read the small text anymore.

But I still have the feeling that Performous is less accurate at hitting the right note as while playing a single player song. It is just weird, but if I'm the only one, I don't know how to show the problem.

**Comment by Baklap4** [comment]
turning down the text quality deffo helps indeed. I myself play at 2.0 for each graphic setting. 

For as hitting the right note, the txt file itself could also contain wrong notedata, are you a 100% sure they have set every tone at every correct note?

**Comment by Lord-Kamina** [comment]
Perhaps play with the latencies a bit and you can get better results? Also,
I find it very odd you need text at 3.0x

**Comment by Stefan1200-de** [comment]
@Baklap4 Well, I found one duet song (which should be is easy to sing), which is also hard to hit the right note in Vocaluxe (but still easier than with Performous). I guess in that song the notes are wrong. But the other duet songs plays in Vocaluxe absolutely normal, but in Performous very hard (well, I tested not every song).

I was just surprised that in duet songs Performous sometimes shows my current pitch very weird (skipping from top to bottom, no matter how I pitch my voice). 

@Lord-Kamina Yeah, with text quality 1.5 it is impossible to read the title on the left bottom. If I go down with the text quality below 1.0 I can't even read the text at the top right, next to the time left progress bar. Two screenshots, one with text quality 1.5, one with 3.0.
![performous_textquality1 5](https://user-images.githubusercontent.com/15168351/27622360-eadbbc48-5bd6-11e7-9d48-62e3ee6d5b97.png)
![performous_textquality3 0](https://user-images.githubusercontent.com/15168351/27622361-eadf678a-5bd6-11e7-8f99-d7158d78bdb8.png)

**Comment by nieknooijens** [comment]
@Lord-Kamina my text quality is at 2 - 2.5
I already changed the default value from 0.5 to 2 a while ago when I ported  it to SDL2, the reason was that stuff just looked ugly on fullHD screens and since my previous 8-year old desktop was fine rendering it at higher quality settings, it was best to go with that.
but 3.0 is ridiculous! 2.0 should be sufficient on HD screens, there might be problems with 2.0 on a 1366x768 screen since you have less pixels to draw onto.

**Comment by Stefan1200-de** [comment]
@nieknooijens text quality 3.0 is ridiculous? I tested it, here is a screenshot from text quality 2.0 at full hd:
![performous_textquality2 0](https://user-images.githubusercontent.com/15168351/27624250-2872c48a-5be0-11e7-9630-66e8ef8ff119.png)

**Comment by basisbit** [comment]
can confirm this in the song playing screen with default settings:
![image](https://user-images.githubusercontent.com/10870269/27624322-7a2d239c-5be0-11e7-817b-13664b51e9ef.png)

**Comment by Baklap4** [comment]
For the text rendering issue please open up a new issue. I can confirm this on linux btw.
