### ISSUE TITLE
Audio Devices selection screen can be hard with many devices shown

### ISSUE THREAD

**Issue by Stefan1200-de** [performous/performous#245]
### Actual behaviour

If I use the audio device selection screen to select my microphones, I can't read the device names.  But the biggest problem is, that some devices are shown twice or three times. See attached screenshot.

To make this even more bad, while doing anything on this list, the performance is very bad. So it takes even on my Intel i7 7700k CPU up to two seconds until I can see that the selection chance after pressing an arrow key. But I also have this performance issue on my linux machine.

### Expected behaviour

Every device should be only shown once. Maybe hide also disconnected or disabled devices to clean up the list. Maybe using this methods to reduce the devices count, the performance while pressing an arrow key will also increase.

### Details

Provide some additional information:

- performous version: 1.1
- operating system + version:
Windows 10 x64
Linux Mint 18.1 x64

![performous_audiodevices](https://user-images.githubusercontent.com/15168351/27544449-7653c59a-5a8d-11e7-8a71-89ea19aa8837.png)

**Comment by Baklap4** [comment]
The thing where it shows multiple of the same audio devices is discussed here:
Possibly related to #160 

Your performance issue however, i myself do not have encountered framedrops or latency issues ubuntu xenial here. Performance issue possibly related to #244

**Comment by Baklap4** [comment]
Closed in favor of issues #160 regarding multiple audio devices.
Closed as result from #244 since text-quality was set to 6.0. Within the config menu it's dully noted that higher values comes with drop in performance see https://github.com/performous/performous/blob/master/lang/performous.pot#L960-L968
