### ISSUE TITLE
Git submodule performous/performous-mxe

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#253]
Within the win32 folder of performous/performous we have an mxe folder with some files to make mxe and build performous for windows on linux/macos. This is all great, however these files shouldn't be maintained here but within the performous/mxe repo. With Git Submoduling we can easily use the performous/performous-mxe repo and have all mxe related stuff there.

Any objections? @performous/contributors

**Comment by basisbit** [comment]
sounds good to me. I am currently working on getting most of the dependencies integrated as submodules, so once that is working, building performous should be a bit closer to just git clone + get submodules + make-install. Hopefully, this will also allow directly compiling + linking on windows, too.

**Comment by Baklap4** [comment]
I'll pick this up tonight ;)

**Comment by Baklap4** [comment]
Fixes commited as per:
* https://github.com/performous/performous-mxe/issues/1
* https://github.com/performous/performous/issues/257

**Comment by TobiX** [comment]
Slightly -1 from me, since submodules are hard to grasp and get to work correctly for people new to git. What is the harm in keeping the repositories separate?

**Comment by basisbit** [comment]
what is so difficult about `git submodule init` and `git submodule update`? Maybe it would be a good idea to add it to the readme.md, so that software developers without knowledge of git basics easily can build stuff.

**Comment by Baklap4** [comment]
scratch init and update, just use `git clone --recursive git://github.com/performous/performous.git`
Where --recursive grabs all the submodules. Git 1.6.5 or higher. (Current git is 2.13.2 )

**Comment by Baklap4** [comment]
closing this since pr is closed (not merged)
