### ISSUE TITLE
Skip instrumental message will be displayed wrong in duet songs

### ISSUE THREAD

**Issue by Stefan1200-de** [performous/performous#254]
### Actual behaviour

If you play a duet song and the second singer is singing, but the lead singer has nothing to sing currently, the "skip instrumental" message will be displayed in the top right.

### Expected behaviour

As long as one of the two singers have a text to sing, don't show this "skip instrumental" message.

### Details

Provide some additional information:

- performous version: 1.1
- operating system + version: Windows 10 x64

**Comment by Baklap4** [comment]
He's talking about `skip instrumental break` function. I've noticed it too on current master.

**Comment by Stefan1200-de** [comment]
@Baklap4 Thanks, I updated my text, because I only knew the German term used by Performous.

**Comment by nieknooijens** [comment]
I guess this has low priority, it's not really that big of a deal, but at the same time, it's probably adding just one if-statement.

**Comment by Stefan1200-de** [comment]
@nieknooijens Yeah, it is not a big thing. I just realized this while doing some tests for another issue. So I wrote it down here to make sure that it will not forgotten. ;)

**Comment by Lord-Kamina** [comment]
This issue is actually bigger than it would appear at first.

Quoting myself on Discord:

> [11:58 PM] Lord Kamina: It's not quite as simple as it seems.
> December 4, 2017
> [12:18 AM] Lord Kamina: And the bug if a bit bigger than just what's described in the issue.
> [12:26 AM] Lord Kamina: tl;dr we haven't implemented any way to check whether a song actually has a duet.
> [12:26 AM] Lord Kamina: What I mean by this is, we can know if a song has a duet from its textfile.
> [12:27 AM] Lord Kamina: But performous thinks we have a duet even if we're playing in normal mode, or if both players are singing the same vocal track.(edited)
> [12:34 AM] Lord Kamina: I think we need to implement a proper check for whether we are actually playing with a duet in screen_sing, and that should be passed as a parameter to Song::status
> [12:35 AM] Lord Kamina: Ideally the function in screen_sing should check for: 
> a) Whether the TXT has a duet.
> b) Number of players
> c) Whether duet mode is actually on
> d) Whether both players are actually singing different voices.

Please take a look at https://github.com/performous/performous/tree/issue/fix_skip_instrumental for what I've done so far; It'd be nice if someone can help also.

**Comment by nieknooijens** [comment]
@Lord-Kamina please make a pull request with [WIP] in the title, then I can see the diff with master, which makes it easier to review and find what has been changed.
