### ISSUE TITLE
config.xml integer values with thousands separator cause crash on load

### ISSUE THREAD

**Issue by basisbit** [performous/performous#256]
### Actual behaviour

Start the game, see a fatal error messagebox appear stating `"[...]\config.xml:11 Error while reading entry: bad lexical cast: source type value could not be interpreted as target More details might be available in [path to performous\caching\infolog.txt]"`.

![image](https://user-images.githubusercontent.com/10870269/27603310-0ec40eb4-5b76-11e7-902d-3a95937d6955.png)

Game can be played again after modifying the line `<entry name="graphic/window_width" type="int" value="1.235"/>` and removing the thousands separator.

### Expected behaviour

Start the game and be able to play even after saving the settings in-game and later restarting it.
Settings should be saved without thousands separator. When reading values and an int is expected, any . or , should be removed from the string to support updating from old performous installs or the user doing manual changes.

### Steps to reproduce

1. Fresh install of current Performous
2. Start the game, modify + save settings in game
3. Close the game
4. Start the game, see a fatal error messagebox appear stating `"[...]\config.xml:11 Error while reading entry: bad lexical cast: source type value could not be interpreted as target More details might be available in [path to performous\caching\infolog.txt]"`.
5. After clicking OK, the game closes and you can not play.

### Details

Provide some additional information:

- performous version: current master, roughly 590fe62
- operating system + version: Windows 10 x64 with all current updates as of today
- typical German localisation settings: numbers format like 1.234,56 or 1234,56
- confirmed by @Baklap4 on linux

**Comment by nieknooijens** [comment]
why would you ever want to do that? and INT is an "integer" (whole number).
I think there already is an old issue proposing to add float/doubles to the config.

**Comment by basisbit** [comment]
@nieknooijens please read again. This issue is not invalid. @Baklap4 confirmed this problem on linux.

**Comment by basisbit** [comment]
I know we do not support half pixels. that would be nonsense. The problem is that performous stores the pixels number with thousands-separator and then is not able to pare that at next start.

**Comment by basisbit** [comment]
thanks a lot for fixing this!
