### ISSUE TITLE
No text output on Windows cmd / Powershell console from Performous.exe (stdout)

### ISSUE THREAD

**Issue by Stefan1200-de** [performous/performous#258]
### Actual behaviour

Unfortunately Performous shows nothing on the console on Windows (stdout), not even if I try **Performous.exe --audiohelp** or **Performous.exe --help**

But I know that commands like **--log debug** works, you just don't see the log file location (you have to know/find it on your own).

### Expected behaviour

Working text output to stdout.

### Details

Provide some additional information:

- performous version: 1.1
- operating system + version: Windows 10 x64

**Comment by nieknooijens** [comment]
is this in CMD or powershell?
if using powershell maybe you can pipe stdout to a file?

**Comment by Stefan1200-de** [comment]
@nieknooijens I tried both, cmd and powershell. Same issue.

Yes, piping to file helps at least for Performous --help / --audiohelp, example:
***Performous.exe --help > test.txt***
test.txt:
```
Generic options:
  -h [ --help ]          you are viewing it
  -l [ --log ] arg       subsystem name or minimum level to log
  -v [ --version ]       display version number
  --songlist arg         save a list of songs in the specified folder

Configuration options:
  --audio arg            specify an audio device to use
  --audiohelp            print audio related information
  --jstest               utility to get joystick button mappings
  any arguments without a switch are interpreted as song folders.
```

But someone mentioned, that ***--log debug*** should write the log file path to stdout, this does not even work with piping to file.

**Comment by nieknooijens** [comment]
ok that's at least some progress limiting everything to the logger which uses a boost::sink to push stuff to stdout. are there any windows specific settings which we forgot?

**Comment by Lord-Kamina** [comment]
In windows, besides the logger you can do 1> log.txt 2>& 1 to pipe both STDOUT and STDERR to a file.

**Comment by Baklap4** [comment]
Fairly recent i built a native build of windows in which this issue was resolved. There's no release for it yet though.

**Comment by Baklap4** [comment]
I think this came from crosscompiling from linux to windows as most exe's were made this way.  Building + compiling on windows gave me loads of output. PR: #650 let's hope it gets merged soon!

**Comment by Baklap4** [comment]
@Stefan1200-de This is fixed within latest master after you've made a native windows build. Like i said before it was an issue with crosscompiling. A new release will soon come. Join the conversation here: https://github.com/performous/performous/discussions/665
