### ISSUE TITLE
Website giving certificate errors in Chrome

### ISSUE THREAD

**Issue by backache** [performous/performous#267]
**Please, do not create duplicate issues**

### Actual behaviour

Website giving certificate errors in Chrome

### Expected behaviour

Website loads without error

### Steps to reproduce

Goto https://performous.org/ using Chrome in Windows

![performous](https://user-images.githubusercontent.com/6274724/28081529-7c1bac00-6667-11e7-8b57-ab48559c2536.PNG)

### Details

Provide some additional information:

- performous version:
- Windows 7, Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by Baklap4** [comment]
Closing in favor of https://github.com/performous/web/issues/4
We are aware of the hsts error. Please view the mirror site: https://performous.asgardsings.nl
