### ISSUE TITLE
Songs finished loading dialog causes a SIGSEGV crash.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#271]
### Actual behaviour

Performous crashes.

### Expected behaviour

Should show a message notifying all songs have been loaded.

### Steps to reproduce

Load Performous, wait.

### Details

Just something I noticed peripherally while working on my audio fixes (was following compiler warnings to see whether I could get rid of any) and I noticed an "unused variable" warning leading to songs.cc where a pointer to the Game singleton was being defined but not used. Immediately below was the line that would use it (commented out) saying it crashed ubuntu 16.10 but not 16.04.

I uncommented it to test and noticed it crashes on mac also. Following it around a bit, it appears the bug is here (surface.hh):

	OpenGLTexture(): m_id() { glGenTextures(1, &m_id); }

And googling for similar errors, I found this which seems to be an identical error (and we can probably derive the solution from it): https://stackoverflow.com/questions/8982472/sigsegv-error-while-using-c-on-linux-with-opengl-and-sdl

**Comment by Baklap4** [comment]
Still crashes on ubuntu 17.10
