### ISSUE TITLE
Performous Installation

### ISSUE THREAD

**Issue by diver66** [performous/performous#282]
I just installed performous on my lubuntu machine. It works great and I have to say although i have about 5500 songs, it is amazingly fast. I have just a few issues

how can I turn off the music in ther background ?
how can I incoorporate the image of the editions/languages i have ?
How can I change the font that is show in the menu and also as the song text ?

I have installed performous using the howto of the wiki. -> Building-and-installing-from-source#Downloading_and_installing_the_sources

Now I see that there is the possibility to install the nightly builds just by doing -> sudo add-apt-repository ppa:performous-team/daily && sudo apt-get update && sudo apt-get install performous

Can I use this command to change my installation to fetch the nighly builds or will it boggle up my performous install ? Whats the best way to get this running ?

**Comment by Baklap4** [comment]
To turn of the music in the background i think you mean canceling out the vocals?
For this you can enable center channel mute by pressing `ctrl + c`

> How can i incoorporate the image of the editions/languages i have?
What do you mean with this? You can get a list sorted by edition/languages within the browser by sorting on either one of them.

> How can i change the font that is shown in the menu and also as the songtext
For customization on themes one can create a new theme as mentioned on the wiki: https://github.com/performous/performous/wiki/Theming

> Can I use this command to change my installation to fetch the nighly builds or will it boggle up my performous install ?
Yes you can use this command to fetch the nightly builds and update it with just `apt-get update && apt-get upgrade`. Before this make sure performous is deinstalled (on unix systems remove `/usr/local/share/games/performous/` 

> What's the best way to get this running
If you did add the nightly builds, just run `apt-get update` and `apt-get upgrade` for installing a newer version. However a nightly build can be broken therefore only do this if you can risk it being unstable.

Extra's:
With #280 the webserver UI is even faster. But this isn't within master yet.

For more questions feel free to use our discord user-support channel: https://discord.gg/NS3m3ad
If you think you found a bug feel free to open up another issue.

**Comment by nieknooijens** [comment]
> how can I turn off the music in ther background ?
in addition to the center channel surpressor, there are 2 volume controls (ctrl+ up / ctrl + down), one for the menu, and one for the gameplay. so you can turn down the music volume in the menu as you like.

> how can I incoorporate the image of the editions/languages i have ?
this is pretty unclear to me. usually you place images next to the MP3 and the TXT file and within the text file you specify which image to use (if you don't specify it performous will guess what to use which could give weird results).
for example in your .txt you can place:
`#BACKGROUND:myfile.png`
