### ISSUE TITLE
Show better text when IP can't be resolved

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#286]
Cleanup of #226 
As mentioned in https://github.com/performous/performous/issues/226#issuecomment-280604558

If trying to get an ip address failed one would get the message: `cannot obtain IP`
A fallback for this would be to use the hostname of the machine: `hostname:portnumber`
If no hostname is set one can show the message: `localhost:portnumber`
~~If no devices are up one can show the message: `No devices up`~~ Scratched because of @nieknooijens comment

**Comment by nieknooijens** [comment]
if no devices are up, localhost still works so no devices up is unnecessary
