### ISSUE TITLE
Web interface: search broken if special characters on title or artist name 

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#290]
Pretty self-explanatory. Can't add songs to  playlist via searching if they have unicode characters in artist or title.

Shouldn't be too hard to fix, considering it works fine if you select them with the "+" from the "All database" tab.

**Comment by Baklap4** [comment]
@Lord-Kamina Hmm to be more exact this is the autocomplete function if i'm correct? If you search, click the search button and then click the song in the list it does work if i'm correct?

**Comment by Lord-Kamina** [comment]
@Baklap4 You're correct. My mistake was in part conditioned by something that I just noticed is UI-related. On a phone, the "Search" button appears unstyled and so I didn't actually see it, or it automatically "registered" as plain text in my brain so I never used it, was just trying to use auto-complete the whole time.

**Comment by Baklap4** [comment]
Closed as it's now a duplicate of #293
