### ISSUE TITLE
Lubuntu 17.10 - sudo apt-get install performous - unmet dependencies

### ISSUE THREAD

**Issue by diver66** [performous/performous#303]
Hi,

the installation under Lubuntu 17.10 fails.
sudo apt-get install performous

I get the message 

The following packages have unmet dependencies
depends libopencv-core2.4v5 but it is not installable
depends libopencv-highgui2.4-deb0 but it is not installable
unable to correct problems, you have held broken packages

How can I solve this, it was working fine under 16.10. I actually wiped my HD and installed a clean Lubuntu 17.10

**Comment by diver66** [comment]
I still cannot install performous, any ideas how I can solve this problem ?

**Comment by nieknooijens** [comment]
you could use our old ppa, or build it form source. (https://github.com/performous/performous/wiki/Building-and-installing-from-source) be aware though that cpp-netlib is no longer in the repositories of 17.10.  currently the workaround is to either build without webserver-support (use cmake-gui for that) or install the previous version from here:
https://packages.ubuntu.com/xenial/libdevel/libcppnetlib-dev
https://packages.ubuntu.com/xenial/libcppnetlib0

**Comment by Baklap4** [comment]
Or install it as mentioned in our docs:
>Note: when building the webserver-branch you need CPP-netlib get the 0.11.2 version from:http://downloads.cpp-netlib.org/0.11.2/cpp-netlib-0.11.2-final.tar.gz and unpack the folder named "boost" into /usr/include. if done correctly you should have the file: /usr/include/boost/network/protocol/http/server.hpp among some others.

**Comment by diver66** [comment]
@Baklap4  done that thanks, I feel a bit stupid asking this but : i tried to install 
sudo apt-get install libcppnetlib0
sudo apt-get install libcppnetlib-dev 

but i always get a unable to locate package error - any hints on how to solve this ?

**Comment by Baklap4** [comment]
@diver66 since ubuntu 17.10 (which lubuntu derives from) cppnetlib is not in the repo's anymore. Therefore you have to either build it yourself (or download the tarball) and manually install it (like you did). 

To solve any apt-get issues, first run `sudo apt-get update` and then run `sudo apt-get install -f` afterwards run `sudo apt-get upgrade` and `sudo apt-get autoremove` this will leave you with a cleaned up system and fixes broken dependencies. It also updates your packages to the current latest packages.
> apt-get install -f
>-f, --fix-broken
       Fix; attempt to correct a system with broken dependencies in place. This
       option, when used with install/remove, can omit any packages to permit APT
       to deduce a likely solution. If packages are specified, these have to
       completely correct the problem. The option is sometimes necessary when
       running APT for the first time; APT itself does not allow broken package
       dependencies to exist on a system. It is possible that a system's dependency
       structure can be so corrupt as to require manual intervention (which usually
       means using dselect(1) or dpkg --remove to eliminate some of the offending
       packages). Use of this option together with -m may produce an error in some
       situations. Configuration Item: APT::Get::Fix-Broken.

With this handled can we close this issue @diver66 ?

**Comment by diver66** [comment]
thank you

**Comment by Baklap4** [comment]
maybe to be mentioned here and in #319 the ppa of the daily builds are running up till Ubuntu Xenial (16.04) as the docs say.

> We currently support Trusty (14.04), Vivid (15.04), Wily (15.10) and Xenial (16.04).
