### ISSUE TITLE
Drop glib2 as we use ICU now.

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#315]
As mentioned on discord `glib2` can probably be dropped since we're using ICU now:

> Lord Kamina - Today at 8:02 PM
@Asgard Sings! while I was looking at fixing your BOM comment
I realized we're using glib2 for a number of things.
We can probably replace glib2 entirely with ICU
http://site.icu-project.org/charts/collation-icu4c-glibc this is some old data but it also appears for most things, ICU is a lot faster than glib
Collation: ICU4C 3.8 vs. glibc-2.12.3-2 - ICU - International Components for Unicode
ICU Project Site

**Comment by Lord-Kamina** [comment]
As I commented on #325, I realized we cannot actually drop Glib2 entirely because several of the libraries we use depend on it in one way or another.

**Comment by nieknooijens** [comment]
so this is considered a future improvement?

**Comment by Lord-Kamina** [comment]
@nieknooijens Not really, I don't think so unless we're really planning to rewrite performous from the ground-up at some point. :P

**Comment by Baklap4** [comment]
Closing this since #325 is closed
