### ISSUE TITLE
Lubuntu 17.10 - Update Question

### ISSUE THREAD

**Issue by diver66** [performous/performous#319]
Hi guys,

I have performous running on my Lubuntu system, I overcame the problem with the missing libs and installed them by hand (Thanks for the help) and built and installed it from source. Now everything is working fine. There is one thing I would like to ask :

I ran the following command to stay up to date - sudo add-apt-repository ppa:performous-team/daily

Even though I have the missing libs installed - running the following command still throws the old error message (unmet dependencies - libopencv-core2.4v5 and libopencv-highgui2.4-deb0 not installable)

sudo apt-get update && sudo apt-get install performous

Any ideas how I can serve this little error ? How can I stay update with the latest version ?

**Comment by Baklap4** [comment]
Heyo @diver66 can you run `sudo apt-get install -f` this will install the unmet dependencies if im correct.

**Comment by diver66** [comment]
no basklap4 that does not work, i get the same error message

**Comment by Baklap4** [comment]
Which lubuntu version are you using?

**Comment by diver66** [comment]
Lubuntu 17.10

**Comment by Baklap4** [comment]
Ahh as mentioned on the docs:

> We currently support Trusty (14.04), Vivid (15.04), Wily (15.10) and Xenial (16.04).

The packages for opencv to be installed is `sudo apt-get install libopencv-core-dev`. This should get you the latest opencv libraries.

You said earlier you built from source. If you want to get the latest and greatest on Lubuntu 17.10 i'd advice you to run the following commands:

# If you haven't build from source earlier
`sudo apt-get update && sudo apt-get install`
This will update your system libraries
`git clone git@github.com:performous/performous.git`
This will clone the repository to the current folder with the name `performous`
`cd performous && mkdir build && cd build`
Change to the performous repository directory. Create build folder. and move into it.
`cmake ..`
Configure cmake.
`make -j2`
Build the application using 2 cores.
`sudo make install`
Install the application.

This should install the master branch. Be careful though, master can sometimes be broken, we try to keep it stable.

# If you want to update an earlier cloned repo do the following
`sudo apt-get update && sudo apt-get install`
This will update your system libraries
`cd performous && rm -rf build && mkdir build && cd build`
Change to the performous repository directory. Remove the build folder. Recreate it. and move into it.
`git pull`
To update source files from remote (github)
`cmake ..`
Configure cmake.
`make -j2`
Build the application using 2 cores.
`sudo make install`
Install the application.

**Comment by diver66** [comment]
great i try this now - and report back

**Comment by diver66** [comment]
well, i updated my cloned repo and it work without a flaw, thanks thanks thanks

**Comment by Baklap4** [comment]
Then i'm going to close this now ;)! Glad it works!
