### ISSUE TITLE
Expose webserver running status

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#320]
With the latest branch https://github.com/performous/performous/tree/feature/PortInUseFix
We helped performous not to crash and ignore the webserver if the port is not free.
The text is a different matter as it still shows `Webserver active on 0.0.0.0:8080` 

We need some way to expose the running state of the webserver to be able to switch the message to for example: "Trying to start up webserver" and when it failed: "Failed to start webserver".

**Comment by nieknooijens** [comment]
we can recycle the message "webserver active! please connect to <ip address>:8000" 
just put over there "cannot start webserver".

**Comment by Tronic** [comment]
What's up with this? Also related to #334.

**Comment by Baklap4** [comment]
If for some reason the webserver failed to start, we should display it on screen. Can be implemented together with #334 indeed to clean shit up
