### ISSUE TITLE
Incorrect FSF postal address in the source files

### ISSUE THREAD

**Issue by abompard** [performous/performous#328]
Hello! This is a non-technical issue, but very easy to fix and guaranteed without regressions.
The postal address for the FSF is incorrect in the following files:

 * tools/gh_fsb/fsbext.c
 * tools/gh_fsb/mywav.h
 * tools/gh_fsb/show_dump.h

Please paste the correct one from the main Performous license. Thanks !

**Comment by Baklap4** [comment]
Regarding to these files, there are still some warnings in fsbext if i'm correct. Maybe fix them up? Are there newer version of these?

**Comment by Tronic** [comment]
I'd rather remove all licensing text from source code and add the corresponding notes to docs/Authors.txt (it seems to be missing now). However, the tools should probably be removed from Performous and archived as a separate project as they are seldom used nor maintained by anyone anymore (which is another issue).

For now, I have simply updated the license text, closing this issue.

**Comment by Baklap4** [comment]
@Tronic i'd like to inform to keep using branches and rebase/merge them back into master.
This way other's have to overlook the code and after review it may be merged to master. This increases code quality in general.
