### ISSUE TITLE
Tools should be moved to a separate module

### ISSUE THREAD

**Issue by Tronic** [performous/performous#330]
The Singstar/GH extraction tools have lived a long life within the main Performous project. They are built alongside with the game and are often also installed even though only the game itself is wanted. Since there is nowadays very little need for rippers, no-one has maintained the tools and they keep spewing compiler warnings.

I suggest removing the tools folder from Performous and giving them a new (archived) life as a separate project that only contains these ripping tools.

Comments?

**Comment by nieknooijens** [comment]
no comments, I completely agree.

and @Tronic welcome back :wave:

**Comment by Baklap4** [comment]
Agreed!
Create a repo, dump the code over there.

**Comment by Baklap4** [comment]
@Tronic aside from the ripping tools, there was a tool for po-edit aswell to sync up the translations. I suggest we add that one back in here?

**Comment by Tronic** [comment]
Sounds reasonable. I never noticed that tool, but if it doesn't need to build and doesn't install anything on `make install` it doesn't really do harm either.

**Comment by Baklap4** [comment]
Aight, that makes the current readme within lang/readme 'working' again
Still no way for windows to sync up with code though as the script is bash only.

**Comment by Tronic** [comment]
🤔·.o(( To rewrite in Python or not? ))

**Comment by Baklap4** [comment]
I don't have the python skills to do so, could take a look of course..

**Comment by Tronic** [comment]
@Baklab4 this should do it? https://paste.zi.fi/p/xml_gettext.py/view

**Comment by Tronic** [comment]
Test if it works, fix if necessary and then commit as your own 🙂

**Comment by Baklap4** [comment]
Seems it can't find xml as a module...
![image](https://user-images.githubusercontent.com/3918517/77229526-d453a100-6b8e-11ea-8649-2c3feacfcf4a.png)
Running with python 3.7.7 on windows

**Comment by Tronic** [comment]
This module is part of standard library, and works for me on Windows too (both Anaconda Python 3.7.4 and standard Python installer 3.8.2). Quite odd if it doesn't work, unless you are running some minimalistic Python modification. Btw, I've cleaned up the script on pastebin a bit, so take a fresh copy if you got the earlier one.

**Comment by Baklap4** [comment]
Hmm with the latest 3.8.2 using the default python installer on windows it's still not working hmm weird...

**Comment by Baklap4** [comment]
Alright we're getting somewhere: 
![image](https://user-images.githubusercontent.com/3918517/77230844-7a0b0e00-6b97-11ea-9b97-45ba5b003918.png)

**Comment by Tronic** [comment]
I'm wondering if poedit sandboxes the script so that it cannot load that module, or at least cannot find Python installation path. Can you try running stand-alone?

**Comment by Tronic** [comment]
Looks like the first argument to the script is not the XML file (like I assumed without really reading the bash script). Change `sys.argv[1]` to something else?

**Comment by Tronic** [comment]
Is the `msquniq` command available on Windows, or should that part also be done by the script? I can easily modify the script to call that and feed data to its stdin.

**Comment by Tronic** [comment]
I've changed the script so that it should do the right thing, including removal of duplicates so that it doesn't require any external tools.

https://paste.zi.fi/p/xml_gettext.py/view updated.

**Comment by Baklap4** [comment]
Let's see the script is added like this as mentioned on the readme within the lang folder
![image](https://user-images.githubusercontent.com/3918517/77233682-62d51c00-6ba9-11ea-93bb-73cd728b577c.png)

Command to extract translations: `‪"C:\Users\aspeiard\AppData\Local\Programs\Python\Python38\python.exe" "C:\Users\aspeiard\Desktop\Persoonlijk\performous-master\tools\scripts\xml_gettext.py" %o %F`

**Comment by Baklap4** [comment]
Currently getting these errors from poedit:
```
22/03/2020 01:01:02: C:\Program Files (x86)\Poedit\GettextTools\bin\msgcat.exe: input file 'C:\Users\aspeiard\AppData\Local\Temp\poe3E51.tmp\legacy_Performous_XML_extracted.pot' doesn't contain a header entry with a charset specification
22/03/2020 01:01:02: Failed command: msgcat --force-po -o "C:\Users\aspeiard\AppData\Local\Temp\poe3E51.tmp\concatenated.pot"  "C:\Users\aspeiard\AppData\Local\Temp\poe3E51.tmp\legacy_Performous_XML_extracted.pot" "C:\Users\aspeiard\AppData\Local\Temp\poe3E51.tmp\gettext.pot"
22/03/2020 01:01:02: Failed to merge gettext catalogues.
22/03/2020 01:01:02: Entries in the catalogue are probably incorrect.
22/03/2020 01:01:02: Updating the catalogue failed. Click on 'Details >>' for details.
```

**Comment by Tronic** [comment]
Moving this over to #510
