### ISSUE TITLE
Can't build on Mac

### ISSUE THREAD

**Issue by x00xer** [performous/performous#34]
I've tried to follow your instruction to build it under Mac OS X 10.8 ML.

I would say it is very hard task :) All dependency was installed via brew. 
Not all of them cmake can find out, during configuration package. There is some problem with magick++, but that problem coming form brew bug. Most important problem is coming on compile stage: 

/usr/local/include/boost/variant/detail/move.hpp:141:35: error: no member named 'move' in namespace 'boost::detail::variant'; did you mean 'move'?
    rhs = boost::detail::variant::move(tmp);

Simialr erros are a lot on that stage.
Seems it is problem coming from compile flags, could you please advise me where and how (and which one) should I use?

Seems that flags can solve it http://stackoverflow.com/questions/13445742/apple-and-shared-ptr

**Comment by TobiX** [comment]
Isn't this fixed? We have a 1.0 Mac build and the 1.1 Mac build should be even easier...

**Comment by Lord-Kamina** [comment]
Indeed it's fixed. Additionally, I'm updating all my ports and stuff to try
building again with Clang.

On Saturday, April 4, 2015, Tobias Gruetzmacher <notifications@github.com>
wrote:

> Isn't this fixed? We have a 1.0 Mac build and the 1.1 Mac build should be
> even easier...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/34#issuecomment-89681454>
> .
>


-- 

-- 
  Gregorio Litenstein Goldzweig [image: glit_qr.png]  Interno de
Medicina  Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com
