### ISSUE TITLE
Bug/Feature Songs getting removed while trying to play.

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#351]
As mentioned on Discord i've encountered an issue with some songs i've played last event. The message telling me: `Notes must have positive durations.`

This was added in commit: https://github.com/performous/performous/commit/eb0c4ed0fe884a1df058f52a2455426c18515827#diff-a74329148b8018fe77d1730d9c5cfe4f

![image](https://user-images.githubusercontent.com/3918517/38196905-c6d9cb34-3685-11e8-83be-b1b469d6744a.png)

Personally yes notes should have a positive duration, however some textfiles have `0` in their text files which used to work before this commit.

I think this check should be `if (length >= 0) { then keep executing } else throw error('notes should've positve duration')`

How is this currently done in usdx @basisbit ?

**Comment by basisbit** [comment]
Usdx just ignores notes of 0 length and continues. I'd suggest implementing
very fault tolerant behaviour to keep people happy :)

Arjan Spieard <notifications@github.com> schrieb am Mo., 2. Apr. 2018,
06:01:
