### ISSUE TITLE
Sometimes menu music plays instead of a song

### ISSUE THREAD

**Issue by Tronic** [performous/performous#356]
Trying to play Defy the Machine, about 50 % of times when I start the song, clock stays at zero and main theme music plays instead of the actual song. Exit and try again, then it works normally. Try again and it fails again.

**Comment by Baklap4** [comment]
I haven't encountered this yet

**Comment by Tronic** [comment]
Quite possibly related: sometimes menu music doesn't play in menu. Enter some other screen (e.g. practice) and come back, then it plays. (with garbled audio at the beginning?)

**Comment by Tronic** [comment]
Fixed in pull request #359.
