### ISSUE TITLE
Testers with 4k 3D TVs and other devices needed

### ISSUE THREAD

**Issue by Tronic** [performous/performous#366]
There's now support for interlaced and checkerboard stereo 3d modes in issue #365. This needs testing with as many different devices as possible, so please do and give feedback if you have any.

**Comment by Lord-Kamina** [comment]
We might still find somebody but I think 4k 3d tvs are not being produced anymore?

**Comment by Baklap4** [comment]
Closing this due to the fact there is a pull request for this. Feedback can be given to #365
