### ISSUE TITLE
Ok seriously... we need to drop cpp-netlib.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#369]
I opened another issue because I think we need to retake this discussion and the best way to do it is starting fresh.

cpp-netlib is a fucking mess; 0.11.2 won't compile at all on boost >= 1.66; and the tests won't build on 1.65 either due to some issue with the Boost Testing framework. I can get it to build if I don't run tests but that's hardly ideal.
cpp-netlib 0.12 changed to standalone Asio instead of Boost.Asio, then 0.13 (currently in rc1 since god knows when) changed back to Boost.Asio.
 
The cpp-netlib 0.13 source tarball refuses to build (cmake errors) because they included dependencies like Google Test framework but didn't put them in the tarball (you're supposed to git clone and download submodules)... not to mention the project is as good as abandoned.

I was considering taking on upgrading performous to 0.13 but frankly it'd be backing ourselves deeper into a corner. We need alternatives. Boost.Asio is too low-level, sure. Perhaps Boost.Beast? It's still a lower-level than cpp-netlib but it's build on top of Boost.Asio and is under active development.

Other options? Would maybe something like mongoose work?

Suggestions/opinions please?

**Comment by Lord-Kamina** [comment]
What about this? 
https://stiffstream.com/en/docs/restinio/0.4/whatis.html

**Comment by Lord-Kamina** [comment]
This could also be a good alternative?
https://github.com/microsoft/cpprestsdk

**Comment by nieknooijens** [comment]
it's probably easier than that.
the nice part about cpp-netlib is that you create a server, which points to a function which tells what to do when a request comes in.
the only parts that are used from cpp-netlib are the request/response objects and the "stock responses"
this can easily be implemented using standard socket logic. eliminating cpp-netlib and boost entirely.

**Comment by Lord-Kamina** [comment]
Perhaps, did you check out Restinio though? It looks beautifully simple, plus it (and most of its dependencies) are header-only.

**Comment by nieknooijens** [comment]
yeah it looks almost the same as cpp-netlib, should be an easy port!

**Comment by Lord-Kamina** [comment]
I'm more partial to RESTinio, even though it's not in most repos because a) cpprestsdk is apparent quite slow and buggy. And b) RESTinio and almost all its deps are header-only so we could even bundle them into performous if so desired. Plus, the API is very nice.

**Comment by Lord-Kamina** [comment]
Originally I was looking into it because also of the json support but it's
pretty slow and not very standards-compliant. I'd rather switch to
rapidjson (which is also header-only)

I don't know... I really like RESTinio, it's a modern and compact project
made from.the ground up with modern c++ in mind.

I was working also on porting to rapidjson (and from there to RESTinio),
it's just I've been procrastinating lately.


From: Arjan Spieard <notifications@github.com> <notifications@github.com>
Reply: performous/performous
<reply@reply.github.com>
<reply@reply.github.com>
Date: May 29, 2018 at 17:25:43
To: performous/performous <performous@noreply.github.com>
<performous@noreply.github.com>
CC: Gregorio Litenstein <g.litenstein@gmail.com> <g.litenstein@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [performous/performous] Ok seriously... we need to drop
cpp-netlib. (#369)

@Lord-Kamina <https://github.com/Lord-Kamina> @nieknooijens
