### ISSUE TITLE
RetroArch / libretro core?

### ISSUE THREAD

**Issue by kstadler** [performous/performous#374]
Hello,

how about implementing a RetroArch/libretro core for Performous?
I think this would be a great addition to RetroArch, especially since libretro doesn't support PS2 Emulation yet.
Please see https://www.libretro.com/index.php/develop/ for technical details.

Best regards
Klaus

**Comment by nieknooijens** [comment]
I don't really get what you want here. libretro is mainly for emulation, while we are just a singstar clone.
I think building a libretro module for PCSX2 would fit your use-case better IMHO.

**Comment by kstadler** [comment]
The same could be said for MrBoom, which is a clone of Bomberman and available as a libretro core.
After Setup, Performous would even allow to use data from original SingStar discs, which makes it kind of a SingStar Emulator (even though it doesn't try to do everything the same way).
I don't know technical details about PCSX2, but I think I read somewhere that it isn't part of libretro because of platform dependent code. So this probably won't happen anytime soon.
Making Performous available as a libretro core could potentially also boost it's popularity.

**Comment by Baklap4** [comment]
What is the status on this? Are we (@performous/contributors) going to implement this yes or no?
If Yes please reopen this issue again.

Currently closed due to inactiveness.

**Comment by pasnox** [comment]
would it make more sense now? I would really love to have it for retro arch, retro arch is our family gaming box

**Comment by ooshlablu** [comment]
As a user of Retroarch and a contributor to Performous, I can say that "just making it a libretro core" is really not that straightforward, at least not as Performous is currently designed. There is also the other problem that the current contributors don't have any experience in working with libretro or making cores :-)
That being said though, I don't think any of us would stop an effort to make it a libretro core if someone was so inclined. If anyone is waiting for this to happen, I don't really see it happening any time soon with the way the current contribution group is composed. If anyone wants to try to make it happen, we accept and review PRs from anyone. Hit us up on Discord, and we are happy to offer advice or provide information in any way we can :-)
