### ISSUE TITLE
Removing songId from playlist crashes performous

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#376]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

* I made a playlist with 4 songs in it.
* I removed id `-5` from the playlist through our webserver by using curl
    * This resulted in a crash

### What did you expect to see?

I'd expect performous not to crash.
I'd expect performous to check the playlist size and if the given index is available before deletion.
I'd expect performous not to do anything in this case.

### What did you see instead?

Performous crashed with a segfault.

### Output of `performous --version`: (_What version of Performous are you using?_)

```
./performous --version
Performous 1.1-654-g06387fcf
```

### What is your environment & configuration (arguments, platform, ...)?

I'm running on Ubuntu 17.04

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

N/A

### Solution

Upon deletion from the playlist check if the given index is available.
If it's available you may delete it.
If it's not available you may not delete

**Comment by Baklap4** [comment]
In Addition to this, if you keep deleting songs and end up with an empty playlist and try to delete some more it'll result in a segfault aswell. But that's more for the webserver to be fixed.

Currently i'm completely rewriting the webserver due to #369 so this won't be happening anymore.

**Comment by nieknooijens** [comment]
so you remove negative numbers? we didn't know those existed :astonished:

**Comment by Baklap4** [comment]
Can't be done anymore by the webserver. Closing this since it also can't be done within the game itself.
