### ISSUE TITLE
Performous crashing with libepoxy 1.5.2 on macOS.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#383]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Run performous

### What did you expect to see?

It working

### What did you see instead?

A crash report

### Output of `performous --version`: (_What version of Performous are you using?_)

Latest master

So... something in 1.5.2 is causing Performous to die. I've opened a ticket upstream to see whether they can help but I figure it'd be good to keep track of it here also.

P.S. Can you people try 1.5.2 in your respective platforms to see whether it's specific to macOS or not?

**Comment by Baklap4** [comment]
Maybe related to #371

**Comment by Lord-Kamina** [comment]
Closing since this was a platform-specific bug that was already fixed in libepoxy 1.5.3.
