### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#389]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Our current CI (semaphore) is using ubuntu trusty (14.04). This is rather old and has lots of old packages.
In my opinion a CI server should be an up to date system to build your program with the latest and greatest of each of the packages. If you want to check for compatibility an older CI server can be used this is currently the main reason we're still using the current server.

I'd suggest adding an updated CI system and keep semaphore for compatibility checks.
This updated CI should

- [x] Build performous for Linux
- [x] Build performous for OSx
- [ ] Build performous for Windows

**Comment by basisbit** [comment]
Maybe using docker + travis-ci you could test building with bunch of old and new environments, and also get to enjoy nice integration in github web ui, pull request requirements and so on?

**Comment by Baklap4** [comment]
I was thinking of that yeah 👍 containers <3 Also makes CD available 👍

**Comment by Baklap4** [comment]
We have recently merged the semaphore2 patch however we can still improve the ci:

I'd say the steps will be:

- [ ] Fetch dependencies (parallel for each system (linux, unix, win32 (cross/native)))
- [ ] Build (parallel for each system (linux, unix, win32 (cross/native)))
    - And parallel for gcc and clang (meaning this will be 6 jobs parallel)
- [ ] Deploy all versions (the previous 6) as release to github (when master is targeted) (not sure if this is nicely integrated in github tho)

**Comment by lua86** [comment]
So, I've been wondering (and felt like this issue would be the best place to ask), is there interest to add AppImage artifact building to the CI build? I don't wanna read on semaphore 2 and go through the effort if you're unlikely to refuse my merge request.

**Comment by Lord-Kamina** [comment]
I say yes, but I don't really use Linux so 🤷🏼‍♂️

**Comment by Baklap4** [comment]
> AppImage artifact building

@lua86 We currently have an open PR to support appimage #642 

Feel free to leave suggestion in regard of that in that pr :)

Closing this issue since semaphore can't do windows builds as of yet.
