### ISSUE TITLE
Not able to get it running on Win 7, Win 8, Win 10 or MacOS 10.13.6

### ISSUE THREAD

**Issue by tmueller78** [performous/performous#391]
I've been trying to run Performous a incredibly high number of systems because I'd love to use it after having seen it last night. Regrettably, I don't get it to run AT ALL. I tried whatever I could find in the Troubleshooting, so I figure it's some general issue in the compiled versions.

I always run into the same issue: the song doesn't start playing after selection, even if using the free songs from the site. I often get an error saying the devices have to be set up, but that also looks good except that I can't edit the configuration in the settings for the speaker.

I tried it on:
- MacOs High Sierra
- Windows 7 in a Parallels environment
- Windows 8
- Windows 10

I'm really excited to use Performous, so I'd highly appreciate any support!

**Comment by Lord-Kamina** [comment]
Are you trying to compile it yourself or using the 1.1 binaries?

**Comment by Lord-Kamina** [comment]
While those binaries used to work, MANY... MANY things have changed since then.

This is not a stable build and it was made for my birthday last month amidst some not-small changes to the rendering code so I cannot promise how well or not it will work but do give it a try: 

https://www.dropbox.com/s/9j34gstdlzuehky/Performous.dmg?dl=1

**Comment by tmueller78** [comment]
Happy belated birthday! :)

I iried it, same result. :(

I could imagine it's got something to do with me not being able to change the setting here (Mac):
![image](https://user-images.githubusercontent.com/3420501/44013139-0ab749c0-9ec4-11e8-8d9d-6bb3f4a8a732.png)

I tried fiddling around with the command line with the 1.1. binaries on MacOS but didn't really get anywhere.

**Comment by Lord-Kamina** [comment]
Wait... where is that, exactly?

**Comment by tmueller78** [comment]
Ah, sorry, German Screenshot. :(

It's under configuration -> audio -> audio devices

**Comment by Lord-Kamina** [comment]
@tmueller78, you're not supposed to change anything there.

The proper interface for setting up devices is in Settings -> Audio Devices, it's a separate screen that looks like this:

![0 2018-08-13 at 11 33 44](https://user-images.githubusercontent.com/6446892/44038349-f8bd4dfe-9eec-11e8-8f5b-c3630fe01df9.PNG)

Also, try going to ~/.config/performous (old location) and ~/Library/Preferences/Performous (new location) and delete the config.xml if present, and try again.

**Comment by tmueller78** [comment]
Wooohoo! It's working! :))))))))))))))))

**Comment by Baklap4** [comment]
Great to hear it's working for you 👍 If you encounter any more bugs feel free to open a new issue ;)!
