### ISSUE TITLE
how to make notes txt?

### ISSUE THREAD

**Issue by jst000000** [performous/performous#392]
how to make notes txt?

**Comment by Lord-Kamina** [comment]
For singing, they're the same format as Ultrastar songs. You can find plenty of Ultrastar sites if you Google. If you want to make them from scratch, you can usually do so with a midi, and a program like yass, ultrastar itself or possibly even the performous composer, but it takes time and work and there are plenty of songs available online already

**Comment by nieknooijens** [comment]
a list of tools can be found here:
https://github.com/performous/performous/wiki/Creation-tools
they usually involve splitting the lyrics into notes and then syncing them with your music. it's quite a time-consuming work so to avoid doing double work I suggest checking ultrastar-es.org and usdb.animux.de first (they both require registration).

usdb.animux.de only provides text files, you need to come up with your own mp3 and sync it. syncing up the mp3 is quite easy, just play with the #GAP tag a little.

**Comment by nieknooijens** [comment]
for chinese songs you can go to http://usasian.forumotion.net/
you do need to introduce yourself and thank every creator personally, it's quite a closed community, but they do provide what you're looking for.

**Comment by Baklap4** [comment]
I think this can be closed then 👍
