### ISSUE TITLE
audio bitwidth question, the audio data size is just for float(32bit)?

### ISSUE THREAD

**Issue by jst000000** [performous/performous#394]
i see the audio.cc code,it would convert the mic output data with sample.hpp,but not on the music data.
is the performous have just support music which bitwidth is 32bit  that what i confused ？

**Comment by nieknooijens** [comment]
As far as I know everything is resampled to Signed-16-bit audio.

**Comment by nieknooijens** [comment]
`void FFmpeg::processAudio(AVFrame* frame) {
	// resample to output
	int16_t *output;
	int out_linesize;
	int out_samples = avresample_available(m_resampleContext) +
		av_rescale_rnd(avresample_get_delay(m_resampleContext) +
		frame->nb_samples, frame->sample_rate, m_rate, AV_ROUND_UP);
	av_samples_alloc((uint8_t**)&output, &out_linesize, AUDIO_CHANNELS, out_samples,
		AV_SAMPLE_FMT_S16, 0);
	out_samples = avresample_convert(m_resampleContext, (uint8_t**)&output, 0, out_samples,
		&frame->data[0], 0, frame->nb_samples);
	// The output is now an interleaved array of 16-bit samples
	std::vector<int16_t> m_output(output, output+out_samples*AUDIO_CHANNELS);
	audioQueue.push(m_output,m_position);
	av_freep(&output);
	m_position += double(out_samples)/m_rate;
}
`

from ffmpeg.cc

**Comment by jst000000** [comment]
that make me confused,is performous use portaudio to record mics data and use ffmpeg to decode music data?

**Comment by jst000000** [comment]
and yes,if use ffmpeg process audio we get the S16 data, but why we need to use float type to access S16data?
`	bool operator()(float* begin, float* end, std::int64_t pos, float volume = 1.0f) {
		std::unique_lock<mutex> l(m_mutex);
		size_t idx = pos + m_data.size() - m_pos;
		size_t samples = end - begin;
		for (size_t s = 0; s < samples; ++s, ++idx) {
			if (idx < m_data.size()) begin[s] += volume * da::conv_from_s16(m_data[idx]);
		}
		m_posReq = std::max<std::int64_t>(0, pos + samples);
		wakeups();
		return !eof(pos);
	}`

**Comment by jst000000** [comment]
and yes,if use ffmpeg process audio we get the S16 data, but why we need to use float type to access S16data?

`	bool operator()(float* begin, float* end, std::int64_t pos, float volume = 1.0f) {
		std::unique_lock<mutex> l(m_mutex);
		size_t idx = pos + m_data.size() - m_pos;
		size_t samples = end - begin;
		for (size_t s = 0; s < samples; ++s, ++idx) {
			if (idx < m_data.size()) begin[s] += volume * da::conv_from_s16(m_data[idx]);
		}
		m_posReq = std::max<std::int64_t>(0, pos + samples);
		wakeups();
		return !eof(pos);
	}
`

**Comment by jst000000** [comment]
and yes,if use ffmpeg process audio we get the S16 data, but why we need to use float type to access S16data?

```
	bool operator()(float* begin, float* end, std::int64_t pos, float volume = 1.0f) {
		std::unique_lock<mutex> l(m_mutex);
		size_t idx = pos + m_data.size() - m_pos;
		size_t samples = end - begin;
		for (size_t s = 0; s < samples; ++s, ++idx) {
			if (idx < m_data.size()) begin[s] += volume * da::conv_from_s16(m_data[idx]);
		}
		m_posReq = std::max<std::int64_t>(0, pos + samples);
		wakeups();
		return !eof(pos);
	}
```

**Comment by nieknooijens** [comment]
probably the ffmpeg data gets forwarded to portaudio somehow converting it to float again.
it's a mess....

**Comment by jst000000** [comment]
i think so....

**Comment by Tronic** [comment]
All internal audio processing should use floats. Externally S16 needs to be used, but these are converted to and from floats in FFMPEG interface (for decoding media files) as well as libda (for talking to PortAudio and audio hardware).

**Comment by Baklap4** [comment]
Closing this due to being answered i believe. Please re-open if there's stll something to be questioned or doesn't have an answer.
