### ISSUE TITLE
libavresample is deprecated, switch to libswresample

### ISSUE THREAD

**Issue by swurzinger** [performous/performous#396]
libavresample is deprecated in current versions of FFMPEG and not built anymore by default. It should be replaced by libswresample, providing a very similar API.
If support for older Linux versions (like Ubuntu 14, which ships with libav) is required a wrapper could be easily built that supports both libraries, but usually libavresample can be simply replaced.

**Comment by dos1** [comment]
There's already a patch for that in Arch Linux: https://git.archlinux.org/svntogit/community.git/tree/trunk/performous-libswresample.patch?h=packages/performous&id=bbef3c0770c2952cd0041592edaf87d6d3a31041

**Comment by nieknooijens** [comment]
wtf? and they forgot to tell us? :disappointed:
