### ISSUE TITLE
Should we remove Boost predefs?

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#398]
When I initially wrote the Platform class, I embedded the minimal headers for boost predefs as a fallback  in case somebody was running Boost 1.54 or lower.

We have now dropped support for trusty, which had boost up to 1.55 (without PPAs) and I don't know any other potential system that would ship such an old version of boost.

So, I'm tempted to remove these files now. Opinions?

**Comment by nieknooijens** [comment]
trusty is 14.04 right? it has support up to next april.
If it still compiles on 14.04 I'd say, wait until april when support is fully dropped then get rid of it.
If current master already breaks 14.04 compability, I'd say, get rid of those files ASAP.

**Comment by Lord-Kamina** [comment]
It doesn't compile any longer, that is why we changed the semaphore and why I said we no longer suppprt it.

**Comment by Baklap4** [comment]
Let's remove them as they no longer serve any purpose then

**Comment by Lord-Kamina** [comment]
I've already done so in an uncommitted branch.

**Comment by Baklap4** [comment]
@Lord-Kamina A while ago you said you already did so, can you push the branch so we can close this item?

**Comment by Lord-Kamina** [comment]
Close it if you want. I haven't pushed because that branch is still heavily WIP
