### ISSUE TITLE
Fullscreen mechanism.

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#407]
So... I'm fixing the resizing issue with my gl branch and I just realized something.

In `setFullScreen`, we're using `SDL_SetWindowFullscreen(screen, (m_fullscreen ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0 ));`

According to the SDL Wiki:

> flags may be SDL_WINDOW_FULLSCREEN, for "real" fullscreen with a videomode change; SDL_WINDOW_FULLSCREEN_DESKTOP for "fake" fullscreen that takes the size of the desktop; and 0 for windowed mode.

So... is this really our desired behavior? Should it remain as is, or should we switch to SDL_WINDOW_FULLSCREEN ?

**Comment by yoda-jm** [comment]
SDL_WINDOW_FULLSCREEN is a PITA, at least in the past it changed resolution and really broke everything else. I would prefer keeping the SDL_WINDOW_FULLSCREEN_DESKTOP behavior.

**Comment by Lord-Kamina** [comment]
> SDL_WINDOW_FULLSCREEN is a PITA, at least in the past it changed resolution and really broke everything else. I would prefer keeping the SDL_WINDOW_FULLSCREEN_DESKTOP behavior.

I just tested it now and, while it appears to be using a pretty arbitrary full-screen resolution (1600x900), that can probably be fixed and it appears to be working well otherwise.

I'm just asking because many things that were true for SDL1.2 aren't necessarily so for SDL2 (like the fact SDL 1.2 couldn't set fullscreen without destroying the OpenGL context)

**Comment by Baklap4** [comment]
If `SDL_WINDOW_FULLSCREEN` is not causing problems i'd suggest to use that. However i think we're using  `SDL_WINDOW_FULLSCREEN_DESKTOP` as for when a fullscreen app crashes or hits an exception it could freeze your screen making it hard to tab out of it. That's why many programs use fullscreen as borderless fullsized application (the latter). Another thing for the user is multi window setup which is easier with borderless fullscreen than exclusive fullscreen.

**Comment by nieknooijens** [comment]
sdl fullscreen broke a lot of shit back in the SDL1 days, when I ported it over to sdl2 SDL_WINDOW_FULLSCREEN_DESKTOP was a relief! it basically creates a borderless window with the exact same resolution as your current desktop. in fact, portal2 team fortress and other valve games use this mecdhanism as well!

**Comment by Lord-Kamina** [comment]
Fair enough.

**Comment by Baklap4** [comment]
Also for reference: https://gamedev.stackexchange.com/questions/136367/what-is-the-point-of-a-borderless-fullscreen-window

**Comment by nieknooijens** [comment]
in SDL1 SDL_WINDOW_FULLSCREEN also broke multi-monitor displays, showing half of performous on monitor 1 and half on monitor 2. the SDL2 port with SDL_WINDOW_FULLSCREEN_DESKTOP actually fixed performous' oldest bug (the multi monitor issue)

**Comment by Baklap4** [comment]
Closing this question since many answers have been given
