### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#420]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

1. Build performous from scratch
2. Open performous (It opened in windowed mode)
3. Maximize performous window (middle button in the menu bar near the close button)
4. Performous goes into full screen mode
5. Go to settings, change full screen mode to disabled (this results in performous windowed mode being the size of desktop)
6. Save config
7. Close performous
8. Start performous
9. Close performous (essential)
10. Start performous
11. Performous is suddenly in full screen mode

### What did you expect to see?
I expected performous to be still in windowed mode.

### What did you see instead?
Performous was in fullscreen state needing to be changed to windowed mode again :/

### Output of `performous --version`: (_What version of Performous are you using?_)
Latest master

### What is your environment & configuration (arguments, platform, ...)?

Ubuntu 1704

**Comment by Lord-Kamina** [comment]
I cannot reproduce this.

**Comment by Baklap4** [comment]
Hmmm maybe a difference between os'ses hmm...

**Comment by jose1711** [comment]
arch linux + gnome. i don't have any maximize button on the toolbar, only close [x]. maximizing window by doubleclicking the titlebar does not make it go fullscreen (titlebar is still shown). could be caused by modifications specific to ubuntu.

**Comment by Lord-Kamina** [comment]
@jose1711 I don't know about that (maybe it's configurable on SDL window creation) but you can also toggle fullscreen:

 - From Settings/Graphics
 - By pressing Alt+Enter
 - I think also by pressing Alt+F or F11

**Comment by jose1711** [comment]
ok, just tested and i am unable to reproduce this either

**Comment by Lord-Kamina** [comment]
@nieknooijens can you reproduce this?

**Comment by nieknooijens** [comment]
I didn't test it on latest master but 3 weeks ago I had this exact same issue on 18.04LTS.
my workaround was to drag performous to the side of the screen (will snap in place to fill the left half of my monitor)then resize the right edge to the screen width, performous goes fullscreen, but at least I told it to store the new windowed dimensions, then press F11 and it will go windowed at desktop size. (with title-bar)
