### ISSUE TITLE
game feedback should be localised too

### ISSUE THREAD

**Issue by jose1711** [performous/performous#423]
https://github.com/performous/performous/blob/fb64ebc17c08fd3d0b454cd0592e93bd6ab79f0f/game/layout_singer.cc#L72

performous already is l10n friendly so i think it should be also extended to the feedback game provides during singing/playing/dancing.

**Comment by Lord-Kamina** [comment]
You're right. To be honest, I'd never noticed it _wasn't_ (I hate using translations of any kind unless I don't have a choice)

**Comment by Baklap4** [comment]
so this is fixed by replacing all hard coded values if i'm correct?
@jose1711 can you manage to get a list of strings to be localised and where they are at in the latest master?

**Comment by jose1711** [comment]
@Baklap4 I think it all affects just two files:
```
game/dancegraph.cc (Perfect, Excellent, ..)
game/layout_singer.cc (Pefect, Excellent, ..)
```
