### ISSUE TITLE
ď (d caron) not displayed correctly at the end of the line

### ISSUE THREAD

**Issue by jose1711** [performous/performous#428]
for some reason "ď" character is rendered as "d" (without the caron) when it's the last character on the line. consider this lyrics:
```
: 1 1 -1 Jeď
: 4 2 1 jeďte
: 9 1 2  ďam
: 11 3 2 raď
: 16 2 2  ďďď
: 20 1 2 ĎĎĎ
```
it renders as
![obrazok](https://user-images.githubusercontent.com/1406222/49512724-2041e000-f88f-11e8-99b2-8edb9188989a.png)

**Comment by Baklap4** [comment]
possible duplicate of https://github.com/performous/performous/issues/427

**Comment by jose1711** [comment]
definitely not a duplicate of #427 as the outcome depends on the position of a letter on a line

**Comment by jose1711** [comment]
after changing font-size to 42px in `sing_lyricscurrent.svg` a few pixels of caron starts to appear. it looks as if the computation of character width is not working correctly. for now the easiest workaround is editing both `sing_lyricscurrent.svg` and `sing_lyricsnext.svg` replacing `Goblin` family with something more common (Arial for instance). a separate theme might be kind of an overkill for this, but it would be a cleaner solution

**Comment by nieknooijens** [comment]
if we're going to use Arial please use the freetype equivalent. original Arial has microsoft licensing issues.

**Comment by Lord-Kamina** [comment]
It might be a bug introduced in my last PR and if not, it might be an unnoticed issue from before. A couple years ago, performous text would just overflow off-screen. One of my first commits actually dealt with fixing that, but maybe they've still got issues.

**Comment by Lord-Kamina** [comment]
Also... What language is this again? Slovak?
Is it acceptable in such for a word to end in d‘?

**Comment by jose1711** [comment]
it's slovak and/or czech. words ending in ď are relatively common in both languages.
```
$ aspell -d sk dump master  | aspell -l sk expand | tr ' ' '\n' | sort -u | grep -c 'ď$'
821
$ aspell -d cs dump master  | aspell -l cs expand | tr ' ' '\n' | sort -u | grep -c 'ď$'
974
```

**Comment by Lord-Kamina** [comment]
Ok. Just wanted to make sure it wasn't in some way related to ICU

**Comment by jose1711** [comment]
confirming #462 fixed the issue. thank you, closing
