### ISSUE TITLE
type filter not working in git version

### ISSUE THREAD

**Issue by jose1711** [performous/performous#432]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

In-game filter for type (has vocals, has dance, etc) is not working in current version - no songs are displayed when a specific filter is activated. Installing performous 1.1 restores the fuctionality.

### Output of `performous --version`: 

```
1.1-766-gc4fcfecc
```

### What is your environment & configuration (arguments, platform, ...)?

Arch Linux, 64bit

**Comment by Lord-Kamina** [comment]
I can confirm this but I'm not quite sure where it went wrong.
I'm fairly sure we tested the new version a lot, didn't we @Baklap4 ?

**Comment by Lord-Kamina** [comment]
Ok I found the issue. I've solved about half of it but there's a specific scenario that's still broken (blame is on my duet fixes a while ago), am still figuring out how to handle it.

**Comment by Lord-Kamina** [comment]
@jose1711 can you please confirm whether my latest changes fixed this? (You'll need to delete the song caché)

**Comment by jose1711** [comment]
@Lord-Kamina if you're ready to wait til Sunday then yes (not at my home PC currently)

**Comment by Lord-Kamina** [comment]
~~NO IT HAS TO BE TODAY~~ it was already merged, so at worst it'll need some extra work.

**Comment by jose1711** [comment]
thank you, confirming the fix works for me
