### ISSUE TITLE
LANG envvar should be used to determine language, not LC_CTYPE

### ISSUE THREAD

**Issue by jose1711** [performous/performous#435]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Tried to run performous in my non-default locale (`sk_SK.utf8`).

### What did you expect to see?

Common way to switch program language on Linux is by setting `LANG` environment variable, e. g. `LANG=fr_FR.utf8 mc` starts Midnight commander in French. For some reason performous reads `LC_CTYPE` instead, so while `LANG="fr_FR.utf8" performous` does not switch the language to French, `LC_CTYPE="fr_FR.utf8" performous` does. `LANG` should be honoured as this is a standard.

### What did you see instead?
Looks like performous only checks for `LC_CTYPE` and ignores the rest of `LC_` variables or `LANG`.

### Output of `performous --version`:

```
Performous 1.1-766-gc4fcfecc
```

### What is your environment & configuration (arguments, platform, ...)?

Arch Linux 64bit

**Comment by Lord-Kamina** [comment]
I'm not sure how but I reckon Arch Linux might be factoring into this.

In both windows and mac, language works as expected (nor sure in other Linux distros). I can also say that the mac launcher affects the language before running performous by exporting LANG and not LC_CTYPE.

Finally, if anything I'd say this issue might be on Boost more than on us: https://www.boost.org/doc/libs/1_65_0/libs/locale/doc/html/locale_gen.html

**Comment by jose1711** [comment]
interesting, just found out that performous 1.1 does respect `LANG` variable, it's only -git version that is showing the described symptoms

**Comment by Lord-Kamina** [comment]
@jose1711 Performous 1.1 used gettext, not boost locale.

**Comment by Lord-Kamina** [comment]
Also, where did you get that LANG is the standard? Most resources I've found online say that LANG is used as fallback when LC_something is not set.

**Comment by Baklap4** [comment]
Running `LANG=ja_JA.UTF-8 performous` makes performous globally installed use the japanese language.. hmm? Running ubuntu 1710 here latest master

**Comment by jose1711** [comment]
not sure what is going on. i rebuilt performous 1.1 manually to see if there's maybe a flaw in my build toolchain but i can only confirm the behaviour i've seen earlier: `LANG` works for 1.1 but does not work on current master. i am reaching out to other arch linux users to validate (https://aur.archlinux.org/packages/performous-git/)

**Comment by Lord-Kamina** [comment]
Did you read what I posted above? All documentation I have seen say LANG is actually just a fallback, not the de-facto standard you claim. And boost locale (which is what performous uses) only uses LANG if LC_CTYPE and LC_ALL are unset.

What is the output of `locale` in your terminal?

Also, try `man locale` and see whether it says something different from what I posted.

**Comment by Baklap4** [comment]
Hmm instead of using `LANG=fr_FR.utf8 performous`
Can you type `export LANG=fr_FR.UTF-8 && performous` this should fill your LANG variable as `fr_FR`. Also what's the output of `locale`

**Comment by jose1711** [comment]
I  did read your comment but did not want to rush it as investigation was ongoing. Nice summary of how locale-relevant are used is at https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html:
```
LANG is the normal environment variable for specifying a locale.
As a user, you normally set this variable (unless some of the other
variables have already been set by the system, in /etc/profile or
similar initialization files).

LC_CTYPE, LC_NUMERIC, LC_TIME, LC_COLLATE, LC_MONETARY, LC_MESSAGES,
and so on, are the environment variables meant to override LANG and
affecting a single locale category only.
```
So probably setting `LANG` was not that far off - notice how it worked for mc (but also for gedit, josm, nautilus, patchage which I've just tested).

What I found later on is that one of the scripts in [ohmyzsh](https://github.com/robbyrussell/oh-my-zsh) I am using sets `LC_CTYPE` to `sk_SK.UTF-8`. Unsetting this variable makes `LANG=fr_FR.utf8 performous` work as expected.

Anyway, I still don't understand why it's `LC_CTYPE` (i. e. a category that determines the interpretation of byte sequences as characters) is a factor that determines the displayed language. I would assume `LC_MESSAGES` to be used instead (`man 7 locale` on Arch: `This  category  affects the language in which messages are displayed`).

Some more tests:
```
unset LC_CTYPE  # as this is set by ohmyzsh called by .zshrc
LANG=fr_FR.utf8 performous
# performous using French => all good here

# make sure no other `LC_` var is set
env | grep LC => empty
# LANG is set to sk_SK.utf8
echo $LANG => sk_SK.utf8
LC_MESSAGES=fr_FR.utf8 performous
# I am overriding LANG partially (for translated text)
# performous showing Slovak text instead of using French
# so this is not expected

# tried the same with LANG unset
unset LANG; LC_MESSAGES=fr_FR.utf8 performous
# performous running in English (not good)
``` 
If I repeat the steps above using performous 1.1 I get French in all 3 tests.

**Comment by Lord-Kamina** [comment]
Performous 1.1 uses a different internationalization engine; and Boost (what we use now) gives priority to LC_CTYPE. I don't know why but it's just how it is.

**Comment by Baklap4** [comment]
As quoted from [boost docs](https://www.boost.org/doc/libs/1_69_0/libs/locale/doc/html/locale_gen.html): 
> The default locale is defined by the environment variables LC_CTYPE , LC_ALL , and LANG in that order (i.e. LC_CTYPE first and LANG last). On Windows, the library also queries the LOCALE_USER_DEFAULT option in the Win32 API when these variables are not set.

**Comment by Lord-Kamina** [comment]
I do think I've found a possible way to fix this to everyone's satisfaction, though.
I've always been assuming the default locale is what we should be using and boost constructs that based on what we've been saying here. But it also seems it's possible to use `boost::locale::util::get_system_locale()` instead.

From a small change I did just now to test I got the following output:

(LANG=es_CL-UTF-8)
```
locale/debug: Boost says default locale is: *
locale/debug: Boost says system locale is: es_CL.UTF-8
```
(LANG=en_CL-UTF-8)
```
locale/debug: Boost says default locale is: *
locale/debug: Boost says system locale is: en_CL.UTF-8
```

**Comment by Lord-Kamina** [comment]
@Baklap4 This should fix it but I can't currently commit because my working copy is a mess and I'm on an unpublished branch and frankly I don't want to deal with stashing now. 🤣 

Could you commit/PR from the attached patch?

[0001-Locale-fix.patch.txt](https://github.com/performous/performous/files/2707492/0001-Locale-fix.patch.txt)

**Comment by Baklap4** [comment]
@Lord-Kamina your patch is doing the exact thing as what `""` does...

https://www.boost.org/doc/libs/1_54_0/libs/locale/doc/html/locale_gen.html
``` #include <boost/locale.hpp>
    
    using namespace boost::locale;
    int main()
    {
        generator gen;
        // Create locale generator 
        std::locale::global(gen("")); 
        // "" - the system default locale, set
        // it globally
    }```

**Comment by Lord-Kamina** [comment]
It's not. That's the thing. The "system default" is not the same as "the current system locale", in fact I just tried it and for example it gets rid of the necessity to specify LANG in the macOS launcher.

To clarify, the output I pasted above was from calls to `gen("").name()` (default locale) and get_system_locale (system locale). As you can see above, they yield (or may yield in some platforms) different values.

**Comment by Baklap4** [comment]
Ahh thanks for the clarification! opened #440 can @jose1711  check if this works?

**Comment by jose1711** [comment]
I disabled oh-my-zsh entirely to not skew the results (now `LC_CTYPE` is unset and so is the rest of the `LC_` variables) - still the outcome is the same (as in https://github.com/performous/performous/issues/435#issuecomment-449741888). Anyway at least `LANG=.. performous` (the 1st test) is working now - I did not have an urge to try anything else until now. Thank you for having a look, closing.

**Comment by Lord-Kamina** [comment]
But THAT IS the expected behavior. I don't know why Boost prefers LC_CTYPE to LC_ALL but that pretty much everywhere is categorical in saying LANG is a fallback.
