### ISSUE TITLE
iostream error while reading song.ini

### ISSUE THREAD

**Issue by jose1711** [performous/performous#437]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Trying to open a full band file yields the following error message on console and skips playback:
```
songparser/warning: /PATH/TO/song.ini:
  basic_ios::clear: iostream error
```
A "Song contains broken tracks" is shown briefly. Performous 1.1 is able to proces the file just fine. This is the contents of the directory with song data:
```
album.png:   PNG image data, 300 x 300, 8-bit/color RGB, non-interlaced
drums_1.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
drums_2.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
drums_3.ogg: Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
guitar.ogg:  Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
notes.mid:   Standard MIDI data (format 1) using 8 tracks at 1/480
rhythm.ogg:  Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
song.ini:    ASCII text
song.ogg:    Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
vocals.ogg:  Ogg data, Vorbis audio, stereo, 44100 Hz, ~192000 bps, created by: Xiph.Org libVorbis I (1.2.0)
```

### Output of `performous --version`: 

```
Performous 1.1-767-g314137bf
```

### What is your environment & configuration (arguments, platform, ...)?

Arch Linux 64bit

**Comment by Lord-Kamina** [comment]
Could this be an issue relating to performous trying to parse the song as both a midi and an ini at the same time?

**Comment by jose1711** [comment]
What can I do to find out?

**Comment by Lord-Kamina** [comment]
Does the ini actually reference the midi? Maybe delete/rename the midi?

**Comment by jose1711** [comment]
Strange, I cannot reproduce the issue anymore. Maybe it got fixed after I removed the cache (?). Closing as invalid.

**Comment by Tronic** [comment]
The song loads and reloads just fine here, using current git master. Looks like it was a song cache issue, and is perhaps fixed by changing JSON libraries since this was reported.

@jose1711 could you test again?

**Comment by jose1711** [comment]
I still experience the problem with 4ed8ec78452a5c9e1aad55915378f301a4aa4bca

**Comment by jose1711** [comment]
The contents of the `Songs-Metadata.json` file is as follows:
```
[{"Artist":"Tommi Inkila","Cover":"/tmp/x/defy/label.png","Duration":167,"GuitarTracks":1,"PreviewStart":5,"SongFile":"/tmp/x/defy/song.ogg","Start":0,"Title":"Defy The Machine","TxtFile":"/tmp/x/defy/song.ini","TxtFileFolder":"/tmp/x","VideoGap":0}]
```

**Comment by Lord-Kamina** [comment]
Perhaps there's important info missing from the cache. 

Can you check https://github.com/performous/performous/tree/issue/refactor-bpm?files=1 out and see if you can reproduce the issue on that branch?

**Comment by jose1711** [comment]
yes, i can reproduce it with refactor-bpm branch too

**Comment by carlinchisart** [comment]
Hi, i have the same problem in arch linux, i think is possible any library for arch is diferent for ubuntu ? i try to use the other branch and no working.

thanks

**Comment by jose1711** [comment]
It is entirely possible that the issue is in one of the dependent libraries but since there are so many of them (just do `ldd $(which performous)`) I don't have any clue where to start looking. It would be ideal if the devs consider trying Arch.. :smile:

**Comment by Baklap4** [comment]
@jose1711 tarball is not found can you reupload it? I'd like to try this out since i introduced the caching :thinking: I can test it with either debian or Fedora

**Comment by ooshlablu** [comment]
@jose1711 Can you try again with a build against latest master? There was an issue with caching that presented exactly in the way you described. That has been fixed within the last couple of months.

**Comment by jose1711** [comment]
Tested with the current master and I no longer can reproduce it. Thank you, closing.
