### ISSUE TITLE
Mp3 file shorter than 30 seconds causes song to be skipped in preview

### ISSUE THREAD

**Issue by jose1711** [performous/performous#439]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Browsing songs I discovered that a specific song is skipped - this seems to be caused by a non-standard (invalid?) mp3 file. The song however plays normally. I will share the problematic mp3 file privately when asked.

### Output of `performous --version`: (_What version of Performous are you using?_)

```
Performous 1.1-767-g314137bf
```

### What is your environment & configuration (arguments, platform, ...)?

Arch Linux 64bit

### If applicable, please paste the log output in DEBUG level

```
ffmpeg/warning: Negative audio timestamp -0.025057 seconds, frame ignored.
ffmpeg/warning: Negative audio timestamp -0.025057 seconds, frame ignored.
ffmpeg/warning: Negative audio timestamp -0.025057 seconds, frame ignored.
ffmpeg/warning: Negative audio timestamp -0.023021 seconds, frame ignored.
ffmpeg/warning: Negative audio timestamp -0.025057 seconds, frame ignored.
```

**Comment by Lord-Kamina** [comment]
Are you certain this is not an caused by an invalid preview start on the song's txt file?

**Comment by jose1711** [comment]
i replaced an mp3 file in the folder with another one and the problem vanished

**Comment by Lord-Kamina** [comment]
That is beside the point. Can you post the song's txt file?

**Comment by jose1711** [comment]
[Two and a Half Men - Intro Theme.txt](https://github.com/performous/performous/files/2707570/Two.and.a.Half.Men.-.Intro.Theme.txt)

**Comment by Lord-Kamina** [comment]
So it appears you're right and it's a problem with the mp3... not sure if we can do much about that though.

**Comment by Lord-Kamina** [comment]
It's a possibility but I'm not entirely sure. If you just leave it there, doesn't it start playing eventually?

**Comment by Lord-Kamina** [comment]
That makes all the sense in the world then.

**Comment by nieknooijens** [comment]
since the PR is merged isn't this closed then?
