### ISSUE TITLE
CMake error installing Performous on Lubuntu 17.10

### ISSUE THREAD

**Issue by diver66** [performous/performous#453]
Just tried to install Performous on Oracle VM Virtual Box -> Lubuntu 17.10 (64bit). When running the cmake .. command I am getting the following error message 

CMake Error at cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GLM (missing: GLM_INCLUDE_DIR)
Call Stack (most recent call first):
  cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindGLM.cmake:56 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  game/CMakeLists.txt:86 (find_package)

any idea, what causes this ?

**Comment by diver66** [comment]
Thanks @lord-kamina , now it stops running with this error message 

CMake Error at CMakeLists.txt:75 (add_subdirectory):
  The source directory

    /home/diver66/performous/ced

  does not contain a CMakeLists.txt file.


google does not give me any information on ced

**Comment by Lord-Kamina** [comment]
It's a submodule. Google how to initialize and check-out submodules.

**Comment by diver66** [comment]
thanks for the hint, it works now I had to do 

git clone --recursive git://github.com/performous/performous

**Comment by diver66** [comment]
I really wanted this to work :-), just run into another problem, "cmake .." ran without problems and finished, but "make" throws an error

game/CMakeFiles/performous.dir/build.make:1502: recipe for target 'game/CMakeFiles/performous.dir/unicode.cc.o' failed
make[2]: *** [game/CMakeFiles/performous.dir/unicode.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:158: recipe for target 'game/CMakeFiles/performous.dir/all' failed
make[1]: *** [game/CMakeFiles/performous.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

what can I do now ?

**Comment by Lord-Kamina** [comment]
You need ICU > 60. Either find a backport or install a newer OS.

**Comment by Baklap4** [comment]
@Lord-Kamina we really need to add the versions of which we minimal need to cmake

**Comment by diver66** [comment]
a newer OS ? I am about to upgrade from Lubuntu 17.10 to Lubuntu 18.04 , let's see what happens then

**Comment by diver66** [comment]
``
