### ISSUE TITLE
Ctrl-Fx should provide visual feedback

### ISSUE THREAD

**Issue by jose1711** [performous/performous#454]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Currently keys for tuning latency during song playback provide no visual output making it more difficult to recognize whether the shortcut is recognized by the app or what the current setting is. An OSD information showing the current latency set would be greatly appreciated.

### Actual result

The keys are bound to other keys instead of the keys described on the wiki.

### To Do
- [ ] Update the wiki with new key combinations

**Comment by nieknooijens** [comment]
there is a function dispInFlash() for that. shouldn't be too hard to add to the key handler functions.
I'm surprised this isn't called on any setting yet.

**Comment by Baklap4** [comment]
Hmm latency is being flashed tho?: 
![image](https://user-images.githubusercontent.com/3918517/51184770-9184a200-18d5-11e9-8f9e-f9c6d8cfbda2.png)

**Comment by jose1711** [comment]
ha, you are right! so this is in fact an out-of-date documentation (+ in game hints) issue

**Comment by Baklap4** [comment]
Closed since #511 was merged to current master and the hint is back up to date :)! Thanks for sharing @jose1711
