### ISSUE TITLE
Submodules in the same style

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#461]
Currently our submodules don't use the same method to build.
# TODO
- [ ] Consolidate submodules under 3rdparty
- [ ] Make all urls use either SSH or https

# Linked
This came from the pull request: #459

**Comment by Tronic** [comment]
I'd say that https is safer. In many places firewalls prohibit the use of ssh (yes, it is stupid, but unfortunately users have little control over such restrictions).

**Comment by Lord-Kamina** [comment]
I prefer https but depending on github's mood on an  given day I've had mixed success while pushing using both methods 😂🤷🏼‍♂️

**Comment by Baklap4** [comment]
Eitherway, just make it ssh or https.. not both :P

**Comment by OznOg** [comment]
why not simply relative path like:
```
[submodule "ced"]
        path = ced
        url = ./compact_enc_det
[submodule "3rdparty/aubio"]
        path = 3rdparty/aubio
        url = ./aubio
```
This should do what we expect: take the url from the base repo, thus https or git@ depending on how you checked-out

**Comment by Baklap4** [comment]
Looks like a good idea @OznOg!
I'd move ced to 3rdparty/ced aswell
Feel free to open a pr :)!

**Comment by Baklap4** [comment]
Made  PR to fix this
