### ISSUE TITLE
Performous isn't working now

### ISSUE THREAD

**Issue by rodroes** [performous/performous#463]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you expect to see?
I expected to run the program. 

### What did you see instead?
Console showed error mesages (see the bottom of this report) 

### Output of `performous --version`: (_What version of Performous are you using?_)
Performous 1.1+

### What is your environment & configuration (arguments, platform, ...)?
Test under Linux Mint 19.1, Cinnamon flavour. I think sound is under PulseAudio. My Graphics card is an ATI Radeon HD 7600, using radeon free driver. OpenGl is enabled and Mesa version is 18.2.2 with direct rendering. 
Kernel used is 4.18.0-16

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)
logger/notice: Logging all notices, warnings and errors. Log file: /home/rodrigo/.cache/performous/infolog.txt
core/notice: Performous 1.1+ starting...
  Internationalization: Enabled
  MIDI Hardware I/O:    Enabled
  Webcam support:       Disabled
core/notice: Starting the audio subsystem (errors printed on console may be ignored).
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
opengl/error: Invalid enum in Shader::compile glCreateShader
terminate called after throwing an instance of 'std::runtime_error'
  what():  stereo3d.geom: Couldn't create shader.
Abortado (`core' generado)

**Comment by nieknooijens** [comment]
did you install it from the repositories or build it from source?

**Comment by rodroes** [comment]
EDIT: I have started Performous properly. I built it from source, but now I am not able to hear any sound. Alsa is working at the moment, but at least the program started. Let me investigate a bit more, to give better info to everybody. Thank you very much!

**Comment by rodroes** [comment]
EDIT again: Finally Performous worked! It seemed to be some rubbish configuration on home/.config/performous. If you are new on linux (like me), and Performous stopped to work, try these steps: 
1 - From console, uninstall the program: sudo apt-get remove performous
2 - Build the program from source (take a look to build instructions on the performous download page).
3 - Delete files (make a copy first!) of files on /home/.config/performous/
4 - Run the program!
My apologies to experienced users, by the way. I should imaginate this issue on my own. Thanks anyway!!
