### ISSUE TITLE
Allow selection of output audio device(s)

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#464]
Performous appears to play audio on ALSA card:device 0:0

As a feature request it should allow the user to select on which device(s) to play audio.

FYI: Despite my best efforts I could not manage to play audio from my Ubuntu Laptop through HDMI connected to my TV.  Other ALSA applications worked fine so I assume that performous or the library it uses to output audio has hardcoded the card:device (0:0) instead of using the default device.

**Comment by Lord-Kamina** [comment]
Unless I'm missing something this should be trivial via the Audio Devices  configuration screen

**Comment by deuteragenie** [comment]
Aargh... you may be right.  I ended up fighting with my ALSA config rather than looking at the commandline options etc. I guess --audio should work fine. Apologies for the noise.

**Comment by Lord-Kamina** [comment]
I highly recommend using the graphical interface over the command line to configure that though.
