### ISSUE TITLE
LibICU dependency

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#465]
Compilation fails on Raspbian Stretch with LibICU 57.1
From reading previous issues it appears that LibICU > 60.0 is needed.
This requirement is difficult to meet, as they are no newer version of Raspbian available currently.  
1. Could Performous use a well supported LibICU ?
2. LibICU is not listed as a dependency in CMakeLists.  This needs to be corrected.

Workaround: install LibICU package from Debian "Buster".

**Comment by Baklap4** [comment]
Closing this since libicu is listed as a dependency now 1.60 or higher
