### ISSUE TITLE
Daily .deb builds

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#468]
Daily .deb builds seem to be broken for a couple of months:

https://launchpad.net/~performous-team/+archive/ubuntu/daily

**Comment by Lord-Kamina** [comment]
I think most of us on the team don't have access to that ppa. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deuteragenie** [comment]
I guess the question is where can one get daily builds then ?

**Comment by Lord-Kamina** [comment]
Nowhere, for now.
@TobiX think maybe you could add me to the performous ppa (and I don't know whoever else has an account at Launchpad?) or would @tapio have to do it? 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Baklap4** [comment]
Closing this in favor for: https://github.com/performous/performous/issues/214 and https://github.com/performous/performous/issues/389
Please continue talking in those threads.
