### ISSUE TITLE
OpenGL Shader compile error

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#469]
Installed performous from Ubuntu bionic repositories on Odroid N2.

I got a shader compile error when starting. Here are the relevant lines:

...
Shader color: 0:1: P0007: Language version "120" unkwown, this compiler only supports up to version '320 es'
terminate called after throwing an instance of 'std::runtime_error'
what(): core.vert: Shader compile error.
...

Further to this, after this error is emitted, the whole system becomes unresponsive and requires a reboot.

Running the application in debug mode also confirms the following:
GL_VENDOR : ARM
GL_VERSION OpenGL ES 3.2 git-c8adbf9...
GL_RENDERER: Mali-G52

Not sure if it is a performous or an opengl driver issue...

This prevents the game to start.

**Comment by Lord-Kamina** [comment]
I wasn't even aware performous was in any bionic repositories. Anyway, that's almost certainly a very old version. The error is most likely related to those shaders using a very old version of GLSL

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deuteragenie** [comment]
Here is the link to the bionic package: https://packages.ubuntu.com/bionic/games/performous
Looks like the package is based on r1.1

Could it be something similar to this issue?

http://www.howtobuildsoftware.com/index.php/how-do/BYG/qt-opengl-es-20-shader-qopenglshader-cant-compile-glsl-120-on-android

**Comment by Lord-Kamina** [comment]
Seems like it, yeah. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deuteragenie** [comment]
Something is probably also wrong with this test in video_driver.cc
`
if (epoxy_gl_version() < 33) throw std::runtime_error("OpenGL 3.3 is required but not available");
`
Most likely for Odroid N2, epoxy_gl_version is >=33. However, the app requires desktop OpenGL and/or specifics.

libepoxy has a function epoxy_is_desktop_gl() which may come in handy.

**Comment by Baklap4** [comment]
@deuteragenie is this stil an issue as of today?
If so would you like to give us a pr regarding the `epoxy_is_desktop_gl()`?
Current master has some more info regarding opengl so feel free to try it again :+1:

**Comment by deuteragenie** [comment]
I would suggest to close this issue.  The app is not made to run with GLES.

**Comment by Baklap4** [comment]
Closing it as per suggestion
