### ISSUE TITLE
Update CED submodule to latest CED commit

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#471]
The title says it all.
This will address several warnings issued by the compiler on the current CED sub-module.  These have been addressed upstream.

**Comment by Baklap4** [comment]
Should be fixed in https://github.com/performous/compact_enc_det and then update submodules head here.
@Lord-Kamina can you make me an admin within the ced repo? I want to tweak some settings in that repo

**Comment by Lord-Kamina** [comment]
Done. What are you gonna change?

**Comment by Baklap4** [comment]
Thanks! Enabled issues, merge request options and security alerts :)

**Comment by Baklap4** [comment]
@deuteragenie our fork will be updated in a few. Once that's done we can update it in the main repo here. https://github.com/performous/compact_enc_det/pull/4

**Comment by Baklap4** [comment]
PR is made this will be merged in a couple hours/days

**Comment by Baklap4** [comment]
Pr is merged, thanks for reminding us :)!
