### ISSUE TITLE
illegal distribution of proprietary font

### ISSUE THREAD

**Issue by mirabilos** [performous/performous#473]
`DroidSansMono.ttf` has:

> This font software is the valuable property of Ascender Corporation and/or its suppliers and its use by you is covered under the terms of a license agreement. This font software is licensed to you by Ascender Corporation for your personal or business use on up to five personal computers. You may not use this font software on more than five personal computers unless you have obtained a license from Ascender to do so. Except as specifically permitted by the license, you may not copy this font software.

**Comment by Lord-Kamina** [comment]
Where does it say that?

Droid fonts are actually licensed under Apache AFAIK. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mirabilos** [comment]
Gregorio Litenstein dixit:

>Where does it say that?

In the font file itself.

>Droid fonts are actually licensed under Apache AFAIK. 

Then get a font file which says that… where did you copy the
binary font from?

><sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

… spam…
