### ISSUE TITLE
keypress is registered upon key release for dance mat

### ISSUE THREAD

**Issue by mirabilos** [performous/performous#481]
### Do you want to request a *feature* or report a *bug*?

Bug

### Forwarded bug information from another tracker

https://bugs.launchpad.net/ubuntu/+source/performous/+bug/1216191

#### information provided by the original submitter

Every time I lift my foot off of a button on my dance mat, Performous behaves as if I instead stepped on the button.

details:

  date: 2013-08-23
  OS: Ubuntu 13.04, fully patched as of this writing.
  architecture: amd64
  Performous version: 0.7.0-1ubuntu2
  dance mat:
    brand: DDR Game http://www.ddrgame.com
    model: Energy, USB/PS2/Xbox 3-in-one [using USB]
  config:
    dancemat string in config file: "0:DANCEPAD_EMS2"

**Comment by Lord-Kamina** [comment]
Does anybody even know where to start, on a 6-year old bug report?

**Comment by AssortedBits** [comment]
I guess I could try it again. I don’t actually have a Linux machine handy anymore. Probably still using the same pads, though.

**Comment by Lord-Kamina** [comment]
😂 perhaps you can try it on a live Linux install or something? Ideally at least running (I think) cosmic that has a package from late 2018. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Baklap4** [comment]
@AssortedBits did you managed to get this retested on latest master version?

For now i'll close this issue but if you still have this issue please reopen it.
