### ISSUE TITLE
[wishlist] work (in degraded mode) with OpenGL 2.1 (or maybe OpenGL ES 2.0?)

### ISSUE THREAD

**Issue by mirabilos** [performous/performous#482]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

A working performous on my work laptop (IBM Thinkpad X61) with more than ~5–6 fps (which is what I get from software rendering).

I know you guys will probably close this as “works as intended” or “we don’t have the resources for this”, but [I just learnt my laptop doesn’t support more](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934776#10) and was wondering if it’s possible to make Performous work, perhaps in degraded mode, with “just” OpenGL 2.1 (according to the documentation, it also supports OpenGL ES 2.0, but I have no idea what that is or how it works on Debian).

Ideally, this would be a run-time option, but even a compile-time one would work for me (we could package that as `performous-degraded` which `Provides: performous` then) and perhaps others.

While I understand that the goal is to produce a Free version of a game, and improve that and make it nice, perhaps someone feels my aim of getting it available on more systems (plus other use cases like choir tutor) might be worth your while.

**Comment by Lord-Kamina** [comment]
Not going to happen because we did plenty of work explicitly to move up from OpenGL 2.1. Performous 1.1 used OpenGL 2.1 though so that should work.

**Comment by mirabilos** [comment]
Hi Gregorio,

>Not going to happen because we did plenty of work explicitly to move
>up from OpenGL 2.1.

thought so, but asking doesn’t hurt; thanks for the answer.
No chance of shipping both, I assume.

>Performous 1.1 used OpenGL 2.1 though so that should work.

Hm yes, but that’d be unmaintained software… what if there are,
for example, necessary security fixes? Also improvements in
unrelated areas (e.g. I’m hoping for notation (as an option, instead
of those halftone lines) some day) would not be applicable.

I could certainly use that… for a while, but I’d essentially be
on my own, and I’m nowhere near familiar with the code at all.
I decided against in the case of MuseScore, where 2.x ought to
be available in parallel to the new 3.x, but has no upstream
interest any more either, so I replaced it (users can still
coinstall both versions, but the next Debian will ship only
3.x so they have to get 2.x from buster).

bye,
//mirabilos
--  
When he found out that the m68k port was in a pretty bad shape, he did
not, like many before him, shrug and move on; instead, he took it upon
himself to start compiling things, just so he could compile his shell.
How's that for dedication. -- Wouter, about my Debian/m68k revival

**Comment by Lord-Kamina** [comment]
Can't ship both because we're talking about maintaining two completely separate versions of the drawing code. It's a very complex change, not just modifying one or two lines.

So no, it's not really worth it for supporting  a 12-year old laptop that wasn't even made for games in the first place.

**Comment by Tronic** [comment]
What comes to security updates, I don't believe there has ever been a security issue with Performous. It is not connected to Internet so the only risk factor comes from downloaded songs. System-installed version of ffmpeg is used for decoding, so you will still get upgrades to that.

@Lord-Kamina is right. It is time to scrap your laptop and get modern hardware.
