### ISSUE TITLE
off-by-one in microphone colours

### ISSUE THREAD

**Issue by mirabilos** [performous/performous#486]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Try to assign the microphone a colour.

### What did you expect to see?

The chosen colour is used.

### What did you see instead?

The one to the left is used (or, for the red one, an invisible-in-the-config blue one is used).

![Screenshot_20190930_170254](https://user-images.githubusercontent.com/861078/65891363-a8581f80-e3a4-11e9-84af-08c603011dab.png)

This ↑ is a screenshot of the configuration dialogue. I have an orange microphone connected, but I need to select one to the right. If I select orange, it gets pink instead ☹

The default left-most one is shown as red but shows up as blue during gameplay.

### Output of `performous --version`: (_What version of Performous are you using?_)

```
Performous 1.1+
```

git commit 9928c27

### What is your environment & configuration (arguments, platform, ...)?

Debian GNU/Linux sid/amd64

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

```

Generic options:
  -h [ --help ]          you are viewing it
  -l [ --log ] arg       subsystem name or minimum level to log
  -v [ --version ]       display version number
  --songlist arg         save a list of songs in the specified folder

Configuration options:
  --audio arg            specify an audio device to use
  --audiohelp            print audio related information
  --jstest               utility to get joystick button mappings

ERROR: unrecognised option '--logLevel=DEBUG'
```

**Comment by Lord-Kamina** [comment]
This is really weird? I've never seen it happen. Will have to investigate. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lord-Kamina** [comment]
@Baklap4 have you been able to reproduce this?

**Comment by Baklap4** [comment]
Never seen this happen, currently closing as cannot-reproduce. @mirabilos if this is still an issue on current master please let us know :)
