### ISSUE TITLE
cmake shouldn't try to outsmart pkgconfig (when finding pango include paths)

### ISSUE THREAD

**Issue by SimonPe** [performous/performous#490]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I'm trying to build performous on archlinux against pango 1.44 which fails, because `FindPango.cmake` tries to outsmart pkgconfig and doesn't include all the needed include directories in the include path.

### What did you expect to see?

A working build.

### What did you see instead?

```
[ 31%] Building CXX object game/CMakeFiles/performous.dir/controllers-joystick.cc.o
In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                 from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                 from /usr/include/pango-1.0/pango/pango.h:25,
                 from /usr/include/pango-1.0/pango/pangocairo.h:25,
                 from /home/simon/.cache/pacaur/performous-git/src/performous-git/game/opengl_text.hh:6,
                 from /home/simon/.cache/pacaur/performous-git/src/performous-git/game/menu.hh:3,
                 from /home/simon/.cache/pacaur/performous-git/src/performous-git/game/screen_intro.hh:4,
                 from /home/simon/.cache/pacaur/performous-git/src/performous-git/game/configuration.cc:8:
/usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
   28 | #include <hb.h>
      |          ^~~~~~
compilation terminated.
```

### Output of `performous --version`:

This is against git master.

### What is your environment & configuration (arguments, platform, ...)?

I'm building on an up-to-date x86_64 archlinux

pkgconfig correctly has all the include paths: (including harfbuzz)

```
$ pkg-config pango --cflags
-I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 
```

**Comment by Lord-Kamina** [comment]
I am not convinced this bug is actually ours to fix.

**Comment by SimonPe** [comment]
@Lord-Kamina The bug is in `FindPango.cmake` and/or `FindPangoCairo.cmake` which are in this repo. Because not all include paths (and cflags, but in this case they are only includes) returned by `pkg-config` get used.

**Comment by Tronic** [comment]
Patching this within CMake is probably quite difficult (one does not simply use pkgconfig's flags blindly; instead each path should be a separately configurable CMake variable). The original script is written by me about a decade ago but someone else will have to fix it.

Maybe upstream already provides CMake config for Pango and PangoCairo, so that neither pkg-config nor those find modules are needed?

**Comment by SimonPe** [comment]
@Tronic why does one not simply use pkgconfig's flags blindly? That's what they're for. They (and all of pkg-config) exist to make your life easier and not have to worry about the whole dependency resolution and everything.
And no, upstream (as in gnome) doesn't provide CMake config, upstream provides pkg-config and says to use it.
If I'm entirely honest I have no clue why the CMake ecosystem tries to reinvent pkg-config.

**Comment by SimonPe** [comment]
I did a little exercise here:
I changed 3 libraries (pangocairo, librsvg, and gstreamer) to just use pkg-config and could throw away 19 other "Find***.cmake" files (next to reducing 3 of them to one-liners).

I have the impression that not just using pkg-config is just making it hard on yourselves.

And the resulting buildflags are all still correct.

**Comment by Tronic** [comment]
The idea in CMake is that all paths are recorded during configuration and may be configured and modified by UI, and that contract should not lightly be broken. Our scripts use pkg-config for initial guesses of paths but other than that it is and should be stand-alone (for instance, the scripts do check that specific header files actually exist in the configured include paths).

You might fix this by breaking down those Find scripts into two, that configure the separate paths, or by duplicating some code inside the modules to configure the separate paths by different names. Change the name of the header file to be looked for appropriately for each dir.
