### ISSUE TITLE
Implement config screen support for string, list and path input.

### ISSUE THREAD

**Issue by Tronic** [performous/performous#5]
Various options still need to be configured via XML file. Provide GUI support for modifying these in-game.

**Comment by Baklap4** [comment]
Are there currently options which are not available through the UI?
IMHO this can be closed whenever !227 is closed. Any objections? @performous/contributors

**Comment by Baklap4** [comment]
@performous/contributors  Closing this due to inactiveness.
Please reopen if you think an option is not in UI yet.
