### ISSUE TITLE
Building without webserver support, still shows menu entry

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#517]
### Do you want to request a *feature* or report a *bug*?

Bug

I've just installed a new version of debian, and installed the bare minimum dependencies using:
```
sudo apt install git cmake build-essential gettext help2man libopenblas-dev libfftw3-dev libicu-dev libepoxy-dev libsdl2-dev libfreetype6-dev libpango1.0-dev librsvg2-dev libxml++2.6-dev libavcodec-dev libavformat-dev libswscale-dev libjpeg-dev portaudio19-dev libglm-dev libboost-all-dev
```
This results in a build where webserver support is not supported since cpprestsdk is not found.

However in the menu i can still disable/enable the webserver (it does nothing though)

### What did you expect to see?

I didnt expect to see webserver features in game.

### What did you see instead?

I saw webserver features in game.

### Output of `performous --version`: (_What version of Performous are you using?_)

Latest master

### What is your environment & configuration (arguments, platform, ...)?

Debian 10

**Comment by Lord-Kamina** [comment]
This should be easy to fix, it's probably a bug in the CMakeLists.txt

**Comment by Baklap4** [comment]
### Todo

- [ ] Wait for #545 OR
- [ ] Fix menu by checking `USE_WEBSERVER`

**Comment by Baklap4** [comment]
With the current (2022-05-17) state of #766 the webserver becomes part of the core system and thus invalidating this issue.

**Comment by Baklap4** [comment]
Still happening as of 26-11-2023. Let's fix this the easy way by checking `USE_WEBSERVER`
