### ISSUE TITLE
Rename Player class to Singer

### ISSUE THREAD

**Issue by allcreater** [performous/performous#543]
### Do you want to request a *feature* or report a *bug*?

Refactoring

### What did you expect to see?

Rename **Player** class (at game/player.hh) and related filenames  to more descriptive name **Singer**

**Comment by Baklap4** [comment]
Problem with this is that performous has more than just singers. We also support Drummers, Guitarists and Bassists. @twollgam You're more of refactoring, any advice or shall we close this one?

**Comment by twollgam** [comment]
Yes I think we should close the pr cause your arguments are right.
