### ISSUE TITLE
Problems at startup

### ISSUE THREAD

**Issue by Lehmeiers** [performous/performous#566]
When testing Performous, I got an error message that referred to a "/home/xxxxxx/.cache/performous/infolog.txt". this is the content:

```
logger / notice: Logging all notices, warnings and errors. Log file: /home/ralf/.cache/performous/infolog.txt
core / notice: Performous 1.1+ starting ...
Internationalization: Enabled
MIDI Hardware I / O: Enabled
Webcam support: Enabled
core / notice: Starting the audio subsystem (errors printed on the console may be ignored).
audio / error: Audio device 'dev = "USBMIC" mics = "blue, red"': No such device.
audio / error: Audio device 'dev = "Microphone" mics = "*"': No such device.
audio / error: Audio device 'out = 2': Device doesn't have enough output channels
opengl / error: Shader color: 0:11 (1): error: `in 'qualifier in declaration of` bogus' only valid for function parameters in GLSL 1.20

core / error: core.frag: Shader compile error.
More details might be available in "/home/xxxxxx/.cache/performous/infolog.txt".
If you think this is a bug in Performous, please report it at
https://github.com/performous/performous/issues
```

How do I get it to work?

**Comment by Baklap4** [comment]
We need a little bit more info about your system.
Can you give us an operating system, video card driver and the version or commit you use of performous?

**Comment by Lehmeiers** [comment]
inxi -Fxxxzo    
System:    Kernel: 4.19.138-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Xfce 4.14.2 tk: Gtk 3.24.20 
           info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:   Type: Desktop System: Dell product: OptiPlex 360 v: N/A serial: <filter> Chassis: type: 6 serial: <filter> 
           Mobo: Dell model: 0T656F v: A01 serial: <filter> BIOS: Dell v: A07 date: 06/18/2012 
CPU:       Topology: Dual Core model: Pentium E5200 bits: 64 type: MCP arch: Penryn rev: 6 L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 9973 
           Speed: 1874 MHz min/max: N/A Core speeds (MHz): 1: 1874 2: 1458 
Graphics:  Device-1: NVIDIA GT218 [GeForce 210] driver: nouveau v: kernel bus ID: 01:00.0 chip ID: 10de:0a65 
           Display: x11 server: X.Org 1.20.8 driver: nouveau unloaded: modesetting alternate: fbdev,nv,vesa 
           resolution: 1680x1050~60Hz s-dpi: 96 
           OpenGL: renderer: N/A v: N/A direct render: N/A 
Audio:     Device-1: Intel NM10/ICH7 Family High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           chip ID: 8086:27d8 
           Device-2: NVIDIA High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 chip ID: 10de:0be3 
           Device-3: Microsoft LifeCam HD-5000 type: USB driver: snd-usb-audio,uvcvideo bus ID: 2-1:2 chip ID: 045e:076d 
           Sound Server: ALSA v: k4.19.138-1-MANJARO 
Network:   Device-1: Broadcom and subsidiaries NetLink BCM5784M Gigabit Ethernet PCIe vendor: Dell driver: tg3 v: 3.137 
           port: dc80 bus ID: 02:00.0 chip ID: 14e4:1698 
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter driver: 8139too v: 0.9.28 port: cc00 
           bus ID: 03:00.0 chip ID: 10ec:8139 
           IF: enp3s0 state: down mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 513.58 GiB (55.1%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 QVO 1TB size: 931.51 GiB speed: <unknown> serial: <filter> rev: 2B6Q 
           scheme: MBR 
Partition: ID-1: / size: 287.37 GiB used: 51.59 GiB (18.0%) fs: ext4 dev: /dev/sda2 
           ID-2: /boot size: 975.9 MiB used: 145.1 MiB (14.9%) fs: ext4 dev: /dev/sda1 
           ID-3: /home size: 556.52 GiB used: 461.83 GiB (83.0%) fs: ext4 dev: /dev/sda3 
Swap:      ID-1: swap-1 type: partition size: 71.13 GiB used: 16.2 MiB (0.0%) priority: -2 dev: /dev/sda4 
Unmounted: Message: No unmounted partitions found. 
Sensors:   System Temperatures: cpu: 45.0 C mobo: N/A gpu: nouveau temp: 49 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 169 Uptime: 2h 13m Memory: 3.79 GiB used: 2.48 GiB (65.6%) Init: systemd v: 245 Compilers: gcc: 10.1.0 
           alt: 8/9 clang: 10.0.1 Packages: pacman: 2267 Shell: Bash v: 5.0.18 running in: yakuake inxi: 3.1.05

**Comment by Lehmeiers** [comment]
inxi -Fxxxzo    
System:    Kernel: 4.19.138-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Xfce 4.14.2 tk: Gtk 3.24.20 
           info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:   Type: Desktop System: Dell product: OptiPlex 360 v: N/A serial: <filter> Chassis: type: 6 serial: <filter> 
           Mobo: Dell model: 0T656F v: A01 serial: <filter> BIOS: Dell v: A07 date: 06/18/2012 
CPU:       Topology: Dual Core model: Pentium E5200 bits: 64 type: MCP arch: Penryn rev: 6 L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 9973 
           Speed: 1874 MHz min/max: N/A Core speeds (MHz): 1: 1874 2: 1458 
Graphics:  Device-1: NVIDIA GT218 [GeForce 210] driver: nouveau v: kernel bus ID: 01:00.0 chip ID: 10de:0a65 
           Display: x11 server: X.Org 1.20.8 driver: nouveau unloaded: modesetting alternate: fbdev,nv,vesa 
           resolution: 1680x1050~60Hz s-dpi: 96 
           OpenGL: renderer: N/A v: N/A direct render: N/A 
Audio:     Device-1: Intel NM10/ICH7 Family High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           chip ID: 8086:27d8 
           Device-2: NVIDIA High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 chip ID: 10de:0be3 
           Device-3: Microsoft LifeCam HD-5000 type: USB driver: snd-usb-audio,uvcvideo bus ID: 2-1:2 chip ID: 045e:076d 
           Sound Server: ALSA v: k4.19.138-1-MANJARO 
Network:   Device-1: Broadcom and subsidiaries NetLink BCM5784M Gigabit Ethernet PCIe vendor: Dell driver: tg3 v: 3.137 
           port: dc80 bus ID: 02:00.0 chip ID: 14e4:1698 
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter driver: 8139too v: 0.9.28 port: cc00 
           bus ID: 03:00.0 chip ID: 10ec:8139 
           IF: enp3s0 state: down mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 513.58 GiB (55.1%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 QVO 1TB size: 931.51 GiB speed: <unknown> serial: <filter> rev: 2B6Q 
           scheme: MBR 
Partition: ID-1: / size: 287.37 GiB used: 51.59 GiB (18.0%) fs: ext4 dev: /dev/sda2 
           ID-2: /boot size: 975.9 MiB used: 145.1 MiB (14.9%) fs: ext4 dev: /dev/sda1 
           ID-3: /home size: 556.52 GiB used: 461.83 GiB (83.0%) fs: ext4 dev: /dev/sda3 
Swap:      ID-1: swap-1 type: partition size: 71.13 GiB used: 16.2 MiB (0.0%) priority: -2 dev: /dev/sda4 
Unmounted: Message: No unmounted partitions found. 
Sensors:   System Temperatures: cpu: 45.0 C mobo: N/A gpu: nouveau temp: 49 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 169 Uptime: 2h 13m Memory: 3.79 GiB used: 2.48 GiB (65.6%) Init: systemd v: 245 Compilers: gcc: 10.1.0 
           alt: 8/9 clang: 10.0.1 Packages: pacman: 2267 Shell: Bash v: 5.0.18 running in: yakuake inxi: 3.1.05

**Comment by Lehmeiers** [comment]
`` inxi -Fxxxzo    
System:    Kernel: 4.19.138-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.1.0 Desktop: Xfce 4.14.2 tk: Gtk 3.24.20 
           info: xfce4-panel wm: xfwm4 dm: LightDM 1.30.0 Distro: Manjaro Linux 
Machine:   Type: Desktop System: Dell product: OptiPlex 360 v: N/A serial: <filter> Chassis: type: 6 serial: <filter> 
           Mobo: Dell model: 0T656F v: A01 serial: <filter> BIOS: Dell v: A07 date: 06/18/2012 
CPU:       Topology: Dual Core model: Pentium E5200 bits: 64 type: MCP arch: Penryn rev: 6 L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 9973 
           Speed: 1874 MHz min/max: N/A Core speeds (MHz): 1: 1874 2: 1458 
Graphics:  Device-1: NVIDIA GT218 [GeForce 210] driver: nouveau v: kernel bus ID: 01:00.0 chip ID: 10de:0a65 
           Display: x11 server: X.Org 1.20.8 driver: nouveau unloaded: modesetting alternate: fbdev,nv,vesa 
           resolution: 1680x1050~60Hz s-dpi: 96 
           OpenGL: renderer: N/A v: N/A direct render: N/A 
Audio:     Device-1: Intel NM10/ICH7 Family High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           chip ID: 8086:27d8 
           Device-2: NVIDIA High Definition Audio driver: snd_hda_intel v: kernel bus ID: 01:00.1 chip ID: 10de:0be3 
           Device-3: Microsoft LifeCam HD-5000 type: USB driver: snd-usb-audio,uvcvideo bus ID: 2-1:2 chip ID: 045e:076d 
           Sound Server: ALSA v: k4.19.138-1-MANJARO 
Network:   Device-1: Broadcom and subsidiaries NetLink BCM5784M Gigabit Ethernet PCIe vendor: Dell driver: tg3 v: 3.137 
           port: dc80 bus ID: 02:00.0 chip ID: 14e4:1698 
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter driver: 8139too v: 0.9.28 port: cc00 
           bus ID: 03:00.0 chip ID: 10ec:8139 
           IF: enp3s0 state: down mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 513.58 GiB (55.1%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 QVO 1TB size: 931.51 GiB speed: <unknown> serial: <filter> rev: 2B6Q 
           scheme: MBR 
Partition: ID-1: / size: 287.37 GiB used: 51.59 GiB (18.0%) fs: ext4 dev: /dev/sda2 
           ID-2: /boot size: 975.9 MiB used: 145.1 MiB (14.9%) fs: ext4 dev: /dev/sda1 
           ID-3: /home size: 556.52 GiB used: 461.83 GiB (83.0%) fs: ext4 dev: /dev/sda3 
Swap:      ID-1: swap-1 type: partition size: 71.13 GiB used: 16.2 MiB (0.0%) priority: -2 dev: /dev/sda4 
Unmounted: Message: No unmounted partitions found. 
Sensors:   System Temperatures: cpu: 45.0 C mobo: N/A gpu: nouveau temp: 49 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 169 Uptime: 2h 13m Memory: 3.79 GiB used: 2.48 GiB (65.6%) Init: systemd v: 245 Compilers: gcc: 10.1.0 
           alt: 8/9 clang: 10.0.1 Packages: pacman: 2267 Shell: Bash v: 5.0.18 running in: yakuake inxi: 3.1.05``

**Comment by Tronic** [comment]
GLSL version incompatibility in shader code, I think. Probably nouveau drivers come with stricter compiler that picks this up. Official Nvidia drivers allow all kinds of bugs to slip through.

The `bogus` variable in our shaders was used to workaround a Nvidia driver bug about 10 years ago, and should no longer be necessary at all. I suggest removing the variable, and if necessary, fix the qualifiers and version statements of all shaders to match with modern GLSL versions. @Baklap4 if you are familiar with GLSL, I suggest you do it.

**Comment by Baklap4** [comment]
I'm not quite familier with GLSL, @OznOg any experience you have?

**Comment by Lord-Kamina** [comment]
> I'm not quite familier with GLSL, @OznOg any experience you have?

This is with 1.1 most likely. `bogus` has indeed long since been excised from master.

**Comment by OznOg** [comment]
> I'm not quite familier with GLSL, @OznOg any experience you have?

Nop, sorry, not at all

**Comment by Baklap4** [comment]
Closing this since the `bogus` variable isn't used anymore in 1.2.0

If the issue still persists please reopen this issue.
