### ISSUE TITLE
Ideas for multi player singing game modes

### ISSUE THREAD

**Issue by twollgam** [performous/performous#572]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to implement some multi player game modes. So this issue is for collecting and discussing ideas.

**Comment by Baklap4** [comment]
What kind of multi-player modes?
As of currently singing, guitar hero are already multiplayer?

**Comment by twollgam** [comment]
Oh sorry, I will be more concrete. In the original Singstar the are modes like "pass the micro". I think  those modes are not implemented actual.

**Comment by Baklap4** [comment]
I've converted this to a discussion. Let's discuss over there
