### ISSUE TITLE
performous does not react to keyboard input

### ISSUE THREAD

**Issue by retorquere** [performous/performous#579]
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I've installed performous on a windows 10 tablet/laptop (acer switch 10), but it doesn't react to the keyboard, neither the physical keyboard or the on-screen keyboard. The keyboard (hardware and on-screen) works in all other applications, and if I plug in an USB keyboard, performous does react.

### What did you expect to see?

I expected there to be no difference between a usb keyboard and the internal keyboard

### What did you see instead?

the usb keyboard works, the internal keyboard (physical nor on-screen) work

### Output of `performous --version`: (_What version of Performous are you using?_)

`performous --version` doesn't output anything, but the title bar says 1.1

### What is your environment & configuration (arguments, platform, ...)?

Windows 10 32 bit, no arguments, I start with the icon.

**Comment by Baklap4** [comment]
@retorquere Windows has been quite buggy ever since the last official release since we crosscompile that. Recently we've managed to create a native build (#650) can you give that a try?

>Github won't let me upload the full executable + dll's since it's too big. I've uploaded it to our discord and can be downloaded from here: https://cdn.discordapp.com/attachments/864212458612064338/874758624990351431/Performous-x64-Debug.zip
SHA512 sum is: ab37c2e58c145dae8ba31cee5bbcfdc03a07ef0b15675d8d4d8b03d8ee0289cc91cf4e73f1ed05c227849a9e3ebacd78612b3a4e1f67966482dab6c9e0494bf3

**Comment by retorquere** [comment]
Hi, I appreciate the effort, but I've switched to Mac since.

**Comment by Baklap4** [comment]
Awhh alright. Then once #650 is merged i'm gonna autoclose this issue, thanks for the headsup
