### ISSUE TITLE
Wrong shortcuts in wiki

### ISSUE THREAD

**Issue by ikcalB** [performous/performous#581]
Bug

### What did you do?
Tried the shortcuts to adjust delays from the [wiki](https://github.com/performous/performous/wiki/Keys#Performing).
These did not work.

i.e.: `Ctrl+F3/F4` to adjust round-trip latency

### What did you expect to see?
adjusted round-trip delay

### What did you see instead?
nothing.

### Output of `performous --version`: (_What version of Performous are you using?_)
1.1-941-g57ad2fc7

### What is your environment & configuration (arguments, platform, ...)?
linux, compiled from master using Cmake.

I've looked into the sources ( [screen_singing.cc](https://github.com/performous/performous/blob/57ad2fc71f625a432f5e82b15bcf44081a29e8f8/game/screen_sing.cc#L410) ), and found that other shortcuts were actually used than mentioned in the wiki.

i.e. round trip delay: `Ctrl+-`, `Ctrl+=`

**Comment by Baklap4** [comment]
Documentation is currently out of date:
https://github.com/performous/performous/pull/511/files
This was merged some time ago to update the language files to have the correct shortcuts in game.

**Comment by Baklap4** [comment]
Documentation is fixed: https://github.com/performous/performous/wiki/Keys/_compare/f7ead9b0ddfd6e26381c5cb575206d53fd5a44ef...d1858d32da1031a65af957deaae7af5cfe6adc49
