### ISSUE TITLE
Provide a "quickstart" for creating a theme

### ISSUE THREAD

**Issue by brianredbeard** [performous/performous#582]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Presently in the wiki, there is a long outdated document named [Theming](../wiki/Theming/).  This issue is to track updating the page with a "quickstart" guide as well as to provide a mechanism for embedding images in a way that does not pollute the source respository nor having the files hosted on a third party service (which increase the likelihood of 404s to the images in the future).

I am about to write this guide and when completed will close this issue.  I don't expect this to take more than 24 hours.

**Comment by brianredbeard** [comment]
Screenshot of warning from Inkscape when opening default theme files:

![inkscape-update-dialog](https://user-images.githubusercontent.com/57542/105615738-ad09c980-5d87-11eb-9d10-da730a0d1cc9.png)

**Comment by brianredbeard** [comment]
Images used throughout the tutorial


![inkscape-glyph-align](https://user-images.githubusercontent.com/57542/105622997-0f37ee00-5dcb-11eb-9d15-44a9977c608a.png)

![inkscape-glyph-bug1](https://user-images.githubusercontent.com/57542/105623004-19f28300-5dcb-11eb-8eb8-f80c3de06eb3.png)

![inkscape-glyph-bug2](https://user-images.githubusercontent.com/57542/105623005-1d860a00-5dcb-11eb-9bc9-1adf9eb881e4.png)

![inkscape-glyph-paste](https://user-images.githubusercontent.com/57542/105623009-21b22780-5dcb-11eb-99a6-cf1d6629bd88.png)

![inkscape-glyph-resize](https://user-images.githubusercontent.com/57542/105623013-25de4500-5dcb-11eb-8f28-5ebcc879a96d.png)

![inkscape-glyph-transform](https://user-images.githubusercontent.com/57542/105623015-2b3b8f80-5dcb-11eb-89af-7650d45a2535.png)

![inkscape-gray-gradient](https://user-images.githubusercontent.com/57542/105623020-3098da00-5dcb-11eb-83c3-aefaf0fb7812.png)

![inkscape-gray-gradient-complete](https://user-images.githubusercontent.com/57542/105623023-37275180-5dcb-11eb-907d-ca27846194a7.png)


![inkscape-gray-shadow](https://user-images.githubusercontent.com/57542/105623025-3bec0580-5dcb-11eb-9d3d-5c5737c45038.png)

![inkscape-intro_configure](https://user-images.githubusercontent.com/57542/105623028-3ee6f600-5dcb-11eb-905a-49f02ad2731e.png)

![inkscape-settings](https://user-images.githubusercontent.com/57542/105623031-427a7d00-5dcb-11eb-8fe3-e3c5132c5cb5.png)

![inkscape-ungroup](https://user-images.githubusercontent.com/57542/105623032-45756d80-5dcb-11eb-8a1d-d0a89592a2bb.png)

![inkscape-xy-coords](https://user-images.githubusercontent.com/57542/105623035-4908f480-5dcb-11eb-8846-cb2ab1098313.png)

**Comment by brianredbeard** [comment]
OK, major update should be good to go.  I'll leave this open for a few days so that folks can hail me if there are any major problems to be fixed.  If it's just something like typos, by all means edit away!

**Comment by brianredbeard** [comment]
Perfect.  So let it be said, so let it be done.

**Comment by Baklap4** [comment]
Thanks for updating the page!
