### ISSUE TITLE
Phase out IRC

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#584]
Currently Discord and the IRC channel on freenode are living aside eachother. We do have an integration in Discord to relay messages to IRC and back to discord.
However I think we should get rid of IRC in general as a platform.
My main reason for this is:

1. Discord provides a better way to interact with eachother
2. Even relaying the messages and be able to chat in discord to the IRC is proven to not quite work as we response too late and the person might be gone by then.
3. Discord saves the messages so you can reply at a later point in time.
4. A better single way of communication instead of 2 ways of which one (IRC) is poorly active.

Let's discuss and get to a solution.
If you don't have anything to say react with a 🎉   if you agree on phasing out IRC.

**Comment by jose1711** [comment]
How many people do we see coming to IRC and raising questions/discussing performous per - say - a month? I love freedom of choice and for instance I see no active (maintained) Discord client for terminal but perhaps it's a waste of resources to keep it up for just a couple folks.

**Comment by Baklap4** [comment]
per month we see about  less than 1 user. Mostly starting with 'hello' and then waiting for response which most likely will be way later if at all. By then the user is probably already gone.

**Comment by heyimyunyl** [comment]
@Baklap4 do you have a discord? if you do, can you give it to me? i want to talk with you about an important topic.

**Comment by bcmpinc** [comment]
The website still links to IRC using freenode webchat, but does not contain a link to the discord. Changing that might reduce the number of visitors in IRC to 0.

**Comment by Tronic** [comment]
IRC is dead, should be replaced by Matrix, if anything, and one can also connect Discord via Matrix.

**Comment by loquesangra** [comment]
> per month we see about less than 1 user. Mostly starting with 'hello' and then waiting for response which most likely will be way later if at all. By then the user is probably already gone.
Well that's just bad IRC etiquette, lol
> How many people do we see coming to IRC and raising questions/discussing performous per - say - a month? I love freedom of choice and for instance I see no active (maintained) Discord client for terminal but perhaps it's a waste of resources to keep it up for just a couple folks.
A waste of resources? are you paying money to bridge?

Also, as much as I love XMPP as the next guy you should keep IRC around. It's still the most accessible chat protocol ever. Not everyone has a Discord account (and doesn't want to) believe it or not.

**Comment by loquesangra** [comment]
https://spywarewatchdog.org/articles/discord.html

https://github.com/libremonde-org/paper-research-privacy-matrix.org

Monopolies and centralization are bad, even moreso as an Internet communication model.

**Comment by Tronic** [comment]
> https://github.com/libremonde-org/paper-research-privacy-matrix.org

The article says that Matrix sends a lot of data to matrix.org and vector.im. This is mostly not true (anymore) as default settings are not to send any to them. Vector.im is basically a phone book that can be used for finding user's account from another server (if you don't know their homeserver address), and one has to opt in to be included. Most channels are hosted at matrix.org so in that regard it gets connected but in that regard it is no different from IRC where all servers know everything. However, Matrix does support and enable E2E encryption by default, while everything on IRC remains plain unencrypted text.

To be honest, IRC is very cryptic to connect and hard to use, especially for persistent connections (not everyone has a tmux+irssi server setup, LOL). Web IRC users close the page and go offline before anyone can reply, so there's that.

**Comment by Baklap4** [comment]
Personally i'd love to have _**one**_ channel to interact with people. Adding for example Matrix probs result into 'just another irc' whilst at discord we already have a community.

Glad we're agreeing that IRC is dead. The suggestion of @bcmpinc seems reasonable: remove the irc link and replace it (for now) with the Discord invite link so we reduce the traffic to the IRC on freenode.

@Tronic why would you suggest Matrix over Discord?

**Comment by Tronic** [comment]
@Baklap4 Matrix provides Discord bridging, which I suggest you to enable (as Discord channel admin):
https://matrix.org/docs/projects/bridge/matrix-appservice-discord

Because it interfaces with all other IM (including IRC) and does that in a technologically superior way (distributed, encrypted, good apps, requires only one account on my home server even if channels are on other servers), I prefer to use it rather than register accounts at others.
