### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Git-Forked** [performous/performous#588]
[CMakeError.log](https://github.com/performous/performous/files/6505082/CMakeError.log)
[CMakeOutput.log](https://github.com/performous/performous/files/6505083/CMakeOutput.log)

**Comment by Git-Forked** [comment]
Trying to build on Manjaro (based on Arch).

**Comment by OznOg** [comment]
could you try the following patch and let me know if it can fix your issue?
```

diff --git a/game/CMakeLists.txt b/game/CMakeLists.txt
index 9f8159c8..68011e96 100644
--- a/game/CMakeLists.txt
+++ b/game/CMakeLists.txt
@@ -147,9 +147,8 @@ else()
 endif()
 
 if(UNIX AND NOT APPLE)
-       # Note: cannot use list APPEND here because it inserts semicolons instead of spaces
-       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
-       set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread")
+        find_package(Threads)
+        target_link_libraries(performous Threads::Threads)
 endif()
 
 if(WIN32)

```

**Comment by OznOg** [comment]
@Git-Forked have you been able to test my patch?

**Comment by Git-Forked** [comment]
Sorry, no idea how to do that.

**Comment by Baklap4** [comment]
Save the mentioned code to a file let's call it `patch`, then use git to apply it: `git apply ./patch`

**Comment by OznOg** [comment]
BTW I wonder if the "IF NOT APPLE" remains useful: I guess threads are required for mac also, and I expect cmake to give unified use of them.

**Comment by OznOg** [comment]
@Git-Forked you may try branch OznOg:devel/fix_some_warnings pointed in mr #589 if it is ieasier for you.

**Comment by Baklap4** [comment]
This should be fixed on current master because of . Can you try to give this a test @Git-Forked ?

For now i'm closing it, but if you still run into issues please reopen the issue.
