### ISSUE TITLE
Diagnostics command line option

### ISSUE THREAD

**Issue by deuteragenie** [performous/performous#639]
- The app could benefit from a diagnostics command line option (ie performous -diag or similar), which would essentially list whatever is discovered in terms of dependencies, opengl, audio devices etc., then quits properly.
- This could be useful for end users issue reporting, but also for CI for example to ensure basic functions are OK after building.
- It is essentially the same information that should be displayed as the one that is currently displayed in the logs upon nominal start.

**Comment by Baklap4** [comment]
> The app could benefit from a diagnostics command line option (ie performous -diag or similar), which would essentially list whatever is discovered in terms of dependencies, opengl, audio devices etc., then quits properly.

We already have this partly for audio with using `performous --audiohelp` also `performous --log=debug` gives a lot of info too.

> This could be useful for end users issue reporting

Agreed in regard of dependency versions.

We also have `performous --version` i think to show us the current version (stable or git commit) of performous which is used

**Comment by Baklap4** [comment]
Closing this issue for a couple of reasons:

- We have `--version` to show the currently used version of performous
    - We know with what binaries and such this specific build is produced.
- A lot of these diagnostics info is found within the Debug log (`performous --log=debug`)
- If someone wants to build from code, we have the GH Workflow for a vast amount of OS'ses which can be used as a guideline on building. If they do somehow have an exotic build structure it most likely is a very small percentage of people.
    - Besides ppl who build from scratch probably know what they're doing anyway
- We currently have some unittests and more to be added within the project to ensure certain stuff is working.
