### ISSUE TITLE
Picking still taken in account when other player's menu is opened

### ISSUE THREAD

**Issue by karamel59** [performous/performous#64]
When you are playing a song and an other player opens its menu the game is paused but you can still pick notes and kill your score. All wrong notes are played at once when the game resumes.

**Comment by Baklap4** [comment]
@Tronic is this still an issue with current master? If not can you close this bug?

**Comment by Tronic** [comment]
Hmm, this is quite ancient and I haven't got any guitar hero controllers anymore. Closing because it doesn't seem to bother anyone else and quite likely someone already fixed it.
