### ISSUE TITLE
Deb artifact creation broken due to conflict ffmpeg/icu/opencv

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#660]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

We merged #656 this lead to working pipelines but breaking the building of our artifacts.

### Output of CI log

```
/usr/bin/ld: warning: libavcodec.so.57, needed by /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2.0, may conflict with libavcodec.so.58 06:11
/usr/bin/ld: warning: libavformat.so.57, needed by /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2.0, may conflict with libavformat.so.58 06:11
/usr/bin/ld: warning: libavutil.so.55, needed by /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2.0, may conflict with libavutil.so.56 06:11
/usr/bin/ld: warning: libswscale.so.4, needed by /usr/lib/x86_64-linux-gnu/libopencv_videoio.so.3.2.0, may conflict with libswscale.so.5 06:11
/usr/bin/ld: warning: libicuuc.so.60, needed by /usr/lib/x86_64-linux-gnu/libxml2.so, may conflict with libicuuc.so.63 06:11
/usr/bin/ld: warning: libswresample.so.2, needed by //usr/lib/x86_64-linux-gnu/libavcodec.so.57, may conflict with libswresample.so.3
```

### What is your environment & configuration (arguments, platform, ...)?

CI - Ubuntu 1804 with  `ppa:litenstein/performous-bionic` ppa installed.

### TODO

- [ ] Fix the artifact building by building the correct version of ffmpeg and icu

**Comment by Baklap4** [comment]
@Lord-Kamina I saw you made a new ppa for bionic. Is that ppa ready to use?

**Comment by Lord-Kamina** [comment]
> @Lord-Kamina I saw you made a new ppa for bionic. Is that ppa ready to use?

Not yet. Currently libdsl2 is broken (not sure why) and so I haven't been able to build ffmpeg.

**Comment by Baklap4** [comment]
Give me a heads up if i can try it out sometime later :+1:
