### ISSUE TITLE
Add support for enum translation

### ISSUE THREAD

**Issue by twollgam** [performous/performous#679]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The file schema.xml contains mappings from text to integer. The description of every item resists inside an "enum" xml tag. All those descriptions are english and while the is no translation yet they are displayed in english even if all other texts are displayed in another language.

Tasks:

- [x] Implement i18n support for enum
- [ ] Implement i18n support for stringvalue
- [x] Extend the xml_gettext.py that it extracts the enum-tags from schema.xml 
- [ ] Extend the xml_gettext.py that it extracts the  stringvalue-tags from schema.xml 
- [x] Add example translation

**Comment by Baklap4** [comment]
Can you verify that strings in a stringlist and/or optionlist are translatable? if not they should be added too.

**Comment by twollgam** [comment]
@Baklap4 the stringvalue tag is rarely used in schema.xml and I did not find them in the configuration screens.  Only I found "Word collation" but that did not work (anymore). It displays < 6 items >. That is not what I expect.

**Comment by Lord-Kamina** [comment]
> @Baklap4 the stringvalue tag is rarely used in schema.xml and I did not find them in the configuration screens. Only I found "Word collation" but that did not work (anymore). It displays < 6 items >. That is not what I expect.

Word collation is working as expected (It's the list of words that are ignored for sorting purposes, such as "The", "A" and such) but the interface does not allow directly editing a stringlist.
