### ISSUE TITLE
Pango warning: Couldn't load font droid sans mono bolt not rotated

### ISSUE THREAD

**Issue by Baklap4** [performous/performous#690]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Some people saw pango warnings. With the message "Couldn't load font droid sans mono bolt not rotated" 
I've looked into it but couldn't reproduce this myself and all the fonts on windows/linux work on my side

### What did you expect to see?

No warnings

### What did you see instead?

The above mentioned warning

### Output of `performous --version`: (_What version of Performous are you using?_)

Performous 1.2.0-rc1

### What is your environment & configuration (arguments, platform, ...)?

Windows/Linux

**Comment by Baklap4** [comment]
Not seeing this warning anymore. @Lord-Kamina @ooshlablu do you guys still see this warning with latest master? If yes then please reopen this

**Comment by Lord-Kamina** [comment]
I don't think I've ever seen it hahahaha
