### ISSUE TITLE
Windows-Setup for 1.2 has issues

### ISSUE THREAD

**Issue by twollgam** [performous/performous#704]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I install the official setup 1.2 on Windows 10. In the licence dialog there is an out of date message.

### What did you expect to see?
```
Performous is
   Copyright (C) 2006-2022 The Performous Team
```

### What did you see instead?
```
Performous is
   Copyright (C) 2006-2016 The Performous Team
```

**Comment by Baklap4** [comment]
@twollgam with #706 this should be fixed. This is also a 'bug' for other platforms
