### ISSUE TITLE
Audio fails after a while with "underrun occurred" being flooded on console

### ISSUE THREAD

**Issue by Tronic** [performous/performous#71]
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred

I can start Performous and play for about one minute before the audio time (song position) starts moving forward much faster than it should and some very noisy unrecognizable audio comes out. The audio is not skipping blocks or playing too fast, it is just garbage. This is most likely PulseAudio or ALSA bug that gets triggered by Performous' attempt to use shorter audio buffers than typical apps do.

Workaround: increase the suggested latency setting in Performous if you are having this problem.

A bug should probably be reported upstream about incorrect underrun handling (which appears to be the problem here) but we should first make very sure that there are no bugs with that in Performous itself.

**Comment by nieknooijens** [comment]
I can still trigger this bug when overloading my CPU while running performous (for example, compiling MXE on 12 threads when running performous) but I never encountered underrruns in normal use.

**Comment by Baklap4** [comment]
@Tronic do you still have this issue?
As @nieknooijens says we can only trigger this when the cpu is running out of clockcycles..

**Comment by Tronic** [comment]
I switched to Mac and thus don't have any Linux machines or audio troubles anymore, so I'll boldly consider this issue closed.
