### ISSUE TITLE
Build fails in 2014-01-07-wheezy-raspbian

### ISSUE THREAD

**Issue by wellumies** [performous/performous#76]
Building from source fails in Rasbian

[ 43%] Building CXX object game/CMakeFiles/performous.dir/color.cc.o
In file included from /opt/performous/performous/game/surface.hh:3:0,
                 from /opt/performous/performous/game/opengl_text.hh:4,
                 from /opt/performous/performous/game/opengl_text.cc:1:
/opt/performous/performous/game/glutil.hh:32:18: sorry, unimplemented: non-static data member initializers
/opt/performous/performous/game/glutil.hh:32:18: error: ISO C++ forbids in-class initialization of non-const static member âm_vboâ
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [game/CMakeFiles/performous.dir/songparser-mid.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....
In file included from /opt/performous/performous/game/surface.hh:3:0,
                 from /opt/performous/performous/game/opengl_text.hh:4,
                 from /opt/performous/performous/game/screen.hh:6,
                 from /opt/performous/performous/game/screen_intro.hh:3,
                 from /opt/performous/performous/game/screen_intro.cc:1:
/opt/performous/performous/game/glutil.hh:32:18: sorry, unimplemented: non-static data member initializers
/opt/performous/performous/game/glutil.hh:32:18: error: ISO C++ forbids in-class initialization of non-const static member âm_vboâ
In file included from /opt/performous/performous/game/surface.hh:3:0,
                 from /opt/performous/performous/game/ffmpeg.hh:3,
                 from /opt/performous/performous/game/audio.hh:7,
                 from /opt/performous/performous/game/audio.cc:1:
/opt/performous/performous/game/glutil.hh:32:18: sorry, unimplemented: non-static data member initializers
/opt/performous/performous/game/glutil.hh:32:18: error: ISO C++ forbids in-class initialization of non-const static member âm_vboâ
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make[2]: *** [game/CMakeFiles/performous.dir/screen_intro.cc.o] Error 4
Linking CXX executable ss_ipu_conv
[ 43%] Built target ss_ipu_conv
make[2]: *** [game/CMakeFiles/performous.dir/opengl_text.cc.o] Error 1

*************

In file included from /opt/performous/performous/game/audio.hh:14:0,
                 from /opt/performous/performous/game/audio.cc:1:
/opt/performous/performous/game/libda/portaudio.hpp: In constructor âportaudio::Stream::Stream(Functor&, const PaStreamParameters*, const PaStreamParameters*, double, long unsigned int, PaStreamFlags) [with Functor = Device, PaStreamParameters = PaStreamParameters, PaStreamFlags = long unsigned int]â:
/opt/performous/performous/game/audio.cc:392:10:   instantiated from here
/opt/performous/performous/game/libda/portaudio.hpp:168:115: error: type âportaudio::Streamâ is not a direct base of âportaudio::Streamâ
make[2]: *** [game/CMakeFiles/performous.dir/audio.cc.o] Error 1
make[1]: *** [game/CMakeFiles/performous.dir/all] Error 2
make: *** [all] Error 2
pi@karaoke /opt/performous/performous $ uname -a
Linux karaoke 3.10.25+ #622 PREEMPT Fri Jan 3 18:41:00 GMT 2014 armv6l GNU/Linux

**Comment by nieknooijens** [comment]
the EGL branch is originally created by tapio, and was discontinued because the raspberry had too little RAM to actually run performous at a decent rate. Tobias has ported performous to libepoxy for EGL support, although that hasn't been fully tested yet, I think that's the way to go, so therefore i'm closing this issue.
