### ISSUE TITLE
performous 1.2 crashes on start

### ISSUE THREAD

**Issue by marcoSchr** [performous/performous#778]
### Performous & operating system versions

Performous: 1.2.0-1
OS: Arch Linux

### What is the problem?

Performous crashes when run

### Steps to reproduce

1. run performous

### Additional context

I have rebuild the package with debug symbols and added the stack trace from gdb.

### Log(s) & preferences file(s)

[infolog.txt](https://github.com/performous/performous/files/8852299/infolog.txt)
[gdb.log](https://github.com/performous/performous/files/8852301/gdb.log)

**Comment by ooshlablu** [comment]
We have had users report success in running the AppImage on from the latest master build report success when running on Arch, even on a Steam Deck: https://nightly.link/performous/performous/workflows/build_and_release/master/Performous-latest.AppImage.zip

**Comment by Lord-Kamina** [comment]
Looks like the LANG issue. Make sure LANG is set to something that makes sense.

**Comment by OznOg** [comment]
looks like the fedora 32 bug we had on std::regex maybe the library is not uptodate on your system are you sure you have the patch for https://github.com/boostorg/locale/issues/52 on you system?
