### ISSUE TITLE
The app doesn't exit while songs are being loaded

### ISSUE THREAD

**Issue by Tronic** [performous/performous#783]
### Performous & operating system versions

Git master

### What is the problem?

Quiting the application while song loading is in progress closes the window but keeps playing music. The application only exits once the song loading is complete, which can take considerable time.

### Steps to reproduce

1. Add a large collection of songs
2. Ctrl-Q, close the window or hit Quit on menu
3. The window closes but menu music or other sounds keep playing, the process won't exit unless kill -9'd, app stays visible in MacOS task switcher
4. After a while the app closes

### Additional context

The song loader thread should be interrupted immediately (I believe there is a quit flag for this and I think it has worked before but for some reason this is now broken).

**Comment by ooshlablu** [comment]
I have noticed this issue as well, and it has been mentioned in Discord a few times by others.

**Comment by OznOg** [comment]
fix in #784
