### ISSUE TITLE
Fontconfig error making fallback not work

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#799]
### Performous & operating system versions

Performous: Master
OS: macOS Big Sur

### What is the problem?

There's a bug with the font-fallback on macOS (and possibly Windows), due to a possibly ambiguous <dir> entry

### Additional context

This issue is just a reminder to myself so I don't forget to fix it later.

**Comment by Baklap4** [comment]
is this (partially?) solved by #824 ?

**Comment by Lord-Kamina** [comment]
No. Actually, this was actually two entirely separate issues that should already be fixed as part of #798
