### ISSUE TITLE
Cannot Mute Vocal Track

### ISSUE THREAD

**Issue by Cossey** [performous/performous#811]
### Performous & operating system versions

Performous: 1.2.0
Operating System: Windows 10 Pro 21H1

### What is the problem?

According to this [page](https://github.com/performous/performous/wiki/Real-karaoke) you should be able to mute the vocal track. I am unable to mute any of the vocal tracks for the songs that have them. Additionally, I cannot find the scripts mentioned at the above page in the install directory.

### Steps to reproduce

Start a song (music.ogg) that has a separate vocal track (vocals.ogg).
Try to press CTRL+V or CTRL+SHIFT+V.
Vocal Track does not mute.

### Additional context

It would be great to have a setting that automatically disables the vocal track (or have this automatically off for Karaoke mode) or if it could work like SingStar, where if it detects someone singing, to lower the volume of the vocal track.

### Log(s) & preferences file(s)

[infolog.txt](https://github.com/performous/performous/files/9355981/infolog.txt)
[config.xml.txt](https://github.com/performous/performous/files/9355987/config.xml.txt)

**Comment by Baklap4** [comment]
As i'm looking towards the code i can see the shortcut being mentioned: https://github.com/performous/performous/blob/master/game/screen_sing.cc#L395

This should call the fade method with 1 or 0 depending if it's going to get muted or not.

Are you sure it isn't working?

I have one song made as this, but here all the different parts of the songs (drums, guitar, vocals, music) have a little bit of voice still in them so it's not completely muted.

Can you share a song which should work alright?

**Comment by Baklap4** [comment]
Seems you were right with this issue!

Just PR'ed a fix for it 👍 
I've also updated the wiki to say ctrl + v is now a toggle

**Comment by Baklap4** [comment]
@Cossey you can use the links within the readme to download the latest build. This includes this fix :) Soon ™ an official release will follow

**Comment by jamesbonifacio** [comment]
@Baklap4 Hi I think this fixed the vocal muting for the FoF songs (which was previously not working) but it is no longer working for the SingStar/UltraStar songs (this was previously working).  Can anyone else confirm?
