### ISSUE TITLE
Support for GH and RB style split drum tracks.

### ISSUE THREAD

**Issue by ghost** [performous/performous#84]
GH Method
drums_1.ogg - Kick Drum
drums_2.ogg - Snare Drum
drums_3.ogg - Cymbals
drums_4.ogg - Toms

RB Method
drums_1.ogg - Kick Drum
drums_2.ogg - Snare Drum
drums_3.ogg - Toms and Cymbals

**Comment by Mrrisikoguru** [comment]
Hi, I had the same problem. Additionaly I have also included the keys and crowd sounds if they exists. For everyone who looks for a workaround: Here my solution. All drum files combine into one drum file and the keys and crowd sounds are mixed into the song file.

At first you have to download SoX from http://sox.sourceforge.net/
and unzip it to C:\sox14\ (or you change the path in the following code).
Then you have to save the following code into a ****.bat file (windows) that you have to save in the folder were your songs are saved.
Make a backup of your songs.

```
for /f "delims=" %%i in ('dir /ad/s/b') do (
	cd %%i
	IF NOT EXIST drums.ogg (
		IF EXIST drums_1.ogg (
			C:\sox14\sox drums_1.ogg -c 2 -C 6 drums_1stereo.ogg
			IF EXIST drums_2.ogg (
				C:\sox14\sox drums_2.ogg -c 2 -C 6 drums_2stereo.ogg
				IF EXIST drums_3.ogg (
					C:\sox14\sox drums_3.ogg -c 2 -C 6 drums_3stereo.ogg
					IF EXIST drums_4.ogg (
						C:\sox14\sox drums_4.ogg -c 2 -C 6 drums_4stereo.ogg
						C:\sox14\sox -m drums_1stereo.ogg drums_2stereo.ogg drums_3stereo.ogg drums_4stereo.ogg -C 6 drums.ogg gain -n
					) ELSE (
						C:\sox14\sox -m drums_1stereo.ogg drums_2stereo.ogg drums_3stereo.ogg -C 6 drums.ogg gain -n
					)
				) ELSE (
					C:\sox14\sox -m drums_1stereo.ogg drums_2stereo.ogg -C 6 drums.ogg gain -n
				)
			) ELSE (
				C:\sox14\sox -m drums_1stereo.ogg -C 6 drums.ogg gain -n
			)
			del drums_?stereo.ogg
		)
	)
	IF EXIST song.ogg (
		ren song.ogg song_1.ogg
		IF EXIST crowd.ogg (
			C:\sox14\sox crowd.ogg -r 44100 -C 6 crowd_1.ogg
			IF EXIST keys.ogg (
				C:\sox14\sox -m song_1.ogg keys.ogg crowd_1.ogg -C 6 song.ogg gain -n
			) ELSE (
				C:\sox14\sox -m song_1.ogg crowd_1.ogg -C 6 song.ogg gain -n
			)
			del crowd_1.ogg
		)ELSE (
			IF EXIST keys.ogg (
				C:\sox14\sox -m song_1.ogg keys.ogg -C 6 song.ogg gain -n
			)
		)
		IF NOT EXIST song.ogg (
			ren song_1.ogg song.ogg
		)
	) ELSE (
		IF EXIST crowd.ogg (
			C:\sox14\sox crowd.ogg -r 44100 -C 6 crowd_1.ogg
			IF EXIST keys.ogg (
				C:\sox14\sox -m keys.ogg crowd_1.ogg -C 6 song.ogg gain -n
			) ELSE (
				C:\sox14\sox -m crowd_1.ogg -C 6 song.ogg gain -n
			)
			del crowd_1.ogg
		)ELSE (
			IF EXIST keys.ogg (
				C:\sox14\sox -m keys.ogg -C 6 song.ogg gain -n
			)
		)
	)
	IF EXIST song.ogg (
		IF NOT EXIST song_1.ogg (
			ren song.ogg song_1.ogg
			IF EXIST crowd.ogg (
				IF EXIST keys.ogg (
					C:\sox14\sox -m song_1.ogg keys.ogg crowd.ogg -C 6 song.ogg gain -n
				) ELSE (
					C:\sox14\sox -m song_1.ogg crowd.ogg -C 6 song.ogg gain -n
				)
			)ELSE (
				IF EXIST keys.ogg (
					C:\sox14\sox -m song_1.ogg keys.ogg -C 6 song.ogg gain -n
				)
			)
			IF NOT EXIST song.ogg (
				ren song_1.ogg song.ogg
			)
		)
	)
)
cd ..
```
Now you can start this bat with a double klick.

This bat goes into every Subfolder and do there what it has to do.
I think there were better solutions but it works.
The song_1 file is kept up. So you can undo this manipulation every time.

Now you can play with perfomous. If everything is working you can delete the backup.

**Comment by ggDropbear** [comment]
I'm currently running Linux, is there a way to merge split tracks using this method?

Alternatively, can we implement this feature so Performous is compatible with FoFiX/Phase Shift formats properly?
