### ISSUE TITLE
Performous theming won't allow font changes on "songs_song.svg" file; 

### ISSUE THREAD

**Issue by TulipKitten** [performous/performous#876]
### Performous & operating system versions

Performous 1.2.0
Windows 11

### What is the problem?

When you change the font of the text in the SVG file for the song label in the "Perform" window, the text goes invisible. This isn't supposed to happen. Changing the font in the SVG file usually changes the font in the game.

### Steps to reproduce

1. Go to "songs+song.svg" file in themes folder.
2. Change the font used and save changes.
3. Go into Performous and press enter on "Perform"

**Comment by Baklap4** [comment]
Might be a caching thing, can you clear the cache folder within `%appdata%/performous/cache`
Also if on Windows the font you refer to has to be installed and/or copied pasted in the font directory: C:/Program Files/Performous/Performous/fonts i suppose

**Comment by marwin89** [comment]
I faced the same issue with my theme in #920. But here's a solution.

Open svg with Inkscape, open text-properties sidebar, select text element as a whole, then select font-family, click ok.

![howto-change-font](https://github.com/performous/performous/assets/63517874/71bfd2c3-6830-4479-845f-3b8335c55e75)

**Comment by marwin89** [comment]
Due inactivtiy I close this issue - please re-open if needed
