### ISSUE TITLE
"Refresh database" in the webserver is not working unless the "Perform" screen is visited

### ISSUE THREAD

**Issue by HetorusNL** [performous/performous#900]
### Performous & operating system versions

Performous: 1.3.0-rc1
Operating system: Windows 11 Pro 22H2 x64

### What is the problem?

When Performous is started and the web server is opened, the "Refresh database" button is not working if the "Perform" screen isn't visited before. After visiting the "Perform" screen, the "Refresh database" button is working correctly and reloads the database

### Steps to reproduce

1. Open Performous
2. Open web server
3. Click "Refresh database" on the web server
4. [No songs are loaded] <- the issue
5. Click "Perform" in Performous
6. Click "Refresh database" on the web server
7. [Songs are loaded correctly] <- what should happen at step 4.

**Comment by Baklap4** [comment]
Closing since #901 has been merged to 1.3.0 branch
