### ISSUE TITLE
Sorting through the WebUI no longer functions

### ISSUE THREAD

**Issue by ooshlablu** [performous/performous#903]
### Performous & operating system versions

Performous: Latest Master
Operating System: Ubuntu 20.04 & 22.04

### What is the problem?

Clicking on "Artist" or any other of the sortable categories through the WebUI does not actually cause the list to sort on that parameter. The interface indicates that it should be sorted by the directional arrow changing.

When choosing different sort options in-game though, the WebUI sorts according to those. 

### Steps to reproduce

1. Start performous normally
2. If the webserver is not enabled, then enable it and restart Performous
3. When the game is started, go to the WebUI via http://(your-ip-or-hostname):8000
4. Try to sort using the categories available

### Additional context

This worked about a year ago, I'm not sure what has changed since then that could have caused this.

**Comment by Baklap4** [comment]
Is merged
