### ISSUE TITLE
1.3.0 not starting on Mac

### ISSUE THREAD

**Issue by MagicChocoRolls** [performous/performous#927]
### Performous & operating system versions

Performous: 1.3.0
OS: macOS 14.0

### What is the problem?

The new 1.3.0 version as well as the RC is not starting

### Steps to reproduce

1. Try starting

### Log(s) & preferences file(s)

➜  MacOS sudo ./performous-launcher
2023-10-27 21:55:14.765 defaults[1345:16112]
The domain/default pair of (kCFPreferencesAnyApplication, AppleLanguages) does not exist

**Comment by Lord-Kamina** [comment]
Fix committed already in #926

**Comment by Baklap4** [comment]
It'll be included in a patch version: 1.3.1. Thanks for notifying us @MagicChocoRolls
