### ISSUE TITLE
Image for freestyle notes is missing in performous+ theme

### ISSUE THREAD

**Issue by twollgam** [performous/performous#936]
### Performous & operating system versions

Performous 1.3+ (1.3-934-cf62611-alpha)
OS: Windows 11

### What is the problem?

The new themes performous+ did not show an image for freestyle notes. If one change to default theme the notes are displayed.

### Steps to reproduce

1. Switch to performous+ Black/Color
2. Start a song with freestyle notes
3. Free style notes will not be displayed

**Comment by marwin89** [comment]
@twollgam I fixed this issue withinin this PullReq
- #932 .

From a designer view I liked to have freestyle notes without "FREESTYLE"-text.

![Screenshot-freestylenotes](https://github.com/performous/performous/assets/63517874/8d5551a2-862b-4add-8407-2655ad5be17c)

**Comment by marwin89** [comment]
@twollgam , @Baklap4 the Freestyle notes design is inspired by other games. How would you like them? 👋 

![Image](https://github.com/performous/performous/assets/63517874/65ca1d4d-db6a-45b5-8cef-a32753e7d761)

**Comment by twollgam** [comment]
In my tests the freestyle notes are not visible enough. Maybe too much transparent color. 

The original freestyle notes show 'freestyle' as text. Don't know if we want that too? @Baklap4 ?

**Comment by marwin89** [comment]
How about this? The freestyle notes are more visible, less transparent. 🎵 

![Image](https://github.com/performous/performous/assets/63517874/4f927b32-5c7e-49a3-8153-0acbbaff61b8)

**Comment by twollgam** [comment]
Looks much better:+1

**Comment by marwin89** [comment]
Alrighty, I commited and pushed it. Problem will be resolved by merging:
- #932
