### ISSUE TITLE
Text colors in asian style have too less constrast in performous+ theme

### ISSUE THREAD

**Issue by twollgam** [performous/performous#937]
### Performous & operating system versions

Performous 1.3+ alpha
OS: Windows 11

### What is the problem?

Other than the default theme the text colors in asian style of performous+ theme differ not enough.

**Comment by marwin89** [comment]
@twollgam  thanks for QA 👋 , I fixed this in Pullreq:
- #932 

Is this what you meant? Another color for highlight lyrics? 

![Screenshot-lyrics-colored](https://github.com/performous/performous/assets/63517874/a080a585-61a3-4893-8b07-0339293642d7)
BTW: the fonts don't get filled well, there's still a white pixeling. Don't know why. 🤔

**Comment by Baklap4** [comment]
In discord this was also mentioned:

> would it be possible to get more stroke color feedback on the singing syllables? currently the letters are white, with a light-grey fill-stroke and that's very hard to read on bright whiteish backgrounds (which a lot of video's are)

Some suggestions from the event were also to fix the outline to be more prominent (the 1px black outline might be a bit too easy to miss)
