### ISSUE TITLE
Add marking songs defect ingame

### ISSUE THREAD

**Issue by twollgam** [performous/performous#942]
### Suggestion

Extend the menu which opens at pressing ESC while playing.

### Use case

Downloaded songs with usdb syncer are sometimes not usable. In this case it would be nice to mark them unusable. That gives an easy way to filter or sort them out.

**Comment by marwin89** [comment]
This is a good idea. 👋 

- Did you know that USDB SYNCER will use "Song-Checked"-Marker in Future? So you can filter songs that definitely work. 💡
- QA Team of USDB is building up right now and will start using song-check marker again. ✔️🎵

**Comment by Baklap4** [comment]
What would the technical details be @twollgam ?
Where are we gonna store this information

It might be usefull for the #240 aswell

**Comment by BWagener** [comment]
I really like this feature.

Another use case which is similar and might warrant consideration is having the same song multiple times. I'd love to be able to just let the game ignore all but one version of the same song.

An option to disable a song would be great for that. The only difference to the feature proposed in this issue would be the intent. 

The songs I'd like to disable using this feature would be songs that are duplicate, but don't need fixing.

**Comment by Baklap4** [comment]
This one is closed right as #978 is already merged into master? (if not please reopen)

**Comment by BWagener** [comment]
I suggest rethinking the current implementation.

Currently the "broken" flag is saved as a song attribute in the database.

This is problematic in cases where a song is present multiple times from different sources. All versions of the song regardless of source are considered broken as there's no information which file was originally marked as broken.

My suggestion would be to specifically mark a file as broken and ignore such files. A separate list could be saved to the db.
