### ISSUE TITLE
Sort songs by subfolders?

### ISSUE THREAD

**Issue by Lord-Kamina** [performous/performous#98]
I know there's a "sort by path" option already but I was thinking... why not a simple sort in sub-folders, kind of like one of the alternatives in USDX. At first you choose a folder, not a song (folders have different rules to determine a cover, or maybe you get a random song from inside that folder as preview) and then you get to choose your song from what's inside there. Escape/Cancel/whatever takes you back to the folder selection screen, up/down (or similar, since I think those have a function already) change between folders.

I doubt it'd be at all hard to make. I don't really know C++ (nor am I truly familiar with the game's code); I'd do it myself but I'm willing to bet somebody who's been involved in the game for a bit could have this done in a couple hours if not less and in that time I'd probably be stumbling around tinkering and learning what the basic game functions do...

**Comment by nieknooijens** [comment]
it's not really clear to me what the idea is of this.
I guess it's in the same way stepmania does it, but stepmania has a 2 folder limit, one for the category, and one for the songs themselves.
performous searches recursively, you can have multiple songs in the same folder and you can go 15 folders deep or more. Using the stepmania-like folder view means I have to re-order all of my songs since a lot of those have been converted from other programs. since performous didn't bother how i organised them I kept the folder hirarchy for backwards compability with their original programs.

**Comment by Lord-Kamina** [comment]
Ultrastar also has the option of sorting that way. The point is, it's IMO a
lot easier to categorize songs using subfolders. For example in my case I
have 4 or 5 very broad artificial categories that are a mix of genre and
language.

On Friday, 22 January 2016, niek nooijens <notifications@github.com> wrote:

> it's not really clear to me what the idea is of this.
> I guess it's in the same way stepmania does it, but stepmania has a 2
> folder limit, one for the category, and one for the songs themselves.
> performous searches recursively, you can have multiple songs in the same
> folder and you can go 15 folders deep or more. Using the stepmania-like
> folder view means I have to re-order all of my songs since a lot of those
> have been converted from other programs. since performous didn't bother how
> i organised them I kept the folder hirarchy for backwards compability with
> their original programs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/performous/performous/issues/98#issuecomment-174003181>
> .
>


-- 

-- 

Gregorio Litenstein Goldzweig [image: glit_qr.png]
Interno de Medicina
Facultad de Medicina Clí­nica Alemana - Universidad del Desarrollo

   - Fono: +56 9 96343643
   - E-Mail: g.litenstein@gmail.com

**Comment by skyli91** [comment]
I have folders by languages and it works great in ultrastar. I even have subfolders but when there are subfolders, it reads all the subfolders content to the main folder which is good. I'd like to have this option too

Now it can sort by folders, but jumping between them is nearly impossible.

**Comment by nieknooijens** [comment]
well... we could add a filter that sorts on path.

**Comment by skyli91** [comment]
yup that would be a useful workaround for us :) just for the main folders in the /Songs/ directory

**Comment by nieknooijens** [comment]
I was looking through the code and there is already a "sort by path" function.

**Comment by skyli91** [comment]
It's just shorting and not filtering. You still have to cycle through all the languages to switch to the language you want.

**Comment by nieknooijens** [comment]
you can type the song name of a song that's in the language you want to jump to.

**Comment by skyli91** [comment]
If i search for example "Japán" or "Magyar", i don't get all the songs that are in these folders, only some.

**Comment by Baklap4** [comment]
Can this be closed? Since we already have search by path functionality as @nieknooijens mentioned? The searching of @skyli91 should not fall under this issue i'm afraid?

**Comment by Lord-Kamina** [comment]
Yeah sure, go ahead.
